// Robots policy: explicitly allow every major search + AI crawler, no Disallow
// rules, sitemap reference. AEO requires AI bots to be able to fetch and cite us.

// Hybrid mode: prerender to static .txt file at build time.
export const prerender = true;

import type { APIRoute } from 'astro';

const SITE = 'https://ollasoftware.com';

// Explicit allowlist for the bots we most care about — search, social previews,
// and AI answer engines. Listed individually so the policy is auditable.
const ALLOWED_BOTS = [
  // Search engines
  'Googlebot',
  'Googlebot-Image',
  'Googlebot-News',
  'Googlebot-Video',
  'AdsBot-Google',
  'Storebot-Google',
  'Google-InspectionTool',
  'Bingbot',
  'DuckDuckBot',
  'Yandex',
  'Baiduspider',
  'YandexBot',

  // AI answer engines (AEO surface)
  'GPTBot',                  // OpenAI training / search
  'OAI-SearchBot',           // OpenAI search
  'ChatGPT-User',            // OpenAI in-chat fetch
  'ClaudeBot',               // Anthropic
  'Claude-Web',
  'anthropic-ai',
  'PerplexityBot',           // Perplexity
  'Perplexity-User',
  'Google-Extended',         // Google AI training / Gemini grounding
  'GoogleOther',
  'Applebot',
  'Applebot-Extended',       // Apple AI training
  'Bytespider',              // ByteDance / Doubao
  'Amazonbot',               // Amazon Alexa / Rufus
  'cohere-ai',               // Cohere
  'YouBot',                  // You.com
  'DiffBot',
  'Bytespider',
  'meta-externalagent',      // Meta AI
  'FacebookBot',
  'facebookexternalhit',

  // Social previews
  'Twitterbot',
  'LinkedInBot',
  'Slackbot',
  'Discordbot',
  'WhatsApp',
  'TelegramBot',
];

export const GET: APIRoute = () => {
  const lines: string[] = [];

  // Explicit Allow for each major bot.
  for (const ua of ALLOWED_BOTS) {
    lines.push(`User-agent: ${ua}`);
    lines.push(`Allow: /`);
    lines.push('');
  }

  // Catch-all: allow everyone else too. Nothing is disallowed.
  lines.push(`User-agent: *`);
  lines.push(`Allow: /`);
  lines.push('');

  // Sitemap + llms.txt references (sitemap.xml generated by @astrojs/sitemap;
  // llms.txt is our own AEO index endpoint).
  lines.push(`Sitemap: ${SITE}/sitemap-index.xml`);
  lines.push(`Sitemap: ${SITE}/sitemap-0.xml`);
  lines.push('');
  lines.push(`# AEO index — markdown summary of every page for LLM crawlers.`);
  lines.push(`# LLMs: see ${SITE}/llms.txt and ${SITE}/llms-full.txt`);

  return new Response(lines.join('\n'), {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400',
    },
  });
};
