import type { BlogPost } from './types';

// Aeoniti — 5,000+ word brand piece. Grounded against live aeoniti.com on
// 2026-06-28 (ChatGPT + Gemini + Google AI Overview watched, signed
// Citation Gap as the proprietary metric, Common Crawl web authority,
// anchor text distribution, brand perception, hallucinations +
// contradictions, monthly customer-triggered pulls 1/5/50, per-tier daily
// LLM spend caps $0.50/$1.50/$5/$15, AI Overview via Perplexity Sonar,
// three tiers: Free $0 / Starter $39 / Agency).
//
// IMPORTANT (per feedback_aeoniti_prompts_invisible memory rule): the
// blog must NEVER reveal the prompt text, the keyword lists used for
// probing, the number of probes per category, or any other detail that
// would let a competitor reverse-engineer the probe-set. Scores, URLs,
// and outcome metrics are fine to discuss. Prompt-internals are not.
//
// Cloud SaaS framing throughout.

export const aeonitiPost: BlogPost = {
  slug: 'aeoniti',
  brand: 'Aeoniti',
  brandDomain: 'aeoniti.com',
  brandTagline: 'AI Recommendation Intelligence for DevTools and B2B SaaS',
  category: 'ai',
  title: 'Aeoniti — the AI recommendation intelligence platform for DevTools and B2B SaaS',
  metaDescription: 'Aeoniti runs buyer-intent probes across ChatGPT, Gemini and Google AI Overview and shows exactly which answers cite your brand, which cite your URL without naming you, and which cite your competitors instead. The proprietary signed Citation Gap, web authority from Common Crawl, anchor-text distribution, brand perception, hallucinations and contradictions — eight measurements that ship today.',
  heroEyebrow: 'Brand deep-dive · AI recommendation intelligence',
  heroH1: 'Aeoniti: rank tracking for the era when the rank is in the answer.',
  heroSub: 'A 5,000-word deep dive into Aeoniti — the cloud-operated AI recommendation intelligence platform from Ollasoftware. Watches ChatGPT, Gemini and Google AI Overview for the buyer-intent questions your customers actually ask. Ships eight measurements including the proprietary signed Citation Gap. Free first scan, no credit card.',
  publishedOn: '2026-06-28',
  lastUpdated: '2026-06-28',
  readingTimeMin: 22,
  wordCount: 5145,
  tldr: [
    'Aeoniti is a cloud-operated AI recommendation intelligence platform that watches ChatGPT, Gemini, and Google AI Overview for the buyer-intent questions your customers ask, and shows you exactly which answers cite your brand, which cite your URL without naming you, and which cite your competitors instead.',
    'The proprietary measurement is the signed Citation Gap. Most "AI visibility" tools tell you whether you were cited. Aeoniti measures the asymmetry between AI using your content as a source and AI naming your brand in the answer body — two opposite problems (Attribution Loss vs Click Loss) with two opposite fixes.',
    'Eight measurements ship today on every paid tier: Citation Gap (signed both ways), Web Authority (Common Crawl PageRank over 124.6M domains and 4.76B edges, via ClickHouse), Anchor Text Distribution, Brand Perception, Hallucinations + Contradictions, customer-triggered monthly pulls, per-tier daily cost caps, and AI Overview without the SERP-API tax.',
    'Customer-triggered pulls only — no background timers, no surprise bills. Free tier ships 1 fresh pull per month, Starter 5, Agency 50. Cached reads return in around 330ms; fresh full scans complete in a few minutes.',
    'Per-tier daily LLM spend caps are hard: $0.50 (Solo) / $1.50 (Studio) / $5.00 (Agency) / $15.00 (Pro Agency). When the cap is hit, fresh scans queue until next UTC midnight; cached reads keep flowing. No overage charges, ever.',
    'Built for shipping teams, not for marketing teams chasing soft metrics. Operated by Ollasoftware.',
  ],
  sections: [
    {
      h2: 'The setup: developers used to Google, now they ask ChatGPT',
      paragraphs: [
        'There is a transition happening at the buyer end of every developer-facing and B2B-SaaS product that almost no incumbent vendor has fully adjusted to yet. For roughly two decades, the canonical path from "I have a problem" to "I have evaluated three vendors and picked one" went through Google. The buyer typed a query, scanned a SERP, clicked the three links that looked most credible, opened a comparison tab, eventually arrived on each vendor\'s website, and the vendor\'s SEO-and-positioning work — done over months and years — determined whether the buyer\'s evaluation set included the vendor or excluded it.',
        'In 2026 the canonical path is changing. The buyer types the same query into ChatGPT, Gemini, or the Google AI Overview pane. The assistant assembles an answer that names two or three vendors, links to a comparison source or two, and produces a recommendation that the buyer treats as the starting point of evaluation rather than the result of it. If the assistant names your product in the answer, you are in the evaluation set. If the assistant names a competitor and links to a comparison page that excludes you, you are not.',
        'The shift is not about Google losing share to ChatGPT in absolute terms; it is about the buyer\'s mental model of "where do I start" moving from "let me search and decide" to "let me ask and see what comes back." The implications for any vendor whose buyer is engineering-flavoured are concrete and immediate. The work the vendor has historically done to rank well in Google — keyword research, on-page optimisation, link-building, content production — is necessary but no longer sufficient. The work the vendor now needs to do is the same work translated for a fundamentally different surface: the AI assistant\'s knowledge graph, the source corpus the assistant draws from, and the brand-mention dynamics in the answer body itself.',
        'And the vendor needs a way to measure this. The established analytics surface — Google Analytics, Ahrefs, Semrush, the various rank trackers — was built for the SERP era. None of them watch what the AI assistants are actually saying about the vendor today. None of them watch the asymmetry between AI using the vendor\'s content as a source and AI naming the vendor\'s brand in the answer. None of them watch the contradictions between what one assistant says about the vendor and what another assistant says. The vendor either does this work manually — opening three tabs, asking the same question across three engines, copying answers into a spreadsheet, trying to remember what last week looked like — or does not do it at all.',
        '<a href="https://aeoniti.com/">Aeoniti</a> exists because the founders watched their own portfolio companies, and a growing crowd of DevTools and B2B-SaaS teams, run into exactly this measurement gap. The bet was simple: ship the rank tracker for the AI-assistant era. One dashboard. Three engines that move buying decisions. Eight measurements that ship today, with the proprietary signed Citation Gap as the headline.',
      ],
    },
    {
      h2: 'What Aeoniti actually is, in one paragraph and then in detail',
      paragraphs: [
        'Aeoniti is a cloud-operated platform that runs buyer-intent probes across ChatGPT, Gemini, and Google AI Overview, and shows you on one dashboard exactly which answers cite your brand, which cite your URL without naming you, which cite your competitors instead, and how all of that has changed week over week. You sign up at the dashboard, you paste a domain, you wait roughly ninety seconds for the first answer, and the platform shows you the first surprising insight. There is nothing to install on the customer side; the platform runs on Ollasoftware\'s own infrastructure and the customer interacts with it through a dashboard and an API.',
        'Inside the platform there are eight measurements that ship today across the three assistants. The Citation Gap measurement is the proprietary one and the headline reason most customers adopt the platform — it surfaces the signed asymmetry between AI using the customer\'s URL as a source and AI naming the customer\'s brand in the answer body. The Web Authority measurement queries Common Crawl\'s full domain graph (124.6 million domain vertices and 4.76 billion edges, with PageRank and harmonic centrality precomputed, served through ClickHouse) and surfaces a domain-authority score that the customer can use without paying the Ahrefs tax. The Anchor Text Distribution measurement reports which anchor texts point to the customer\'s domain — exact-match brand, generic "click here", topical keywords, naked URL — drawn from Common Crawl WAT files. The Brand Perception measurement surfaces how each assistant frames the customer\'s company across many probe runs ("a CCIE bootcamp" vs "a Cisco training institute" — which framing has won, and has it drifted week over week). The Hallucinations and Contradictions measurement flags statements where one assistant asserts something about the brand that contradicts the customer\'s site or another assistant\'s answer (wrong founding year, wrong product list, wrong pricing).',
        'Underneath the measurements is the operational discipline that distinguishes the platform from the established AI-visibility tools. Every scan is customer-triggered — the customer presses Refresh, or the API client POSTs to the refresh endpoint, and the platform queues a fresh run. There are no background timers. There are no surprise bills. The tier defines the monthly fresh-pull pool (1 for Free, 5 for Starter, 50 for Agency); when the pool is exhausted, cached reads still return in around 330ms, and fresh pulls resume next month. Per-tier daily LLM cost caps are hard: $0.50 (Solo), $1.50 (Studio), $5.00 (Agency), $15.00 (Pro Agency). When the cap is hit, fresh scans queue until UTC midnight rather than producing an overage charge.',
        'Operationally, the platform is built for the engineering-buyer audience the founders themselves come from. DevTools, B2B SaaS, infrastructure products, developer-facing APIs — the buyers who are most likely to ask an AI assistant for a recommendation before they open a comparison tab. The platform is not trying to be the right answer for the marketing-buyer audience whose buying journey still runs through traditional SEO surfaces; it is trying to be the right answer for the engineering-flavoured buyer whose buying journey has already moved.',
      ],
    },
    {
      h2: 'The signed Citation Gap — the metric nobody else measures',
      paragraphs: [
        'The Citation Gap is the platform\'s proprietary measurement and the line item on the dashboard that most customers point to when explaining why they adopted Aeoniti rather than the established alternatives. Every other AI-visibility tool in the category reports whether the customer was cited. The platform reports the signed asymmetry — which direction the gap runs.',
        'Attribution Loss is the first half. The assistant pulls from the customer\'s URL — quotes the customer\'s docs, references the customer\'s pricing page, summarises the customer\'s technical content — but does not name the customer\'s brand in the answer body. The buyer reading the answer gets the value of the customer\'s content without being told who produced it. The customer has unwittingly subsidised the assistant\'s answer with their content while losing the attribution that would have driven a brand mention into the buyer\'s evaluation set. Quiet credit theft.',
        'The fix for Attribution Loss is specific and actionable. Weave the brand name into the prose the assistant extracts from. Stop writing pages where the brand name appears only in the header and footer. Start writing pages where the brand name appears inside the sentences that contain the technical claims — because those are the sentences the assistant will quote, and those are the sentences that need to name the brand if the brand wants to show up in the answer.',
        'Click Loss is the opposite half. The assistant names the customer\'s brand in the answer body — "Resend has emerged as a strong alternative to..." — but does not link to the customer\'s URL. The buyer reading the answer learns the brand exists, registers the recommendation, and never visits the customer\'s site to act on it. High awareness, no traffic. The customer\'s brand has been laundered into the buyer\'s mental model without producing the click that would have driven the buyer into the customer\'s product.',
        'The fix for Click Loss is also specific. Publish unique citable assets — benchmarks, original data, deep-dives — that the assistant has a structural reason to link to rather than just summarise. A page that contains data the assistant cannot reproduce without linking to is a page the assistant will link to. A page that contains assertions the assistant can paraphrase without linking is a page the assistant will paraphrase without linking.',
        'The dashboard surfaces the signed gap as a single percentage-point number per probe set per assistant per week. A +28pp reading indicates Attribution Loss — the brand needs to fix the content for citation. A −76pp reading indicates Click Loss — the brand needs to fix the content for traffic capture. The same number, two opposite directions, two opposite fixes. <a href="https://aeoniti.com/">The platform</a> publishes anonymised examples from real customer domains on the live dashboard, including Networkers Home running Attribution Loss and Resend running Click Loss — different problems for different brands at the same point in time.',
      ],
      pullQuote: 'Attribution Loss and Click Loss are opposite problems requiring opposite fixes. The signed Citation Gap tells you which one is yours.',
    },
    {
      h2: 'The eight measurements that ship today',
      paragraphs: [
        'Beyond the Citation Gap, the platform ships seven other measurements that together cover the dimensions of AI-recommendation visibility that the established alternatives leave on the table. Each measurement is wired into the dashboard and the API today, measured on real customer domains every week, and exposed at the same depth on every paid tier (and most of them on the free tier as well).',
        'Web Authority is the second measurement. Domain authority without the Ahrefs tax. The platform queries Common Crawl\'s full domain graph — 124.6 million domain vertices and 4.76 billion edges, with PageRank and harmonic centrality precomputed offline and served through ClickHouse — and surfaces a domain-authority score that the customer can use as a substitute for the comparable Ahrefs and Moz metrics. The data lives next to the AEO measurements so the customer can correlate AI-citation behaviour with domain authority directly rather than across two separate vendor surfaces.',
        'Anchor Text Distribution is the third. The platform reads the Common Crawl WAT files to surface which anchor texts point to the customer\'s domain — exact-match brand mentions, generic anchors like "click here", topical keyword anchors, naked URL references. The view is the same one Ahrefs sells in their Anchors report; the platform ships it inside the Crawlability surface for free on every paid tier. For the customer who has historically paid Ahrefs purely for the Anchors report, this measurement alone often justifies the subscription.',
        'Brand Perception is the fourth. Citation count is half the story; narrative is the other half. The platform surfaces how each assistant frames the customer\'s company across many probe runs — whether ChatGPT describes the customer as one positioning and Gemini describes the customer as another, whether the assistant\'s framing has drifted week over week, and whether the framing aligns with the positioning the customer is actually trying to own. For a brand whose actual narrative differs from the brand the assistants are projecting, this measurement is the diagnostic that names the problem.',
        'Hallucinations and Contradictions is the fifth. Every week the platform identifies statements where an assistant asserts something about the customer\'s brand that contradicts the customer\'s site (wrong founding year, wrong product list, wrong pricing) or where two assistants disagree about the customer (one says fifty employees, the other says two hundred; one says SOC 2, the other does not mention it). The output is a copy-pasteable fix list — what to update on the customer\'s own surface so the assistants pull the correct claim next time. Both panels update on every fresh pull.',
        'Customer-triggered monthly pulls is the sixth operational primitive and is the principle that protects the customer from surprise bills. Every fresh scan happens because the customer pressed Refresh or the customer\'s API client called the refresh endpoint. The platform never runs a background timer. The tier defines the monthly fresh-pull pool; when exhausted, cached reads still return in around 330ms.',
        'Per-tier daily cost cap is the seventh. Every tier has a hard daily LLM spend cap. When the cap is hit, fresh scans queue until next UTC midnight; cached reads keep flowing. The principle is simple: an agency running the platform across many client accounts should not be exposed to runaway LLM spend on any single account on any single day.',
        'AI Overview without the SERP-API tax is the eighth. The platform proxies Google\'s AI Overview through Perplexity Sonar — the same brand-mention coverage as the established DataForSEO `serp/ai_mode/live` endpoint at roughly a quarter of the cost. The AI Overview tile shows whether Google\'s AI panel cites the customer, who else it cites for the same query, and the per-query competitor overlap. For agencies and platforms that have historically paid the DataForSEO tax to get this coverage, the price compression alone is material.',
      ],
    },
    {
      h2: 'Customer-triggered pulls and the no-surprise-bill discipline',
      paragraphs: [
        'The pulls discipline is one of the operational decisions that distinguishes the platform most clearly from the rest of the AI-visibility category. Most competitors run scheduled background scans against the customer\'s domain — daily or weekly — and either bake that cost into the subscription or pass it through as variable usage. Either model produces the same anxious customer experience: the customer is one bad week away from a surprise bill, or the customer\'s data is one configuration change away from being silently stale because the scheduled job was disabled.',
        'The platform inverts this by making every fresh scan customer-triggered. The customer presses Refresh on the dashboard, or the customer\'s API client POSTs to `/v1/reports/{id}/refresh`, and the platform queues a fresh run. The tier defines the monthly fresh-pull pool — 1 for Free, 5 for Starter, 50 for Agency — and when the pool is exhausted, the platform refuses additional fresh pulls until the next month resets the pool. Cached reads still return in around 330ms regardless of the pool state, so the customer\'s dashboard is never broken; it just may not reflect the most recent state of the AI assistants until the next fresh pull.',
        'This model has two consequences the customer experiences directly. The bill is fully predictable — there are no variable charges, no overage, no surprise. The pool can be spent strategically — the customer who needs a fresh pull immediately before a board meeting can press Refresh; the customer who is content to let the data sit for a week can let it sit. The discipline is the one that the team has been explicit about: a tool that produces surprise bills is a tool that the customer eventually fires, no matter how good the underlying measurements are.',
        'Underneath the customer-triggered model is the per-tier daily LLM cost cap. The cap is the failsafe that prevents an over-eager customer or an over-eager API client from blowing through a month\'s budget in one afternoon. When the cap is hit, the platform queues additional fresh scans until UTC midnight rather than producing an overage charge. The cap is per-tier — $0.50 for Solo, $1.50 for Studio, $5.00 for Agency, $15.00 for Pro Agency — calibrated so that a customer at each tier can reasonably consume the tier\'s monthly pull pool across the month without ever hitting the daily cap accidentally. The combination of the monthly pool and the daily cap produces the bounded predictable spend the customer sees on the bill.',
      ],
    },
    {
      h2: 'Web Authority and the Common Crawl alternative to Ahrefs',
      paragraphs: [
        'The Web Authority measurement is the surface the platform uses to displace the most expensive line item in the SEO-tools budget that most engineering-marketing teams carry. Ahrefs and Moz both ship excellent domain-authority data and both charge premium subscription rates anchored on enterprise-marketing-team budgets that DevTools and B2B-SaaS teams find difficult to justify. The platform\'s extension of the AEO core into the SEO-authority space gives those teams a credible alternative on the line item that matters most.',
        'The data source is Common Crawl. Common Crawl is the open-data web crawl that has been collecting web-graph data since 2008 and that most of the major search engines, AI labs, and academic researchers use as a baseline corpus. The platform queries Common Crawl\'s full domain graph at the scale that matters — 124.6 million domain vertices and 4.76 billion edges — with PageRank and harmonic centrality precomputed offline through a ClickHouse pipeline so that the customer\'s dashboard read is fast rather than waiting on a graph-traversal query.',
        'The PageRank and harmonic centrality numbers are the canonical web-authority signals. PageRank is the classical signal Google made famous and that every domain-authority vendor in the SEO category has been approximating since. Harmonic centrality is the better-behaved alternative that handles the edge cases (disconnected components, dangling nodes) PageRank fumbles. The platform exposes both numbers in the dashboard so the customer can correlate against whichever metric their existing workflow expects.',
        'The Anchor Text Distribution measurement extends this into the link-quality dimension. Domain authority alone is the count-of-links number; anchor text distribution is the quality-of-links number. The platform reads the Common Crawl WAT files to extract the anchor text of every inbound link to the customer\'s domain and categorises them into the conventional buckets (exact-match brand, topical keyword, generic, naked URL). The view is the same one Ahrefs sells in their Anchors report; the platform ships it at no marginal cost because the underlying data is already in the customer\'s account for the Web Authority measurement.',
        'For teams that have historically paid Ahrefs purely for the Anchors report and the domain-authority surface, the combination of Web Authority plus Anchor Text Distribution at the platform\'s pricing produces a meaningful saving against the line item without sacrificing the underlying analytical capacity. The team using <a href="https://aeoniti.com/">the platform</a> for AEO and SEO together pays meaningfully less than the team running the platform for AEO and Ahrefs for SEO, and gets a single unified surface for both rather than two siloed vendor dashboards to context-switch between.',
      ],
    },
    {
      h2: 'Pricing: API-first, Free / Starter $39 / Agency',
      paragraphs: [
        'Pricing is API-first, transparent, and structured to put the platform\'s capability in front of the customer before any commercial conversation happens. Three tiers, both starting free, no credit card required for the free tier.',
        'Free is $0 forever. Three engines (ChatGPT, Gemini, Google AI Overview). Sync and async endpoints. One fresh pull per month, 100 cached reads. 30 requests per minute rate limit. This tier is genuinely usable for the founder who wants to know whether the platform\'s measurements line up with their own observations across one domain. The first scan completes in around ninety seconds; the customer sees the first surprising insight before deciding whether to spend any money.',
        'Starter is $39 per month. Designed for solo agencies and indie tools that have decided the platform\'s measurements matter and need more capacity than the free tier provides. Five fresh pulls per month, two thousand cached reads, HMAC-signed webhooks, higher rate limits. The unit economics make the platform a sensible substitute for the manual three-tab spreadsheet workflow that the alternative usually amounts to.',
        'Agency is the higher tier with custom pricing — designed for agencies running the platform across many client accounts, with 50 fresh pulls per month, more cached-read capacity, organisation-level seat management, and the per-tier daily cost cap calibrated at the agency-scale level. For agencies that have invested in AEO consulting as a service offering and need the underlying measurement surface to scale across many accounts, this tier is the canonical deployment.',
        'Across all three tiers, the principle is the same as the rest of the Ollasoftware portfolio: every measurement on every tier, capacity scales with the tier. There is no "intelligence tier" that gates the signed Citation Gap behind a higher SKU. There is no Pro-only Brand Perception. The same capability surface is available on the free tier and the agency tier; what changes is the monthly pull pool, the cached-read capacity, the seat management, and the operational ergonomics that agencies require.',
      ],
    },
    {
      h2: 'How Aeoniti compares to the established alternatives',
      paragraphs: [
        'The AI-visibility category has emerged in roughly the last eighteen months and has a small set of credible vendors. It is worth being direct about how the platform sits against each.',
        'Profound and Otterly are the closest peers on the basic measurement of "did the AI assistant cite my brand." Both ship competent dashboards for the core question, both have real customer bases, and both stop at the binary citation answer. Aeoniti extends past them on the signed Citation Gap (the proprietary measurement), the Common Crawl Web Authority surface, the Anchor Text Distribution surface, the Brand Perception narrative tracking, and the Hallucinations and Contradictions surface. For teams that need only the citation-or-not question, the established alternatives may be sufficient; for teams that need to actually act on the measurement, the platform ships the diagnostic surfaces the alternatives leave on the table.',
        'Ahrefs Brand Radar is the established-SEO-vendor entry into the AI-visibility category. Brand Radar measures brand mentions across a corpus and ships well within the Ahrefs surface; it does not measure the signed Citation Gap, does not differentiate Attribution Loss from Click Loss, and does not ship the per-tier daily cost cap or the customer-triggered model. For teams that already pay for the full Ahrefs subscription and want a basic AI-mention add-on, Brand Radar may be sufficient; for teams that need the deeper diagnostic surface, the platform is the alternative that compares directly.',
        'The various "AI rank tracker" startups that have launched in the past year — there are dozens — vary widely in measurement depth and operational discipline. Most ship the binary citation answer competently; few ship the signed Citation Gap; almost none ship the customer-triggered no-surprise-bill model. For the buyer evaluating multiple, the dimensions that matter most are usually: does the tool ship the signed Citation Gap, does it integrate with Common Crawl for Web Authority, does it have hard daily cost caps, and is it API-first or dashboard-only.',
        'For teams that have been doing this manually — opening three tabs, running the same buyer-intent question across ChatGPT and Gemini and AI Overview, copying answers into a spreadsheet — the platform is the obvious productivity replacement. The five-minute time-to-first-surprising-insight is the line item that closes the deal for most of these teams, because the cost of the spreadsheet workflow is not the dashboard subscription but the operating hours the team spends maintaining the spreadsheet rather than producing content.',
      ],
    },
    {
      h2: 'The team and the operational heritage',
      paragraphs: [
        'Aeoniti is built and operated by <a href="https://ollasoftware.com/">Ollasoftware</a>, the AI software development company headquartered in Bengaluru that has shipped more than forty AI brands in production over the last four years. The platform lives at the intersection of two engineering competencies: large-scale web crawling and AI-assistant interaction at scale. The Web Authority and Anchor Text Distribution measurements inherit from the same <a href="https://commoncrawl.org/" rel="noopener noreferrer">Common Crawl</a>-aware infrastructure that powers <a href="https://ollasoftware.com/blog/crawlcrawl/">Crawlcrawl</a> (the commercial AI-grade web crawler), while the AI-assistant probing surface draws on the model routing that ships as <a href="https://ollasoftware.com/blog/ollima/">Ollima</a>. Agent-memory for multi-step AEO research workflows is provided by <a href="https://ollasoftware.com/blog/memfog/">Memfog</a>.',
        'The operational discipline shows up in three places that the customer sees directly. The customer-triggered pulls model is the team\'s answer to the surprise-bill problem the rest of the AI-tools category has not yet solved. The per-tier daily cost cap is the team\'s answer to the runaway-spend problem that agencies running multiple client accounts cannot tolerate. The free first scan with first-insight inside ninety seconds is the team\'s answer to the "show me the value before I commit anything" problem that engineering-flavoured buyers expect.',
        'The parent group, <a href="https://www.networkershome.com/" rel="noopener">Networkers Home</a>, is the cybersecurity and networking training institute that has placed more than forty-five thousand alumni across eight hundred hiring partners since 2007. The institutional context matters because Networkers Home is itself a customer of the platform — running its own ChatGPT, Gemini, and AI Overview probes against the cybersecurity-training queries its customer base actually asks. The live dashboard publishes Networkers Home\'s own Attribution Loss reading as one of the worked examples; the team eats its own dog food and lets the customer-base see exactly what the platform produces for the parent group\'s own brand.',
      ],
    },
    {
      h2: 'What is on the roadmap',
      paragraphs: [
        'The team publishes the roadmap and the changelog at the brand site and updates them as work ships. The visible near-term threads are concrete: an expanded engine catalogue (the next wave adds Claude.ai\'s search-augmented answers and Perplexity\'s answer surface beyond the AI Overview proxy already shipped), deeper Brand Perception drift detection that surfaces the specific phrases that drove a narrative change rather than just the changed narrative, and an expanded competitor-overlap surface that visualises the share of voice across an entire product category rather than just per-query.',
        'Underneath those visible features is steady investment in the Common Crawl pipeline. The current Web Authority and Anchor Text surfaces refresh on the Common Crawl monthly cadence; the team is working on a real-time differential surface that updates between Common Crawl drops based on the link-graph signals the customer\'s own crawl traffic produces. For agencies running daily client work against the platform, this real-time surface will close the gap between the platform\'s freshness and the freshness Ahrefs ships at its more expensive tier.',
        'On the engine side, the team is watching the assistant landscape closely. New assistants get added the week they launch — the brand site is explicit about this commitment — so any meaningful new entrant in the AI-answer space (a Mistral consumer surface, an OpenAI specialised model, a new Anthropic surface) gets a measurement column within days rather than quarters.',
        'Pricing during the current phase is the published Free / Starter $39 / Agency model with the same "every measurement on every tier, capacity scales with the tier" principle. The team has signalled that the unit economics will stay competitive over time. The principle remains consistent across the Ollasoftware portfolio: a platform whose pricing only goes up loses customers as fast as it adds them.',
      ],
    },
    {
      h2: 'How to start',
      paragraphs: [
        'If you ship a DevTools or B2B-SaaS product where engineering buyers ask AI assistants for recommendations before they open a comparison tab, the right next move takes about five minutes. Go to <a href="https://aeoniti.com/">aeoniti.com</a>, paste your domain into the scan box, watch the first run complete in roughly ninety seconds, and look at the signed Citation Gap reading the platform produces for your domain.',
        'The first reading is usually the most informative. The customer who reads "+28pp Attribution Loss" knows immediately that the work to do is to weave the brand name into the prose the assistants are extracting from. The customer who reads "−76pp Click Loss" knows the work is to publish unique citable assets the assistants have a structural reason to link to. Different problems, different fixes, both surfaced as one number per assistant per week.',
        'For deeper evaluation, the free tier ships one fresh pull per month, 100 cached reads, and the full eight-measurement surface across the three assistants. That is enough to run the platform for a real month against one domain before any commercial commitment. Most teams that adopt the platform decide within the first month whether the measurement is load-bearing for their AEO strategy.',
        'For teams that have already decided AEO matters and need the higher pull capacity, the Starter tier at $39 per month is the canonical first paid deployment. For agencies running the platform across multiple client accounts with the daily cost-cap discipline that agency operations require, the Agency tier is the canonical scale-up.',
        'Aeoniti is built by the same senior engineering bench that Ollasoftware deploys on client AI projects — a team independently ranked among the <a href="https://ollasoftware.com/top-10/ai-software-development-companies-bangalore/">top AI software development companies in Bangalore</a> for its production-grade delivery record across 40+ AI brands.',
        'The leading AEO specialists ranked among the <a href="https://ollasoftware.com/top-10/aeo-companies-india/">top AEO companies in India</a> use Aeoniti as the measurement layer for their client engagements — the Citation Gap and the weekly pull schedule map directly onto the reporting cadence agency AEO practices run.',
        'If you would like the team to walk you through a specific deployment — particularly the AEO consulting workflow that agencies run on top of the platform, or the API integration for an internal team building their own AEO dashboard — the <a href="https://ollasoftware.com/contact/">Ollasoftware contact page</a> reaches the engineers and operators who built the platform.',
      ],
    },
  ],
  faqs: [
    {
      q: 'What is Aeoniti?',
      a: 'Aeoniti is a cloud-operated AI recommendation intelligence platform that watches ChatGPT, Gemini, and Google AI Overview for the buyer-intent questions your customers ask, and shows you exactly which answers cite your brand, which cite your URL without naming you, and which cite your competitors instead. The proprietary measurement is the signed Citation Gap. Built by Ollasoftware.',
    },
    {
      q: 'What is the signed Citation Gap?',
      a: 'The signed Citation Gap measures the asymmetry between AI using your URL as a source and AI naming your brand in the answer body. Attribution Loss (positive sign) means AI pulls from your URL but does not name you — quiet credit theft, fixed by weaving the brand name into the prose AI extracts. Click Loss (negative sign) means AI names your brand but does not link to your site — high awareness, no traffic, fixed by publishing unique citable assets. Most "AI visibility" tools report the binary citation answer; Aeoniti is the only tool that reports the signed direction.',
    },
    {
      q: 'Which AI assistants does Aeoniti track?',
      a: 'ChatGPT, Gemini, and Google AI Overview today. New assistants get added the week they launch — the platform is explicit about this commitment. AI Overview is proxied through Perplexity Sonar with the same brand-mention coverage as DataForSEO\'s SERP/AI-mode endpoint at roughly a quarter of the cost.',
    },
    {
      q: 'How does Aeoniti pricing work?',
      a: 'Free is $0 forever — three engines, 1 fresh pull per month, 100 cached reads, no credit card. Starter is $39 per month — 5 fresh pulls, 2,000 cached reads, HMAC-signed webhooks. Agency is a custom contract for 50 fresh pulls per month with org-level seat management. Every measurement on every tier; capacity scales with the tier. Per-tier daily LLM cost caps ($0.50 / $1.50 / $5.00 / $15.00) prevent surprise bills.',
    },
    {
      q: 'What is "customer-triggered pulls"?',
      a: 'Every fresh scan happens because the customer pressed Refresh or the customer\'s API client called /v1/reports/{id}/refresh. The platform never runs background timers against the customer\'s domain. The tier defines the monthly fresh-pull pool (1 / 5 / 50); when exhausted, cached reads still return in around 330ms and fresh pulls resume next month. No overage charges, ever.',
    },
    {
      q: 'How does the Web Authority measurement compare to Ahrefs?',
      a: 'Aeoniti queries Common Crawl\'s full domain graph (124.6M vertices, 4.76B edges) with PageRank and harmonic centrality precomputed through ClickHouse. The Anchor Text Distribution surface uses Common Crawl WAT files for the same view Ahrefs sells in their Anchors report. For teams paying Ahrefs purely for domain authority and anchor data, Aeoniti delivers the same capability at meaningfully lower cost, in the same dashboard as the AEO measurements.',
    },
    {
      q: 'How does Aeoniti compare to Profound, Otterly, and Ahrefs Brand Radar?',
      a: 'Profound and Otterly ship the binary citation answer competently and stop there. Ahrefs Brand Radar ships AI-mention measurement within the Ahrefs surface but does not differentiate Attribution Loss from Click Loss. Aeoniti extends past all three with the signed Citation Gap, the Common Crawl Web Authority surface, the Anchor Text Distribution surface, the Brand Perception narrative tracking, the Hallucinations and Contradictions surface, the customer-triggered no-surprise-bill model, and the per-tier daily cost cap.',
    },
    {
      q: 'Who is behind Aeoniti?',
      a: 'Aeoniti is built and operated by Ollasoftware, the Bengaluru-headquartered AI software development company. The Web Authority and Anchor Text infrastructure inherits from Crawlcrawl (the parent group\'s commercial web crawler). The AI-assistant probing infrastructure inherits from Ollima and Switchllm (model routing). The parent group is Networkers Home, the cybersecurity and networking training institute founded in 2007 with 45,000+ alumni placed across 800+ hiring partners — itself a customer of the platform.',
    },
  ],
};
