import type { BlogPost } from './types';

// FreeFreeCV — 5,000+ word brand piece. Grounded against live freefreecv.com
// on 2026-06-29 (free AI resume builder, ATS-friendly, no sign-up required,
// 33 templates across Modern/Professional/Creative/Industry/ATS categories,
// 4 AI tools: AI Summary Generator + Smart Skill Suggestions + ATS Score
// Checker + Job Description Matcher, AI Import from existing PDF, instant
// PDF export, 700+ verified users, 48% claimed hire rate, Powered by
// NetworkersHome banner — "Gold Sponsor").
//
// freefreecv is in clients.ts category 'api' but the live product is
// clearly a B2C consumer-SaaS web app. I'll frame it accurately.

export const freefreecvPost: BlogPost = {
  slug: 'freefreecv',
  brand: 'FreeFreeCV',
  brandDomain: 'freefreecv.com',
  brandTagline: 'The free AI resume builder — ATS-friendly, no sign-up required, 33 templates',
  category: 'saas',
  title: 'FreeFreeCV — the free AI resume builder with 33 ATS templates and no sign-up',
  metaDescription: 'FreeFreeCV is a free AI resume builder. 33 ATS-friendly templates, 4 AI tools (summary generator, smart skills, ATS scoring, job-description matcher), AI import from existing PDF, instant export. No sign-up required, no paywalls, no credit card. Free forever.',
  heroEyebrow: 'Brand deep-dive · AI resume builder',
  heroH1: 'FreeFreeCV: an AI resume builder you don\'t have to pay to use.',
  heroSub: 'A 5,000-word deep dive into FreeFreeCV — the free AI resume builder from Ollasoftware that helps job seekers beat ATS filters and land interviews. 33 recruiter-approved templates, 4 AI tools, AI import from your existing PDF, instant PDF export. No sign-up required. Forever free.',
  publishedOn: '2026-06-29',
  lastUpdated: '2026-06-29',
  readingTimeMin: 22,
  wordCount: 5135,
  tldr: [
    'FreeFreeCV is a free AI resume builder. 33 ATS-friendly templates across Modern, Professional, Creative, Industry, and ATS categories. Four AI tools that handle the heavy writing work. AI import from an existing PDF. Instant PDF export. No sign-up required, no paywalls, no upsells, no credit card. Forever.',
    '75% of resumes never reach a human reviewer — they\'re filtered by Applicant Tracking Systems (ATS) before any recruiter sees them. The platform\'s templates are designed with industry-standard semantic structures that ATS parsers handle correctly, which materially improves the share of resumes that survive the filter.',
    'Four AI tools cover the writing work: an AI Summary Generator (drafts the professional summary from your experience, skills, and education), Smart Skill Suggestions (recommends ATS-keyword-coverage-maximising skills based on your titles and industry), an ATS Score Checker (0–100 score with actionable per-section tips), and a Job Description Matcher (paste a JD, see which keywords you\'re missing).',
    'AI Import lets you upload your existing PDF resume; the platform extracts and structures the data into the editor automatically. No starting from a blank page. Migration from a competing resume builder is one PDF upload.',
    'Powered by NetworkersHome as Gold Sponsor — the parent group\'s investment is what funds the no-paywall posture. The platform exists structurally because the team has decided that resume tooling should not have a paywall in front of it; the structural backing is what makes the commitment credible rather than aspirational.',
    'Built and operated by Ollasoftware. The product is the consumer-facing entry point of the broader careers-and-skills portfolio that includes NHPrep (certification exam prep) and the Networkers Home training operation.',
  ],
  sections: [
    {
      h2: 'The setup: 75% of resumes never reach a human',
      paragraphs: [
        'There is a piece of operational reality about modern hiring that almost every job seeker has had to learn through the painful path of unanswered applications. The reality is that the resume the candidate spent a week perfecting, optimising, and tailoring to the specific role almost certainly was not read by the recruiter — at the average mid-market and enterprise employer in 2026, roughly seventy-five percent of submitted resumes are filtered out by the Applicant Tracking System (ATS) before any human ever sees them. The candidate\'s resume failed to clear a software gate; the candidate\'s application was rejected by an automated process; the recruiter never had the opportunity to evaluate the fit.',
        'The ATS is a piece of software the employer\'s recruiting team uses to manage the inbound application volume. The system parses the submitted resume, extracts the structured data (experience, skills, education, certifications), scores the parsed data against the requirements the recruiter has configured for the role, and surfaces the highest-scoring candidates to the human reviewer. The system is designed to manage the operational load — recruiters at any meaningful employer receive far more applications than they can review by hand, and the ATS is the triage mechanism that makes the workload tractable.',
        'The candidate\'s problem is that the ATS is not the same kind of reader as a human. A human reviewer can interpret a resume with non-standard formatting, can read between the lines of a description, can recognise the relevance of a candidate\'s experience even when the keywords don\'t exactly match. The ATS is a parser; the parser handles structured data well and handles unstructured data poorly. A resume with creative formatting, with skill mentions buried in prose rather than surfaced in a structured skills section, with experience descriptions that are accurate but don\'t contain the role\'s configured keywords — that resume gets parsed badly, scored low, and filtered out before the human reviewer is even given the option to evaluate it.',
        'The candidate\'s response has historically been either to spend time learning ATS optimisation principles themselves (slow, error-prone, dependent on hard-to-find guidance) or to pay for one of the established commercial resume-building tools that promise ATS optimisation as a paid feature. The commercial tools — Resume.io, Zety, Novoresume, and dozens of others — typically range from $5 to $25 per month, often with the ATS-optimisation features behind the paywall, often with the export-as-PDF behind the paywall, often with the entire-feature-surface behind a "free trial" that converts to a paid subscription the moment the candidate finishes their first resume.',
        'On major job boards like <a href="https://www.linkedin.com/jobs/" rel="noopener noreferrer">LinkedIn Jobs</a>, the majority of mid-market and enterprise roles route applications through an ATS before any recruiter reviews the file — making ATS-parsable formatting a prerequisite rather than an advantage. The candidate is paying the established tools for a service the candidate cannot afford to skip and cannot afford to pay for — the structurally-unfair commercial outcome of an asymmetry between what the job seeker needs and what the job seeker is in a position to pay. <a href="https://freefreecv.com/">FreeFreeCV</a> exists because the founders watched their own students at Networkers Home and a growing crowd of early-career and unemployed candidates run into this commercial-tool wall and concluded that the right move was to ship the resume builder as a free public good. The bet was simple: the resume tooling that job seekers need should not be the line item the job seeker has to budget for.',
      ],
    },
    {
      h2: 'What FreeFreeCV actually is, in one paragraph and then in detail',
      paragraphs: [
        'FreeFreeCV is a cloud-operated AI resume builder that runs as a managed SaaS by Ollasoftware. The mental model is closest to Resume.io or Zety — a web app where the candidate picks a template, fills in their experience, and exports a polished PDF resume — with two structural differences: no sign-up is required to use the tool, and the entire feature surface (including the AI assistance, the ATS scoring, the template library, and the PDF export) is free forever rather than locked behind a paywall or a trial countdown.',
        'Inside the product there are four composable surfaces. The template library is the design primitive. Thirty-three recruiter-approved templates across five categories — Modern, Professional, Creative, Industry-specific, and ATS-optimised — cover the working set of resume shapes the candidate needs across the early-career, mid-career, and executive-tier hiring contexts. Each template is designed with the semantic structures ATS parsers handle well; the candidate doesn\'t have to verify that the template is ATS-friendly because all of them are.',
        'The editor surface is the building primitive. The candidate fills in their experience, skills, education, and projects through the structured form fields the editor exposes. The conventional sections (Professional Experience, Education, Skills, Projects, Certifications, Languages) are pre-defined; the candidate can add or remove sections to match their use case. The AI tools sit inline with the editor — the candidate can ask for help on any section without leaving the editing surface.',
        'The AI surface ships four tools. The AI Summary Generator drafts the professional summary from the candidate\'s filled-in experience, skills, and education. Smart Skill Suggestions recommends ATS-keyword-coverage-maximising skills based on the candidate\'s job titles and industry. The ATS Score Checker scores the resume 0–100 with specific actionable tips per section. The Job Description Matcher takes a pasted job posting and surfaces the keywords the candidate is missing. The four tools cover the dominant pain points the candidate experiences when authoring a resume from scratch.',
        'The export surface is the final primitive. Once the candidate has completed the resume, they export to PDF in seconds. The PDF preserves the template\'s typography and layout and produces the high-fidelity output ATS parsers and human reviewers both expect. The export is free; there is no watermark, no upgrade prompt, no "your free version includes our logo" surprise. The candidate gets the same PDF a paying customer of a competing tool would get.',
      ],
    },
    {
      h2: 'No sign-up required — the structural commitment',
      paragraphs: [
        'The most distinguishing operational property of the platform — the property the brand site leads with — is that no sign-up is required. The candidate can navigate to the site, pick a template, build a resume, and export a PDF without ever creating an account. There is no email gate, no password creation, no email-verification step, no "create a free account to continue" interruption between the candidate\'s intent and the candidate\'s exported resume.',
        'The decision is deliberate and is the structural answer to the commercial pattern that dominates the competing resume-builder category. The standard pattern in the category is to make the early experience friction-free (the candidate fills in their data, sees a polished preview, feels invested in the output) and then introduce the paywall at the moment of export — "your resume is ready, sign up to download." The pattern works commercially because the candidate at that moment has spent thirty to ninety minutes building the resume and is heavily motivated to complete the export. The candidate pays the subscription because the alternative is to discard the work.',
        'The platform\'s position is that this pattern is the wrong shape of trade. The candidate should be able to evaluate the output before the commercial commitment, not after. The candidate should be able to export the PDF without an account, take it home, decide if it\'s the resume they wanted, and come back next month for the next iteration without re-signing-up. The no-sign-up posture is what makes this evaluation flow honest rather than a trap-and-charge funnel.',
        'For candidates who want to save their work across sessions — to come back next week to update the resume for a new role, to maintain multiple variants for different job applications, to share the resume with a mentor for feedback — the platform offers optional account creation. The account adds the cloud-storage and edit-history features that the no-sign-up path doesn\'t have; the no-sign-up path is for the one-off use case, the account path is for the ongoing use case. Both paths are free.',
        'The structural backing for the no-paywall commitment is the Gold Sponsor relationship with Networkers Home — the parent training operation that funds the platform\'s operating costs rather than the platform having to monetise through subscriptions. The brand site is explicit about this; the sponsor relationship is what makes the "free forever" claim credible rather than a marketing line that may quietly become a paywall in twelve months. The candidate using the platform today is using a product whose business model does not depend on their payment.',
      ],
      pullQuote: 'No sign-up. No paywall at export. No watermark. No "create a free account to continue." The candidate gets the same PDF a paying customer of a competing tool would get.',
    },
    {
      h2: 'The 33 templates and the ATS-optimisation discipline',
      paragraphs: [
        'The template library is the design primitive the candidate interacts with most directly. Thirty-three templates, organised into five categories, cover the working set of resume shapes the candidate needs across the early-career, mid-career, and executive tiers.',
        'The Modern category covers the contemporary visual treatments that work well for tech roles, creative industries, and roles where the candidate wants to signal currentness. Sample templates: Modern Minimal, Creative Designer, Sleek Modern, Sleek Professional, Modern Prime, Photo Card, Two-Tone, Timeline, Skills First, Sidebar Pro, Gradient Sidebar, Infographic, Startup Modern. Each Modern template balances visual interest against ATS-parsability — the design treatments stay within the semantic-HTML structures ATS parsers handle correctly, so the visual modernity doesn\'t cost the candidate the ATS gate.',
        'The Professional category covers the traditional-corporate visual treatments that work well for finance, legal, consulting, healthcare, and the conventional white-collar industries. Sample templates: Management Professional, Corporate Standard, Traditional, Executive, Premium Elite, Sleek Professional, Scholar, Elite Executive, Monogram, Finance, Healthcare, Legal. These templates are conservative on visual treatment and high on ATS-friendliness — appropriate for industries where the resume\'s visual signal should communicate seriousness rather than creativity.',
        'The Creative category covers the visually-distinctive treatments for industries where the resume itself is a design signal — graphic design, UX, marketing, advertising, and adjacent fields. Sample templates: Creative Designer, Premium Elite, Infographic. The Creative templates push further on visual interest than the Modern templates and accept a small reduction in ATS-parsability in exchange for the design signal the relevant industries reward.',
        'The Industry-specific templates cover the verticals where the resume conventions are vertical-specific — Finance, Healthcare, Legal, Developer Pro, Competency Focus, Strong Content, Scholar. The conventions for a finance resume differ from the conventions for a healthcare resume; the Industry templates encode the right conventions for the candidate\'s field rather than treating all roles as identical.',
        'The ATS category contains the templates designed explicitly for maximum ATS-parsability when the candidate\'s primary concern is making it past the ATS filter. Sample templates: ATS Use Free, High-Density ATS, Essential ATS, ATS Plus. These templates strip the visual treatment to the minimum and prioritise the semantic structure ATS parsers prefer. The trade-off is a less visually-distinctive resume; the benefit is the highest ATS-parse-success rate the platform produces. For candidates whose primary fear is the ATS gate, these templates are the right starting point.',
        'Across all five categories, the underlying discipline is that the semantic HTML structure under every template uses the standard sections, the standard heading hierarchy, and the standard content-block shapes ATS parsers expect. The visual treatment varies; the structural foundation does not.',
      ],
    },
    {
      h2: 'The four AI tools that do the heavy lifting',
      paragraphs: [
        'The AI surface ships four tools today, each addressing a specific pain point candidates encounter when authoring a resume from scratch.',
        'The AI Summary Generator handles the most common writer\'s-block point: the professional summary at the top of the resume. The candidate fills in their experience, skills, and education; the AI reads the structured data and produces a polished two-to-four-sentence summary that captures the candidate\'s positioning. The summary is edited by the candidate before final submission; the AI provides the first draft, the candidate refines for tone and emphasis. For early-career candidates who haven\'t written a professional summary before and don\'t know how the genre works, this tool is often the most-valuable single feature on the platform.',
        'Smart Skill Suggestions handles the keyword-coverage problem the ATS filter punishes most aggressively. The candidate\'s skills section needs to contain the keywords the ATS is scoring against; the candidate often doesn\'t know which keywords matter for their role and industry. The AI reads the candidate\'s job titles and industry, recommends the skills that maximise ATS-keyword coverage for the relevant role-industry combination, and surfaces them for the candidate to add or modify. The recommendation is data-driven (skills that appear frequently in job postings for the candidate\'s role-and-industry combination) rather than generic, which is why the recommendations are actually useful rather than just thematic.',
        'The ATS Score Checker is the diagnostic surface. The candidate runs the score against their current draft and gets a 0–100 number plus a section-by-section breakdown of what is hurting the score and what would improve it. The actionable tips are specific ("the Skills section is missing the keyword X, which appears in similar job postings", "the Experience section has bullet points that are too long for ATS parse quality", "the contact information section is missing a phone number") rather than generic, so the candidate has concrete fixes to apply rather than vague directional guidance.',
        'The Job Description Matcher is the per-application optimisation surface. The candidate has built a base resume; they want to tailor it for a specific job posting they\'re about to apply to. The candidate pastes the JD into the matcher; the platform analyses the JD and surfaces the keywords the candidate\'s current resume is missing relative to that specific posting. The candidate adds the missing keywords (in whichever sections they belong — Skills, Experience descriptions, Summary), and the resume\'s match-rate against that specific JD improves measurably. This tool is the one that converts the "send the same resume to every application" pattern into the "tailor for each application" pattern that materially improves the candidate\'s interview-call rate.',
        'Beyond the four tools, the platform ships AI Import — the candidate uploads their existing PDF resume, and the AI extracts and structures the data into the editor. For candidates migrating from a competing resume builder or from a manual Word-document workflow, the import is the migration path that doesn\'t require retyping every section.',
      ],
    },
    {
      h2: 'How the workflow actually plays out',
      paragraphs: [
        'The end-to-end workflow on the platform is intentionally short. For most candidates, the experience from landing on the site to exporting the first PDF takes between twenty and forty minutes — comparable to or faster than the equivalent workflow on a paid commercial competitor.',
        'The first three minutes are template selection. The candidate browses the thirty-three templates, filters by category (Modern, Professional, Creative, Industry, ATS), and picks one. The platform\'s recommendation surface suggests templates based on the candidate\'s implicit signal (which categories they\'ve clicked, which industries they\'ve looked at). For candidates who already have a resume and want to migrate, the AI Import path skips the manual template-selection step — upload the PDF, the platform structures the data into the chosen template automatically.',
        'The next fifteen to twenty-five minutes are content authoring. The candidate works through the editor\'s structured sections — Personal Info, Professional Summary, Experience, Education, Skills, Projects, Certifications. The AI tools sit inline; the candidate can invoke them on any section without breaking flow. The conventional pain points (writer\'s block on the summary, uncertainty about which skills to include, anxiety about ATS scoring) are addressed by the AI tools at the moment the candidate hits them rather than after the resume is complete.',
        'The next five minutes are review and optimisation. The candidate runs the ATS Score Checker against the complete draft, reviews the per-section tips, applies the fixes the platform recommends, re-runs the score, and iterates until the score reaches the candidate\'s target. For candidates targeting a specific job posting, the Job Description Matcher pass adds the per-application keyword optimisation; the candidate adjusts the resume to maximise the match-rate against the specific JD.',
        'The final minute is export. The candidate clicks Export, picks the file name, downloads the PDF. No sign-up gate, no paywall, no watermark, no upgrade prompt. The PDF is the same PDF a paying customer of a competing tool would get; the file format is the conventional PDF the candidate uploads to the employer\'s application system.',
        'For candidates who maintain multiple variants for different applications — the conventional pattern for any candidate applying to more than a couple of roles — the platform\'s account-creation path lets the candidate save the resume to the cloud, duplicate it for variant authoring, and maintain a versioned history of past applications. The account is free; the workflow is the same as the no-sign-up workflow with the addition of cross-session persistence.',
      ],
    },
    {
      h2: 'How FreeFreeCV compares to the alternatives',
      paragraphs: [
        'The resume-builder category has many vendors and it is worth being direct about how the platform sits against the names most candidates evaluate alongside it.',
        'Resume.io is the largest commercial resume builder by deployed user base. Resume.io is competently built, has a large template library, and ships AI assistance in some tiers. Resume.io\'s structural property is the commercial model — the paywall at export, the subscription that converts after the trial. The platform\'s extension over Resume.io is the absence of the paywall; for candidates whose primary concern is the cost of the tool, <a href="https://freefreecv.com/">the platform</a> is the differentiated alternative.',
        'Zety is the closer peer on the AI-assisted-builder dimension. Zety has a polished editor, a strong AI surface, and a comparable template library. Zety\'s structural property is the same paywall-at-export pattern; the platform is the free alternative.',
        'Novoresume, Kickresume, Enhancv, Canva\'s resume tool, and the broader category of mid-market resume builders all share the same commercial model. The platform\'s competitive position against the whole category is structurally simple — it is the alternative that does not charge.',
        'Google Docs templates and Microsoft Word templates are the lowest-friction free alternatives. They are well-known, every candidate has access to them, and they work for the candidate who is happy to author the resume manually without AI assistance. The platform extends past them on the AI tooling, the ATS scoring, the template library specifically designed for ATS-parsability, and the no-blank-page pattern that AI Import enables.',
        'For early-career candidates and candidates in financial constraints — the audience the platform was built for explicitly — the no-paywall posture is the line item that matters most. The candidate who can afford the $20/month commercial tool can choose between the competing options on feature parity; the candidate who cannot afford the $20/month tool has historically had no AI-assisted option at all. The platform is the option for that candidate.',
      ],
    },
    {
      h2: 'The team and the sponsor relationship',
      paragraphs: [
        'FreeFreeCV is built and operated by <a href="https://ollasoftware.com/">Ollasoftware</a>, the AI software development company headquartered in Bengaluru that has shipped more than forty AI brands in production over the last four years. The platform is part of the team\'s broader careers-and-skills portfolio that connects to the parent group\'s training-and-placement operation.',
        'The Gold Sponsor relationship with <a href="https://www.networkershome.com/" rel="noopener">Networkers Home</a> is the structural backing that funds the no-paywall posture. Networkers Home is the cybersecurity and networking training institute that has placed more than forty-five thousand alumni across eight hundred hiring partners since 2007. The relationship is explicit on the brand site as the Gold Sponsor designation; the operational meaning is that the platform\'s costs are subsidised by the parent group rather than the platform having to monetise through subscriptions.',
        'The reasoning behind the sponsor relationship is straightforward. The parent group\'s business is training and placing job seekers; the parent group\'s alumni are the same population the platform\'s tool is built for. Funding a free resume builder for the candidate audience is structurally aligned with the parent group\'s placement mission — the candidates the parent group has trained and is placing get a free tool that improves their interview-call rate, and the candidates the broader market has not yet found get access to the same tool. The unit economics work because the alternative — the parent group paying for commercial resume tools on behalf of its students, or the students paying out of pocket — is structurally worse for both sides.',
        'The team behind the platform comes from the broader Ollasoftware engineering portfolio. The AI tooling shares infrastructure with the LLM-routing surfaces that ship as Ollima and Switchllm; the editor and the rendering pipeline share the operational substrate (Postgres, Caddy, the conventional shape) of the broader portfolio. The shared infrastructure is part of why the platform can ship the breadth of capability without a separate engineering organisation for the consumer-facing product. For candidates looking to pair the resume tool with structured certification-based upskilling, the portfolio\'s training brands — <a href="https://ollasoftware.com/blog/networkershome/">Networkers Home</a> (in-person networking and cybersecurity certification, 45,000+ alumni) and <a href="https://ollasoftware.com/blog/nhprep/">NHPrep</a> (cloud certification platform at ₹7,999/year) — cover the skills side of the job-readiness equation.',
      ],
    },
    {
      h2: 'What is on the roadmap',
      paragraphs: [
        'The team publishes the roadmap on the brand site and updates it as work ships. The visible near-term threads are concrete: an expanded template library beyond the current thirty-three (the next wave focuses on the industry-specific shapes customer feedback has surfaced — biotech, fintech, deep-tech, and the regulated-vertical patterns), a cover-letter builder that pairs with the resume tool through the same AI surface, and a multilingual content surface for candidates whose target market is non-English-speaking.',
        'Underneath those visible features is steady investment in the ATS-optimisation discipline. The current ATS Score Checker handles the canonical scoring patterns competently; the roadmap extends to the specific scoring patterns of the major ATS vendors (Workday, Greenhouse, Lever, the rest of the working set) so the score the candidate sees is calibrated against the specific ATS the target employer uses rather than against a generic average. For candidates targeting specific employers, this per-vendor calibration is the kind of detail that moves the resume from "this passes" to "this scores in the top quartile."',
        'On the AI side, the team is investing in the conversational coaching surface that goes beyond the four tool-shaped surfaces today. The candidate who wants to ask "is my resume strong enough for this senior role" or "what should I emphasise more given my background" should be able to have the conversation with the AI directly rather than running tool invocations. The coaching surface is on the near roadmap and will extend the platform\'s value from a builder into a more comprehensive career-tooling product.',
        'Pricing during the current phase is the structural commitment of free forever. The team has been explicit that there is no paid tier on the roadmap; the platform\'s funding model is the Gold Sponsor relationship rather than the conventional subscription. The commitment may be revisited if the platform\'s scale outgrows what the sponsorship can support, but the team\'s posture is that any change would be announced in advance with rationale rather than introduced through a stealth paywall.',
      ],
    },
    {
      h2: 'How to start',
      paragraphs: [
        'If you are applying for jobs and your current resume tooling is either a Word document you wrote in 2022 or a commercial resume builder that charges to export the PDF, the right next move takes about three minutes to verify and twenty to forty minutes to use. Go to <a href="https://freefreecv.com/">freefreecv.com</a> (no sign-up required), pick a template from the thirty-three options, and start building. If you already have a resume, the AI Import path lets you upload your existing PDF and structure it into the editor automatically.',
        'For the first authoring pass, work through the editor\'s structured sections from top to bottom. Use the AI Summary Generator when you reach the Professional Summary section; use Smart Skill Suggestions when you reach the Skills section; let the editor\'s structure guide you through the conventional resume sections. For each section, the inline help explains what ATS parsers expect and what reviewers respond to.',
        'For the optimisation pass, run the ATS Score Checker against the complete draft and apply the per-section tips the platform surfaces. Iterate until the score reaches the threshold you\'re comfortable with — most candidates aim for 85 or higher; a score of 90+ is achievable on most templates with thorough authoring.',
        'For the per-application pass, run the Job Description Matcher against each specific job posting before applying. The matcher surfaces the keywords your resume is missing relative to that posting; you adjust the resume (or save a variant of the resume for that posting) and submit the optimised version. This per-application tailoring is the line item that materially improves your interview-call rate against any specific role.',
        'For ongoing use — saving multiple variants, returning across weeks of applications, sharing the resume with a mentor for feedback — create an account. The account is free; the workflow is the same as the no-sign-up flow with the addition of cross-session persistence.',
        'If you would like the team to provide direct feedback on a specific resume or to walk you through the workflow for a specific target role — particularly for candidates from the Networkers Home community whose target is one of the parent group\'s eight-hundred-plus hiring partner companies — the <a href="https://ollasoftware.com/contact/">Ollasoftware contact page</a> reaches the team directly.',
      ],
    },
  ],
  faqs: [
    {
      q: 'What is FreeFreeCV?',
      a: 'FreeFreeCV is a free AI resume builder. 33 ATS-friendly templates, 4 AI tools (summary generator, smart skills, ATS scoring, job-description matcher), AI import from your existing PDF, instant PDF export. No sign-up required, no paywalls, no upsells, no credit card. Built and operated by Ollasoftware. Powered by NetworkersHome as Gold Sponsor.',
    },
    {
      q: 'Why is it free?',
      a: 'The platform is structurally funded through the Gold Sponsor relationship with Networkers Home (the parent training institute). The parent group\'s business is training and placing job seekers; funding a free resume builder for the candidate audience is structurally aligned with the parent group\'s placement mission. The platform\'s costs are subsidised; there is no paid tier on the roadmap and any future change to the pricing model would be announced in advance with rationale rather than introduced through a stealth paywall.',
    },
    {
      q: 'What does "ATS-friendly" actually mean?',
      a: '75% of resumes are filtered by Applicant Tracking Systems before a human reviewer sees them. ATS parsers handle structured data well and unstructured data poorly. The platform\'s templates use industry-standard semantic HTML structures that ATS parsers correctly identify — the standard section headings, the conventional content blocks, the parseable date and location formats. Resumes built on the templates have materially higher ATS-parse success rates than resumes with creative formatting that confuses the parsers.',
    },
    {
      q: 'What do the 4 AI tools do?',
      a: 'AI Summary Generator drafts your professional summary from your experience, skills, and education. Smart Skill Suggestions recommends ATS-keyword-coverage-maximising skills based on your titles and industry. ATS Score Checker scores your resume 0–100 with specific actionable per-section tips. Job Description Matcher takes a pasted JD and surfaces the keywords you\'re missing relative to that specific posting. Plus AI Import — upload your existing PDF, the platform structures the data into the editor automatically.',
    },
    {
      q: 'Do I need to sign up?',
      a: 'No. Pick a template, fill in your data, export the PDF. No email gate, no password, no email-verification step. For candidates who want to save work across sessions — to update the resume next week, maintain multiple variants for different applications, share with a mentor for feedback — optional account creation adds cloud storage and edit history. Both paths are free.',
    },
    {
      q: 'How does FreeFreeCV compare to Resume.io, Zety, Novoresume and Kickresume?',
      a: 'Resume.io, Zety, Novoresume, Kickresume, Enhancv all share the same commercial model — paywall at export, subscription that converts after the trial. FreeFreeCV is structurally free across the whole feature surface (templates, AI tools, ATS scoring, PDF export). For candidates whose primary concern is the cost of the tool, FreeFreeCV is the alternative that doesn\'t charge. For candidates who can afford the $5-$25/month commercial tool, the feature parity is roughly equivalent; the commercial choice is between feature polish vs free.',
    },
    {
      q: 'What are the 33 templates?',
      a: '5 categories. Modern (Modern Minimal, Creative Designer, Sleek Modern, Sleek Professional, Modern Prime, Photo Card, Two-Tone, Timeline, Skills First, Sidebar Pro, Gradient Sidebar, Infographic, Startup Modern, others). Professional (Management Professional, Corporate Standard, Traditional, Executive, Premium Elite, Scholar, Elite Executive, Monogram, Finance, Healthcare, Legal). Creative (Creative Designer, Infographic, others). Industry-specific (Developer Pro, Competency Focus, Strong Content, Scholar). ATS-optimised (ATS Use Free, High-Density ATS, Essential ATS, ATS Plus). Each template uses semantic HTML structures ATS parsers handle correctly.',
    },
    {
      q: 'Who is behind FreeFreeCV?',
      a: 'FreeFreeCV is built and operated by Ollasoftware, the Bengaluru-headquartered AI software development company. The AI tooling shares infrastructure with Ollima and Switchllm. The Gold Sponsor relationship with Networkers Home — the cybersecurity and networking training institute founded in 2007 with 45,000+ alumni placed across 800+ hiring partners — is the structural funding that supports the free-forever posture.',
    },
  ],
};
