import type { BlogPost } from './types';

// OllaSync — 5,000+ word brand piece. Grounded against live ollasync.com
// on 2026-06-28 (8-in-1 workspace: HD meetings, real-time chat with
// instant voice calls, AI assistant with catch-me-up, smart search across
// everything, recordings & transcripts, knowledge graph, teams & roles,
// developer platform; per-seat pricing Free / Pro $10 ($8 yearly) /
// Enterprise).
//
// Cloud SaaS framing throughout.

export const ollasyncPost: BlogPost = {
  slug: 'ollasync',
  brand: 'OllaSync',
  brandDomain: 'ollasync.com',
  brandTagline: 'Meet, chat, and remember — in one workspace',
  category: 'saas',
  title: 'OllaSync — meet, chat and remember in one workspace (the 8-in-1 collaboration platform)',
  metaDescription: 'OllaSync is the all-in-one workspace from Ollasoftware. HD meetings with live transcription, real-time chat with one-click voice calls, an AI assistant that catches you up, smart search across every meeting and message, recordings, a knowledge graph that auto-links decisions and projects, team RBAC, and a developer platform — one login, one bill, eight tools collapsed into one.',
  heroEyebrow: 'Brand deep-dive · all-in-one workspace',
  heroH1: 'OllaSync: meet, chat and remember — in one workspace.',
  heroSub: 'A 5,000-word deep dive into OllaSync — the cloud-operated all-in-one workspace from Ollasoftware. HD meetings, real-time chat with instant voice calls, an AI assistant that catches you up, search across every meeting and message, recordings with transcripts, a knowledge graph that auto-links decisions, teams with RBAC, and a developer platform. Eight tools collapsed into one screen, one login, one bill.',
  publishedOn: '2026-06-28',
  lastUpdated: '2026-06-28',
  readingTimeMin: 22,
  wordCount: 5170,
  tldr: [
    'OllaSync is a cloud-operated all-in-one workspace that collapses what most teams currently buy from eight separate vendors — Zoom for meetings, Slack for chat, a voice tool for calls, a copilot for AI assistance, a search layer over everything, a recording tool, a knowledge wiki, and a developer-platform layer — into one product with one login and one bill.',
    'HD video and audio with live transcription, recordings, polls, screen share, and virtual backgrounds. Channels, DMs, presence, reactions, file sharing, plus one-click voice calls that stay inside the conversation rather than spinning up a parallel meeting room.',
    'AI Assistant is the differentiator. "Catch me up" summarises any channel or meeting in seconds. AI compose drafts the message while you stay in flow. The workspace copilot answers plain-language questions drawn from every meeting, message, and file in the team\'s history.',
    'Smart Search is the second differentiator. Type the words you remember in plain English. The platform searches across every meeting, message, file, and decision at once, with auto-extracted facets, time-range filters, and saved searches that double as alerts.',
    'Knowledge Graph is the third. Decisions, people, projects, and follow-ups get automatically linked into a graph that the team can explore visually or query via the API. The graph is the substrate that makes "what did we decide about pricing last week" answerable.',
    'Pricing is per-seat and straightforward. Free for solo use and trying the platform. Pro at $10 per user per month ($8 yearly). Enterprise contracts for SSO, advanced RBAC, audit-log streaming, and SLA. Built by Ollasoftware.',
  ],
  sections: [
    {
      h2: 'The setup: eight tools, eight subscriptions, eight tabs',
      paragraphs: [
        'Every team that has matured past the founding-team stage runs roughly the same collaboration stack, accreted over the course of two or three years through a sequence of point decisions that each made sense at the time. Zoom for meetings because the team needed video that worked reliably and Zoom was the default answer. Slack for chat because the team grew past the point where everything could happen in one shared room. A voice-call tool — Dialpad, Aircall, Twilio, whichever — for the phone-shaped conversations that did not warrant a full video meeting. Google Meet or another video tool for the meetings that crossed organisational boundaries and needed a different surface. A notes-and-recordings tool — Otter, Fathom, Tactiq, whichever — for the meeting-summary workflow. A wiki — Notion, Confluence, whichever — for the team\'s persistent knowledge. A search layer — Glean, Coveo, whichever — for the "we wrote this down somewhere" problem. And eventually some kind of internal-AI assistant that ties some subset of them together.',
        'The cost of that stack at maturity is real and increasingly hard to defend. Eight subscriptions, eight billing relationships, eight sets of user-provisioning steps every time someone joins or leaves. Eight tabs the operating team has open by default in every browser session. Eight definitions of "where the decision was made" — the meeting, the chat thread, the document, the wiki page — that never quite agree because the team can\'t reliably remember which surface holds which artifact. The mental overhead of maintaining the stack quietly becomes a tax on the operating output of every person on the team.',
        'The operational problems compound when the team grows past a certain size. The meeting that established the pricing change happens on Zoom and is forgotten within a week because the recording lives in a tool nobody opens daily. The Slack thread where the implementation detail was hashed out gets buried under the next two thousand messages within a day. The decision document in Notion gets out of date within a quarter because nobody updates it after the next iteration ships. The team\'s collective memory is fragmented across eight surfaces, and the cost of reconstructing context — for a new hire, for a customer escalation, for an executive who wants to know "what did we decide" — scales with the fragmentation.',
        'The AI-era addition has been to bolt a copilot onto each surface individually. Zoom got an AI Companion. Slack got Slack AI. Notion got Notion AI. Otter got its own copilot. Each one is reasonable within its surface and aware of nothing outside it. The team that asks "did we decide on the Q4 pricing change yet" has to ask the question of each copilot separately and stitch the answers together by hand. The cross-surface intelligence the operating team actually needs does not exist in any single product because no single product owns enough of the surfaces.',
        '<a href="https://ollasync.com/">OllaSync</a> exists because the founders watched their own teams and a growing crowd of operator-led startups end up with this eight-vendor stack, suffer the operational tax, watch the cross-surface intelligence remain stubbornly out of reach, and decide that the right move was to ship the consolidation as the product. The bet was simple: one workspace that owns the meeting, the chat, the call, the recording, the search, the knowledge graph, and the AI tier on top of all of them.',
      ],
    },
    {
      h2: 'What OllaSync actually is, in one paragraph and then in detail',
      paragraphs: [
        'OllaSync is a cloud-operated all-in-one workspace that runs as a managed SaaS service. The mental model is "Slack plus Zoom plus a recording tool plus a wiki plus a copilot plus a search layer, on one bill, behind one login." You sign up at the dashboard, you invite your team, you create channels, you start meetings, you record what matters, you ask the AI assistant for what you need — all of it inside one app rather than across eight. There is nothing to install on the platform side; the product runs on Ollasoftware\'s own infrastructure as a hosted service.',
        'Inside the product there are eight composable surfaces that together cover the working set of operational collaboration tools the average team currently buys separately. Meetings is HD video and audio with recording, live transcription, polls, screen share, and virtual backgrounds. Chat & Calls is channels, DMs, reactions, presence, file sharing, plus one-click voice calls that stay inside the conversation rather than spinning up a parallel surface. AI Assistant is the cross-surface intelligence layer — catch-me-up summaries, a workspace copilot that answers plain-language questions, and AI compose woven through every conversation. Smart Search is plain-language search across every meeting, message, file, and decision at once. Recordings & Transcripts captures every meeting, organises into folders, supports in-app replay, and exposes the artifacts internally and externally with the right access controls. Knowledge Graph auto-links decisions, people and projects into a graph the team can explore. Teams & Roles covers the workspace identity layer with owner / admin / member / viewer roles, invites, domain auto-join, and secure offboarding. Developer Platform exposes scoped API keys, signed webhooks, and the exportable audit log.',
        'The architectural decision that distinguishes the platform most clearly is that the AI assistant has access to the data from all of the other surfaces simultaneously. Where a Zoom-only copilot can answer questions about meetings, where a Slack-only copilot can answer questions about chat, where a Notion-only copilot can answer questions about wiki pages, <a href="https://ollasync.com/">the workspace copilot</a> answers questions drawn from every meeting, every message, every file, every decision the team has produced. The "what did we decide about pricing last week" question is answerable because the platform owns enough of the surfaces to actually know.',
        'Operationally, the platform sits in a specific place in the competitive landscape. It is not trying to displace Slack for the team that has standardised on Slack and is happy with it (Slack\'s install base and product depth are real). It is not trying to displace Zoom for the very-large-enterprise meeting workload (Zoom\'s SLA and integration depth at the F500 tier are real). It is trying to be the right answer for the small-to-mid-market team that has either not yet standardised on the eight-vendor stack and would prefer one product, or has standardised on the eight-vendor stack and is paying the operational tax and would prefer to consolidate.',
      ],
    },
    {
      h2: 'The meetings layer: HD video, live transcription, recordings that stay',
      paragraphs: [
        'Meetings is the surface most teams reach for first and the one where the platform competes most directly with the established video vendors. The capability surface matches the working subset of Zoom and Google Meet — HD video with adaptive bitrate, HD audio with noise suppression, screen share with high-fidelity content sharing, virtual backgrounds with consistent edge detection, polls for the meetings that need them, breakout rooms for the workshops that need them.',
        'Live transcription runs by default on every meeting and is the foundation for the entire "catch up later" and "search this later" workflow. The transcript is real-time enough that an attendee who joins late can read what they missed in the past few minutes without playing the recording. The transcript is searchable in the platform\'s smart-search surface from the moment the meeting ends, which means a question asked three months later — "did we decide on the Q4 launch date in the November planning meeting" — returns the actual passage from the meeting with the speaker attribution and the timestamp, not just a meeting-title-level hit.',
        'Recordings save automatically when the meeting host opts in. The recording lives inside the platform alongside the transcript, with the same access controls as any other artifact in the workspace. Replay is in-app — the user does not have to download a file or navigate to a separate tool — and the player supports the standard accelerated-playback and chapter-navigation primitives the operating team expects. For external sharing, the meeting host can publish a shareable link with a configurable expiry, an optional password, and an access log that records who viewed the recording when.',
        'The screen-share surface is one of the small details that matters more than it usually does. The platform handles the high-frame-rate content sharing that demo workflows require, the lossless code-window sharing that engineering reviews require, and the multi-screen-share patterns that workshop and pair-programming sessions require. The fallback paths — when bandwidth degrades, when the sharer\'s machine is under load — degrade gracefully rather than dropping the share entirely.',
        'For the meetings that involve external participants — customers, partners, candidates — the join experience is browser-first. The external participant clicks the link, the browser handles the video and audio surface directly via WebRTC, and the participant joins without installing a desktop client. For the internal team that uses the platform daily, a desktop client offers the same surface with the conventional ergonomics of a native app.',
      ],
    },
    {
      h2: 'Chat with instant voice calls in the conversation',
      paragraphs: [
        'The chat surface covers the working subset of Slack and Microsoft Teams that operating teams actually use day-to-day. Channels for the persistent conversation surfaces (public for the team-wide threads, private for the scoped working groups, locked for the executive and HR-shaped channels). DMs for one-to-one and small-group conversations. Reactions, mentions, threads, file sharing, presence, typing indicators, all the conventional ergonomics the operating team has been trained on by the established chat vendors over the past decade.',
        'The differentiator on the chat surface is the one-click voice call. When a chat conversation needs to escalate to a voice exchange — the moment three messages in the thread are not resolving the question and a five-minute call would — the voice call happens inside the conversation rather than spinning up a parallel meeting room. The participants do not have to context-switch to a different surface. The call is recorded if the team has the policy enabled. The transcript becomes part of the thread\'s history. The conversation continues in chat after the call ends without losing context.',
        'This pattern matters more than it sounds because the cost of the context-switch — opening Zoom, sending a meeting link, waiting for everyone to join, leaving the original chat thread to handle the call surface, returning to the chat thread later to write the summary — is the single biggest operational tax on the established chat-plus-meeting-tool stack. The platform collapses the context-switch entirely. The chat is the call. The transcript is the message history. The recording is the artifact.',
        'For the voice-only calls that do not need video — the quick check-in, the customer call, the alignment exchange — the same primitive handles the surface without any of the video overhead. The call quality is matched to the conventional VoIP standards the operating team expects. The recording and transcript flow through the same pipelines as the video-meeting artifacts.',
        'For the public-facing channels that get high volume, the platform handles the standard chat-at-scale ergonomics — pinned messages, channel-level notifications, mute and DND scheduling, the conventional chat-noise-management primitives the operating team has been trained on. The cross-channel search and the AI assistant\'s catch-me-up surface mean the team does not have to read every channel in real time to stay current.',
      ],
    },
    {
      h2: 'The AI assistant: catch-me-up, workspace copilot, AI compose',
      paragraphs: [
        'The AI assistant is the layer that turns the all-in-one workspace into something materially different from the sum of its surfaces. Three primitives ship today: catch-me-up summaries, the workspace copilot, and AI compose.',
        'Catch-me-up summaries are the answer to "I have been heads-down for two hours, what happened in #launch and #engineering while I was away." The user invokes the catch-me-up surface on any channel, any meeting, or any time-range, and the assistant produces a structured summary of what was discussed, what was decided, what is pending, and what needs the user\'s attention. The summary cites the source messages and meetings inline so the user can drill in for context where the summary is not enough. For the operating team that lives in chat, this primitive alone justifies the platform for many users.',
        'The workspace copilot is the cross-surface answer to plain-language questions. "What did we decide about pricing last week" returns the actual decision, the meeting it was decided in, the people who made the decision, and the message thread where it was confirmed. "Who is the owner of the Q4 launch page" returns the assigned person, the most recent activity on the page, and the linked issues. "What is the current status of the auth migration" returns the timeline, the open blockers, and the most recent commits if the team has the engineering-integration enabled. The copilot draws from every meeting, every message, every file, every decision the team has produced — not from one surface at a time.',
        'AI compose is the third primitive and lives inside the message-writing surface. The user starts typing a message; the assistant offers to extend, refine, or rewrite based on the context of the channel and the conversation. For long-form messages — incident updates, executive briefings, customer responses — the assistant can take a one-line prompt and produce a structured draft. The user owns the final send; the assistant accelerates the writing.',
        'Underneath all three primitives is one principle: the more the team works inside the platform, the smarter the workspace gets. Memory accumulates per workspace; the assistant\'s context window for each query is the entire team\'s history, not just the immediate conversation. The compounding effect is real and shows up most clearly in long-tenured workspaces where the catch-me-up and the copilot answers are noticeably better at six months of accumulated history than they were at six weeks.',
      ],
      pullQuote: 'The "what did we decide about pricing last week" question is answerable because the platform owns enough of the surfaces to actually know.',
    },
    {
      h2: 'Smart Search: type the words you remember',
      paragraphs: [
        'The smart-search surface is the second differentiator and the one that most directly addresses the "we wrote this down somewhere" problem that fragments operating teams above a certain size. Type the words you remember in plain language; the platform searches across every meeting transcript, every chat message, every file, every decision, and every wiki page at once.',
        'The query syntax is the un-feature: there is no SPL, no proprietary DSL, no advanced-search modal the user has to learn. Plain substring works. So does `from:maya` or `in:#launch` or `before:last-week` when the user wants to narrow the search. Auto-extracted facets show up alongside the results — clickable filters for channel, author, date range, content type — that let the user drill in with one click rather than refining a query string.',
        'Live results stream as the user types, which makes the search surface useful for the "I am pretty sure I remember this" question where the exact words are uncertain. The user types one word, sees the candidate hits, refines the query based on what came back, and converges on the right artifact in seconds rather than minutes. For long-tenured workspaces, the search surface becomes the primary navigation tool — faster than browsing the channel list or opening folders.',
        'Saved searches double as alerts. A team running a launch can save the search "customer:* AND keyword:bug AND in:#support" and get notified the moment a new message matches. A sales team can save "intent:demo AND in:#leads" for the cross-surface lead routing pattern. The search surface and the notifications surface are connected at the platform level rather than as two separate features.',
        'For teams that need to export search results — for compliance review, for audit, for the "give me everything related to this customer for the legal case" workflow — the export surface produces structured artifacts (CSV, NDJSON, or a sealed PDF bundle) that can be handed to downstream tools without the team having to manually copy results out of the search UI.',
      ],
    },
    {
      h2: 'The knowledge graph: decisions, people, projects auto-linked',
      paragraphs: [
        'The knowledge graph is the third differentiator and the one that ties the surfaces together at the structural level. As the team works inside the platform, the platform automatically extracts and links the entities that show up in the operational artifacts — decisions, people, projects, follow-ups, customers, vendors, deadlines, and the relationships between them.',
        'The graph is built passively. The team does not have to maintain a wiki page that catalogues every project, every owner, every decision; the platform builds and maintains that graph as a byproduct of the team\'s normal work. A decision made in a meeting is recognised as a decision, attributed to the people who made it, linked to the project it concerns, and linked to the implementation work that follows. A follow-up assigned in chat is recognised as a follow-up, linked to its owner, and surfaces in the assignee\'s pending-work view.',
        'For the operating team, the graph becomes the substrate for several patterns the eight-vendor stack cannot reliably support. The "who owns this" question gets a structured answer drawn from the graph rather than a guess based on chat history. The "what are the dependencies of the Q4 launch" question gets a structured answer drawn from the cross-references in the graph rather than a manual reconstruction. The "what was actually decided in last Tuesday\'s meeting" question gets a structured answer rather than a transcript-scan.',
        'The graph is queryable via the developer-platform API as well as through the workspace UI. For teams that have invested in their own analytics surface or in a custom internal dashboard, the graph can feed the dashboard with the structured-decisions and assigned-work data the dashboard needs. For teams that have not, the in-app exploration surface is the canonical way to traverse the graph — by entity, by relationship, by time, by department.',
        'The graph is also the substrate for the workspace copilot\'s cross-surface answers. When the copilot answers "what did we decide about pricing last week," it draws the decision from the graph and cites the originating meeting and message as evidence; the answer is structured rather than synthesised, which is what makes the copilot trustworthy for production operational use rather than just impressive in demos.',
      ],
    },
    {
      h2: 'Teams, roles, and the operational identity layer',
      paragraphs: [
        'Workspace identity matters more than it usually does because the platform owns enough of the team\'s working surfaces that the identity layer is also the security boundary for most of the team\'s operational data. The platform ships four roles — owner, admin, member, viewer — with the conventional permissions hierarchy and the conventional management surface (invite by email, invite by domain auto-join, suspend, reactivate, transfer ownership, secure offboarding).',
        'Domain auto-join is the canonical onboarding pattern for teams above ten people. The workspace admin configures one or more allowed email domains, new sign-ups from those domains land in the workspace automatically at the configured default role, and the admin reviews the list periodically rather than approving every individual invite. For larger teams the same surface integrates with SCIM provisioning so the workspace membership stays in lockstep with the team\'s identity provider.',
        'Secure offboarding handles the failure mode the established collaboration vendors mostly handle poorly. When a team member leaves, the admin can suspend the account, archive the offboardee\'s direct messages, redirect inbound mentions to a delegated owner, and rotate any API tokens the offboardee created. The audit log records the offboarding sequence; the workspace membership is updated in one action rather than across eight vendor surfaces.',
        'For teams that operate under compliance regimes (financial services, healthcare, public sector), the role-and-permissions surface extends to fine-grained controls — channels that only admins can read, channels that only specific roles can write to, file-attachment controls that block uploads of regulated data shapes, retention policies that automatically delete content older than a configured window. The compliance surface is configurable per workspace rather than imposed by default; the team picks the controls that match its regime.',
      ],
    },
    {
      h2: 'The developer platform: scoped keys, signed webhooks, audit log',
      paragraphs: [
        'For teams that want to integrate <a href="https://ollasync.com/">the workspace</a> with the rest of their operational stack, the developer platform exposes a scoped API key surface, signed webhooks, and an exportable audit log. The scopes follow the same discipline as the rest of the Ollasoftware portfolio — narrow scopes, per-workload tokens, explicit expiry, recorded last-used timestamps.',
        'The API covers the operational surface — messages, channels, meetings, recordings, transcripts, files, the knowledge graph — and the management surface — workspace members, roles, integrations, audit log queries. The conventions are conventional: bearer-token authentication, REST endpoints under `/v1/`, JSON request and response shapes, idempotency-key headers on mutations. Teams that have written REST integrations before can integrate with the platform without learning a vendor-specific paradigm.',
        'Signed webhooks fire on the events teams typically care about — new messages in subscribed channels, meeting recordings becoming available, new entities added to the knowledge graph, role changes in the workspace. The webhook contract uses HMAC-SHA256 signatures and idempotency keys, and the delivery layer retries with exponential backoff on customer-side failure. For teams that prefer pull-based integration, the same events are queryable through the API.',
        'The audit log is the canonical record of every mutation across the workspace and is queryable through the API for compliance and observability use cases. Export to NDJSON or CSV for archival. Stream to a SIEM via the structured-events surface for teams that need the audit data in their security infrastructure rather than in the workspace UI.',
        'For teams that want to build inside the workspace — slash commands, message actions, custom UI panels — the platform exposes a hosted-app surface where the team can register custom interactive surfaces that get rendered inside the workspace UI. The model is intentionally similar to the established collaboration platforms\' app surfaces so teams with existing Slack apps or Microsoft Teams apps can port their experience without rebuilding from scratch.',
      ],
    },
    {
      h2: 'Pricing: free to start, $10 per seat for the Pro tier',
      paragraphs: [
        'Pricing is per-seat and intentionally straightforward. The Free tier is $0 forever for solo use and for trying the platform. Workspaces on the free tier get the full feature surface but with bounded retention, bounded recording storage, and bounded AI-assistant credits per month. The free tier is genuinely usable for solo developers, small founder teams, and the evaluation period that precedes any real procurement decision.',
        'The Pro tier is $10 per user per month, or $8 per user per month billed annually. Pro unlocks unlimited retention, unlimited recording storage (within reasonable use), the full AI-assistant capacity, the full developer-platform surface, and the full role-and-permissions controls. The Pro tier is the default for teams above the free-tier limits; the unit economics are comparable to or better than running the equivalent Slack + Zoom + recording + wiki stack the team would otherwise pay for.',
        'The Enterprise tier moves to a custom contract with SCIM, SAML SSO, fine-grained RBAC, audit-log streaming to a SIEM, dedicated-tenant regional deployment, advanced compliance controls, and a contractual SLA. The Enterprise tier is the right answer for larger organisations whose procurement gate is the standard enterprise-grade vendor profile; the team negotiates the terms directly with the customer rather than publishing rates that would be wrong for most enterprise shapes.',
        'Across all three tiers, the principle the team has been deliberate about is "every feature on every plan, capacity scales with the tier." There is no "intelligence tier" that gates the AI assistant behind a higher SKU. There is no Pro-only knowledge graph. The free tier and the enterprise tier get the same capability surface; what changes is the capacity allowance and the operational controls (SSO, RBAC, SLA) that enterprises require. The principle is consistent with the rest of the Ollasoftware portfolio.',
      ],
    },
    {
      h2: 'How OllaSync compares to the established alternatives',
      paragraphs: [
        'The collaboration category has a lot of vendors and it is worth being direct about how the platform sits against each.',
        'Slack is the dominant chat-first vendor and the right choice for the team that has standardised on Slack and is happy with its depth, its ecosystem, and its app catalogue. <a href="https://ollasync.com/">OllaSync</a> displaces Slack for the teams that haven\'t yet standardised, that have outgrown Slack\'s pricing, or that want the consolidation across meetings + chat + recordings + AI + search rather than Slack-plus-six-other-vendors. For teams in transition between the eight-vendor stack and a consolidated platform, the platform is the path of least resistance.',
        'Microsoft Teams is the bundled-with-Microsoft-365 alternative and the right choice for organisations whose procurement is already standardised on Microsoft. The platform\'s extension over Teams is operational simplicity and surface coherence — the AI assistant and the smart search work across all surfaces simultaneously, rather than within the silos Teams\' architecture imposes. For organisations outside the Microsoft procurement gravity, the platform is the alternative that competes directly.',
        'Zoom is the meetings-only specialist and is the right answer for organisations whose primary workload is the meeting surface and who run the rest of the stack from other vendors. The platform\'s extension is everything around the meeting — the chat that the meeting started in, the recording the meeting produced, the transcript the meeting generated, the decisions the meeting made — flowing into the same workspace where the rest of the team\'s work happens.',
        'Notion, Confluence, and the wiki-shaped vendors are the persistent-knowledge-management category. The platform\'s knowledge graph extends past their model by building the persistent knowledge passively as a byproduct of the team\'s normal work, rather than requiring the team to actively author wiki pages. For teams that have invested heavily in their existing wiki, the platform integrates with it rather than displacing it; for teams that have always struggled to keep a wiki current, the graph is the alternative that doesn\'t require the curation discipline.',
        'Glean, Coveo, and the enterprise-search-over-everything vendors are the closest peers on the search-and-AI-assistant axis. The platform\'s differentiator is that it owns the surfaces being searched rather than indexing them from outside, which means the latency, the depth, and the cross-surface intelligence are all materially better than what an indexer-from-outside can produce. For teams that have already standardised on the eight-vendor stack and want the unified search layer on top, Glean and Coveo are the right answer; for teams choosing the unified workspace itself, the platform is the integrated alternative.',
        'Across all of these, the question is rarely "is the platform cheapest for the slice I am buying." It is "for the operational stack my team is actually running, what is the total cost of ownership — including the operational tax of running eight vendors in parallel and the operational benefit of cross-surface intelligence — compared to a single workspace that handles the full surface." For most teams in the series-A-to-mid-market range, the answer points clearly at the platform.',
      ],
    },
    {
      h2: 'The team behind the workspace',
      paragraphs: [
        'OllaSync is built and operated by <a href="https://ollasoftware.com/">Ollasoftware</a>, the AI software development company headquartered in Bengaluru that has shipped more than forty AI brands in production over the last four years. The team behind the platform comes from inside the operations side of Ollasoftware — the operators who had been running the parent company\'s own collaboration stack across the portfolio and who built the platform initially to consolidate that internal load into one product. The platform is, in a real sense, the workspace an operations team building for itself would have built, then chose to ship commercially when it became obvious that the same consolidation gap existed across most operating teams.',
        'The meeting and chat surfaces inherit from the parent team\'s production heritage in real-time systems — the Rust engineering group that operates <a href="https://ollasoftware.com/blog/24observe/">24observe</a> and <a href="https://ollasoftware.com/blog/olladns/">OllaDNS</a> built the <a href="https://webrtc.org/" rel="noopener noreferrer">WebRTC</a> and the real-time messaging layers. The AI assistant and smart search surfaces draw from sibling AI products: <a href="https://ollasoftware.com/blog/ollagraph/">Ollagraph</a> powers the knowledge-graph construction; <a href="https://ollasoftware.com/blog/ollima/">Ollima</a>\'s multilingual model-routing powers AI compose; <a href="https://ollasoftware.com/blog/ollabear/">Ollabear</a>\'s conversation-grounding engine powers the catch-me-up summarisation. Form submissions and async agent messages are handled by <a href="https://ollasoftware.com/blog/ollastack/">Ollastack</a>.',
        'The advantage of being built inside Ollasoftware is that every primitive the workspace platform needs already exists somewhere in the portfolio; the platform composes them rather than rebuilding them. The operational maturity of the underlying infrastructure carries across, which is part of why a small team can ship the breadth the platform covers without the headcount the established collaboration vendors require.',
        'The parent group, <a href="https://www.networkershome.com/" rel="noopener">Networkers Home</a>, is the cybersecurity and networking training institute that has placed more than forty-five thousand alumni across eight hundred hiring partners since 2007. The institutional context matters because the trust primitives the platform ships — RBAC, audit logs, attribution discipline, retention policies — are anchored on the disciplinary heritage of an organisation that has been operating at meaningful scale for nearly two decades.',
      ],
    },
    {
      h2: 'What is on the roadmap',
      paragraphs: [
        'The team publishes the roadmap and the changelog at the brand site and updates them as work ships. The visible near-term threads are concrete: expanded native integrations with the established vendor surfaces teams currently run alongside the platform (Salesforce and HubSpot CRMs, Linear and Jira project trackers, Notion and Confluence as legacy wiki bridges), an expanded mobile-app surface with parity to the desktop client, and deeper voice-call ergonomics including dial-in numbers for the external participants who prefer voice over join-by-link.',
        'Underneath those visible features is steady investment in the AI assistant and the knowledge graph. The current assistant handles the canonical cross-surface queries well; the roadmap extends the assistant\'s reasoning to multi-step operational workflows ("draft me the customer renewal note that references our last QBR, the open support tickets, and the usage trajectory"). The knowledge graph extends to cover more entity types as customer requests surface new operational patterns the graph should model.',
        'On the meeting surface, the team is investing in the long-form meeting workflows — workshops, all-hands, strategic offsites — that the platform currently supports but that have room to be materially better with workflow-specific surfaces. Breakout-room handling, facilitator tooling, structured-agenda integration, and the post-meeting "decisions made and follow-ups assigned" extraction are the threads under active development.',
        'Pricing during the current phase is the published Free / Pro $10 / Enterprise tiers. The team has signalled that the per-seat price will stay competitive over time and that the free-tier capability surface will not shrink. The principle remains consistent across the Ollasoftware portfolio: a platform whose pricing only goes up loses customers as fast as it adds them.',
      ],
    },
    {
      h2: 'How to start',
      paragraphs: [
        'If you run an operating team that currently lives in the eight-vendor collaboration stack — Slack, Zoom, a voice tool, a recording tool, a wiki, a search layer, a copilot, plus the integration glue — and the operational tax of running it has crossed into the territory where consolidation looks attractive, the right next move is to evaluate the platform on a real workload. Sign up at <a href="https://ollasync.com/">ollasync.com</a>, claim the free tier, invite three or four of your team, and run one department\'s worth of conversation through the platform for a week.',
        'The Quick start takes a few minutes — sign up, invite teammates by email or by domain auto-join, create the canonical channels for your team\'s working groups, schedule the first meeting, and start a conversation. The platform behaves like the conventional collaboration tools the team is already trained on, which means there is no learning curve for the foundational surfaces. The AI assistant and the smart search are the surfaces where the platform diverges from convention; both are discoverable from the workspace UI with no setup required.',
        'For teams that want a more guided evaluation — migration support from Slack, Zoom, or Microsoft Teams; data import for historical chat or wiki content; integration setup for the team\'s existing CRM or project tracker — the <a href="https://ollasoftware.com/contact/">Ollasoftware contact page</a> reaches the team directly. Most migrations from the established platforms are well-supported and the team has built the tooling for the common shapes.',
        'For teams that want to evaluate without speaking to anyone, the published documentation, the user guide, the API reference, and the case studies of teams that have made the consolidation are all open. The platform\'s case is most legible when measured against your team\'s specific operational stack rather than against an abstract pitch.',
      ],
    },
  ],
  faqs: [
    {
      q: 'What is OllaSync?',
      a: 'OllaSync is a cloud-operated all-in-one workspace that collapses meetings, chat, voice calls, an AI assistant, smart search, recordings, a knowledge graph, team management, and a developer platform into one product with one login and one bill. The mental model is Slack + Zoom + a recording tool + a wiki + a copilot + a search layer + a voice tool, on one platform. Built and operated by Ollasoftware.',
    },
    {
      q: 'How is OllaSync priced?',
      a: 'Free for solo use and trying the platform (full feature surface with bounded retention, storage and AI capacity). Pro at $10 per user per month, or $8 per user per month billed annually, unlocks unlimited retention, unlimited recording storage, full AI capacity, full developer-platform surface. Enterprise is a custom contract for SSO, advanced RBAC, audit-log streaming, dedicated regional deployment, and SLA.',
    },
    {
      q: 'What are the 8 tools OllaSync replaces?',
      a: 'Meetings (Zoom-class), Chat & Calls (Slack-class with one-click in-conversation voice), AI Assistant (catch-me-up summaries + workspace copilot + AI compose), Smart Search (plain-language across every meeting, message, file, decision), Recordings & Transcripts, Knowledge Graph (decisions, people, projects auto-linked), Teams & Roles (workspace identity + RBAC), Developer Platform (scoped API keys + webhooks + audit log).',
    },
    {
      q: 'How does the AI assistant differ from Slack AI or Zoom AI Companion?',
      a: 'Slack AI knows about Slack messages; Zoom AI Companion knows about Zoom meetings; Notion AI knows about Notion pages. The OllaSync workspace copilot has cross-surface access because the platform owns enough of the surfaces simultaneously — every meeting transcript, every message, every file, every decision the team has produced. The "what did we decide about pricing last week" question is answerable because the platform actually knows.',
    },
    {
      q: 'How does the knowledge graph work?',
      a: 'As the team works inside the platform, the platform automatically extracts and links entities — decisions, people, projects, follow-ups, customers, vendors, deadlines — and the relationships between them. The team does not have to maintain a wiki page; the graph is built passively from the team\'s normal work. Queryable via the developer-platform API or browsable through the workspace UI. The substrate for the workspace copilot\'s structured answers.',
    },
    {
      q: 'How does OllaSync compare to Slack, Zoom, Microsoft Teams, Notion and Glean?',
      a: 'Slack and Teams are chat-first vendors; OllaSync displaces them when consolidation matters more than ecosystem depth. Zoom is a meetings-only specialist; OllaSync extends past it with everything around the meeting flowing into the same workspace. Notion and Confluence are wiki-shaped vendors; OllaSync\'s knowledge graph builds the persistent knowledge passively rather than requiring curation discipline. Glean and Coveo are enterprise search vendors; OllaSync owns the surfaces being searched rather than indexing from outside, which gives materially better latency, depth and cross-surface intelligence.',
    },
    {
      q: 'Does OllaSync have RBAC, SSO and audit logs for enterprise compliance?',
      a: 'Yes. Free and Pro tiers ship the four standard roles (owner, admin, member, viewer) with the conventional permissions hierarchy plus the workspace audit log. Enterprise tiers add SCIM provisioning, SAML SSO, fine-grained role definitions, audit-log streaming to the customer\'s SIEM, dedicated-tenant regional deployment, retention-policy controls, and a contractual SLA.',
    },
    {
      q: 'Who is behind OllaSync?',
      a: 'OllaSync is built and operated by Ollasoftware, the Bengaluru-headquartered AI software development company. The meeting and chat surfaces are built by the Rust engineering group that also operates 24observe and OllaDNS. The AI assistant and smart search inherit from Ollagraph (knowledge-graph construction), Ollima (multilingual routing), and Ollabear (conversation grounding). The parent group is Networkers Home, the cybersecurity and networking training institute founded in 2007 with 45,000+ alumni placed across 800+ hiring partners.',
    },
  ],
};
