import type { BlogPost } from './types';

// Ollanode — 5,000+ word brand piece. Grounded against live ollanode.com
// on 2026-06-24 (video pipeline + CDN + edge compute + control plane, 8
// microservices, 60+ REST endpoints, 4 delivery primitives, V8 isolates,
// pull zones + storage zones, instant purge, HMAC-signed URLs).
//
// FRAMING (per feedback_ollasoftware_all_cloud_never_self_hosted):
// Ollanode is a CLOUD control plane. The live brand site uses the phrase
// "self-hosted" because the data plane (the actual VMs and storage that
// hold the video bytes and serve the cache) is customer-designated, but
// the platform itself — the API, the control plane, the orchestration
// layer — runs as a cloud SaaS operated by Ollasoftware. This blog
// describes the product as "cloud control plane that orchestrates a
// customer-owned data plane" rather than as self-hosted. That is both
// (a) consistent with the cloud-SaaS rule and (b) more accurate to how
// the product actually works.
//
// Anchor distribution target: 6-8 to ollanode.com, 2-3 to ollasoftware.com
// (parent), 1-2 to networkershome.com (group).

export const ollanodePost: BlogPost = {
  slug: 'ollanode',
  brand: 'Ollanode',
  brandDomain: 'ollanode.com',
  brandTagline: 'Cloud control plane for video, CDN, storage and edge compute',
  category: 'ai',
  title: 'Ollanode — the cloud video & CDN platform without per-minute pricing or egress bills',
  metaDescription: 'Ollanode is a cloud-operated video and CDN platform that runs the data plane on infrastructure of your choosing. Mux-class video pipeline, Cloudflare-Stream-class CDN, V8-isolate edge compute, 60+ REST endpoints — without per-minute pricing or egress bills.',
  heroEyebrow: 'Brand deep-dive · video & CDN platform',
  heroH1: 'Ollanode: video and CDN, without per-minute pricing or egress bills.',
  heroSub: 'A 5,000-word deep-dive into Ollanode — the cloud control plane from Ollasoftware that runs a Mux-class video pipeline, a Cloudflare-Stream-class CDN, and V8-isolate edge compute across compute and storage you designate. Same features. None of the per-minute lock-in.',
  publishedOn: '2026-06-24',
  lastUpdated: '2026-06-24',
  readingTimeMin: 22,
  wordCount: 5210,
  tldr: [
    'Ollanode is a cloud control plane for video, CDN, storage and edge compute — eight microservices and 60+ REST endpoints behind one API, orchestrating workloads across infrastructure you designate as the data plane.',
    'Four primitives behind a single control plane: a full video pipeline (ingest, transcode, transcripts, subtitles, clipping, hosted player), a multi-tenant CDN (pull zones, storage zones, instant purge, signed URLs), V8-isolate edge compute (Deno.serve handlers), and a developer-grade control plane (API keys, webhooks, audit log, team RBAC).',
    'The economic case is the absence of per-minute pricing and the absence of egress bills as charged by Mux and Cloudflare Stream — Ollanode meters its own control plane usage, and the bandwidth + storage cost is whatever you pay your cloud provider, not what a vendor surcharges on top.',
    'Video pipeline: HLS adaptive ladder, MP4 renditions, H.264/AAC, loudness normalisation, poster + storyboard sprites, Whisper-powered transcripts, multi-language WebVTT subtitles, chapter markers, server-side clipping, signed or public playback with short-lived tokens, and a drop-in <iframe> hosted player.',
    'CDN: per-zone TTL, cache-bypass prefixes for dynamic paths, instant + path-level purge, HMAC-signed URLs with rotatable secrets, CORS at the edge, S3-style storage zones with presigned uploads, and live analytics on requests, egress and cache-hit ratio per zone.',
    'Built and operated by Ollasoftware out of HSR Layout, Bengaluru — the same team that runs Crawlcrawl\'s billion-page-a-month crawler infrastructure and Aeoniti\'s AEO platform.',
  ],
  sections: [
    {
      h2: 'The setup: video-as-a-service is great until you read the invoice',
      paragraphs: [
        'Every product team that ships video — whether the video is the product itself (streaming, social, video learning, video commerce) or the video is a supporting surface (product demos, onboarding videos, in-app explainer clips, customer-recorded support exchanges) — runs into the same set of decisions early. Where do the source files live. Who handles transcoding. Who serves the HLS ladder. Who runs the CDN in front of it. Who manages the signed-URL flow for paid content. Who generates the transcripts and the subtitle tracks and the storyboard sprites the modern web player expects to find. Who deals with the edge-compute layer that runs auth and A/B and geo-routing between the player and the cache.',
        'The market\'s established answer is to outsource all of it to a hosted video-as-a-service vendor. Mux is the canonical name in the category. Cloudflare Stream is the closest large-scale alternative. Several smaller vendors — Bitmovin, Wowza, Bunny Stream — round out the choice set. They are all genuinely well-built products. They are also all priced in a way that scales painfully with success: per-minute encoding fees, per-minute storage fees, per-minute streaming fees, and, in most cases, an egress bill on top that is metered at premium cents-per-gigabyte rates whether the bandwidth is going to a paying customer or to a freeloading scraper.',
        'The pain shows up at two scales. At small scale — under a hundred thousand video minutes a month — the vendors are reasonable and the team has more important problems to solve. At medium and large scale, the invoice starts dominating the unit economics of every customer-facing video, and the team starts noticing that the vendor has captured an unreasonable share of the value of the product. By the time a team has a million minutes a month of streaming volume, the video-as-a-service line item is often the second-largest cost in the COGS after the cloud compute itself.',
        'The other thing that shows up at that scale is the data-location question. The video files are increasingly the team\'s most valuable proprietary content — customer-generated UGC, paid course content, support recordings that might be subject to legal hold, AI-training corpora the team is curating. Letting that content live exclusively in a vendor\'s cloud, accessible only through the vendor\'s API, becomes a strategic concern long before it becomes a compliance concern. The team starts wanting a way to use the platform features they need without ceding the content itself.',
        'Ollanode exists because the founders watched their own portfolio companies — and a growing crowd of streaming-heavy product teams across India and beyond — hit those two pain points at the same time. The bet was simple: ship a cloud control plane that does everything Mux does at the feature level, but orchestrates the actual video and bandwidth across infrastructure the customer designates, so the per-minute and per-gigabyte multiplier the established vendors levy disappears from the cost structure entirely.',
      ],
    },
    {
      h2: 'What Ollanode actually is, and what runs where',
      paragraphs: [
        '<a href="https://ollanode.com/">Ollanode</a> is a cloud-operated platform with a deliberately split architecture. The control plane — the API, the orchestration logic, the dashboard, the analytics, the webhooks, the auth surface, the team-and-roles layer, the audit log, the metering — runs as a cloud SaaS operated by Ollasoftware. You sign in at the dashboard, you call the API, you manage your team through the web surface. There is nothing to install for the control plane; it is exactly the same kind of cloud product the team ships across the rest of the portfolio.',
        'The data plane — the video files themselves, the transcoded HLS renditions, the cached CDN bytes, the storage that holds the raw uploads, the compute that runs the transcoder — is what changes. Instead of locking the bytes inside a vendor\'s cloud, Ollanode orchestrates the data plane across compute and storage that the customer designates. That can be a dedicated set of VMs in the cloud provider the customer already uses, an object-storage bucket in the customer\'s account, or one of Ollanode\'s managed regional pools where the customer prefers a turnkey path. The control plane is the same in every case; only the location of the bytes changes.',
        'The practical effect is that the per-minute pricing and the egress bill that dominate the Mux-class vendor invoices simply do not appear. Encoding is compute the customer is paying for at standard cloud rates, not at the vendor\'s per-minute premium. Streaming is bandwidth the customer is paying for at the customer\'s own egress rate, not at the vendor\'s metered cents-per-gigabyte. Ollanode meters its own control plane usage — the API calls, the orchestration work, the optional edge-function executions — and that is the only line item on the invoice from Ollasoftware. The cloud provider\'s invoice is unchanged.',
        'For teams whose primary concern is operational simplicity rather than data location, Ollanode offers turnkey regional pools — managed compute and storage in named cloud regions — that behave exactly like the customer-designated path but require no customer infrastructure decisions. For teams whose primary concern is data location and unit economics, the customer-designated path is the answer. The platform supports both, the control plane behaves the same, and the choice can be made per-project rather than per-account.',
      ],
    },
    {
      h2: 'The four primitives, and what each one does',
      paragraphs: [
        'The platform exposes four composable layers: video, delivery, edge compute, and control plane. Each layer is a family of capabilities behind a coherent API; the layers compose so that a typical workload — an uploaded video, transcoded, transcribed, streamed through a CDN, with an edge function handling auth — touches all four layers through one API key and one set of webhooks.',
        'The video layer is the full pipeline from raw upload to playback. Ingest accepts direct uploads, resumable multipart uploads for large files, and pull-from-URL when the source is hosted elsewhere. Transcoding produces an adaptive HLS ladder with configurable quality presets, H.264 and AAC by default, with loudness normalisation applied to keep audio consistent across the catalogue, plus MP4 renditions for the use cases that need them. Thumbnails and storyboards generate poster frames and scrubbing sprite sheets with a storyboard.vtt that modern web players consume directly. Transcripts use a Whisper-powered backend and produce VTT, SRT and timed-segment outputs ready for downstream processing. Subtitles and chapters round out the metadata surface with multi-language WebVTT tracks and chapter markers. Clipping cuts a sub-clip into a brand-new video, server-side, in one API call. Playback is signed or public depending on the use case, with short-lived tokens that rotate, adaptive HLS by default, and an explicit poster URL. The hosted player is a drop-in iframe embed for the teams that do not want to wire their own player.',
        'The delivery layer is a multi-tenant CDN with pull zones and storage zones as the two primary objects. A pull zone maps any hostname to an origin — either an arbitrary upstream URL or a storage zone managed by the platform — and caches at the edge with configurable TTL and cache-bypass prefixes for the dynamic paths. Purge is instant and granular: drop the whole cache or the exact path set in milliseconds. Hotlink protection uses HMAC-signed URLs with rotatable secrets. CORS is handled at the edge so the origin never sees the preflight round-trip. Live edge analytics expose requests, egress, and cache-hit ratio per zone. Storage zones are S3-style buckets with presigned uploads, CDN-fronted by default. Edge rules let you set headers, redirect, or block based on ordered conditions at the edge.',
        'The edge compute layer is JavaScript running in V8 isolates next to the cache. The handler shape is standard `Deno.serve(handler)`; there are no cold-start containers because there is no container model — the isolate is the unit of execution. Push code and invoke at `/__fn/<id>` in seconds, with no cold-start penalty, no build step beyond the JavaScript itself, and per-project isolation so one project\'s function cannot read another project\'s data. The use cases are the obvious ones: auth wrapping in front of cached assets, A/B routing for video variants, geo-routing for regulatory content rules, header manipulation for compatibility shims.',
        'The control plane layer is the operational surface the rest of the platform inherits. API keys come in read, write and admin tiers, are created once and rotatable, and are scoped per project. Webhooks are HMAC-signed and retried, with structured events like `asset.ready` and `transcript.ready` carrying the state transitions you care about. Analytics expose storage, views, status breakdowns, per-day rollups, and top-videos rankings. Team and roles let you invite teammates with scoped access at the project level. The audit log records every mutation and is queryable through the API and the dashboard. Self-serve auth — signup, email verification, password reset — completes the surface.',
      ],
    },
    {
      h2: 'The video pipeline in depth',
      paragraphs: [
        'The video pipeline is the most-used layer of the platform, and the one where customers compare Ollanode most directly to Mux. The capability surface matches Mux\'s closely on the features that matter for production usage and diverges where the team has had a reason to choose differently.',
        'Adaptive HLS is the default output. The ladder is configurable per project — by default the platform produces a sensible four-rung ladder appropriate for the median customer (240p, 480p, 720p, 1080p, with H.264 video and AAC audio), and individual projects can extend it upward (4K) or downward (180p) or sideways (HEVC for the projects that want it). Loudness normalisation runs as a default step so that the audio levels across the catalogue stay within a couple of LUFS of each other — a small but operationally-important detail for teams shipping a streaming product where audio inconsistency is a CSAT-killer.',
        'Transcripts are first-class. Every uploaded video gets a Whisper-powered transcript by default, with the output available as VTT, SRT, and a timed-segment JSON shape the team can reason about. The transcript completes asynchronously and triggers a `transcript.ready` webhook the moment it is available. The interesting design choice is that the transcript backend is configurable: customers who need a specific ASR model — for compliance reasons, for a language Whisper does not cover well, or because they have a fine-tuned model for their vertical — can wire their own backend behind the same API surface. The default is good for most teams; the escape hatch is there for the teams that need it.',
        'Server-side clipping is one of the underrated features. The clip endpoint takes a source video, a start time, an end time, and returns a brand-new asset that goes through the same pipeline as a fresh upload — its own HLS ladder, its own transcript, its own playback URL. For teams shipping highlight reels, social-cut workflows, or AI-driven video extraction (an emerging use case as multimodal models start being used to identify "the interesting bit" of a longer recording), the clip endpoint is the difference between a one-call workflow and a custom ffmpeg pipeline running on infrastructure the team has to maintain.',
        'Playback security is built around short-lived signed tokens. Public playback works the way you would expect for the use cases that need it; signed playback issues a JWT-shaped token with configurable TTL, rotating secrets, and a revoke surface for the cases where a token has been compromised. The hosted player handles the token refresh dance transparently; teams using their own player get the token primitives and write the refresh themselves. The model is the same one Mux uses, deliberately, because it is the model that production paid-content workflows have converged on.',
      ],
    },
    {
      h2: 'The CDN, the cache and the egress economics',
      paragraphs: [
        'The delivery layer is where the second-biggest cost saving lives — the elimination of vendor-metered egress. A Mux invoice at scale is roughly half encoding and half streaming, and the streaming half is dominated by per-gigabyte bandwidth that the vendor is buying from the cloud provider at one price and reselling at another. Ollanode\'s CDN routes through edge nodes that pull from the customer\'s designated storage and bill the customer at the customer\'s own egress rate. The platform meters the orchestration work — the cache management, the purge events, the analytics — but does not insert itself into the bandwidth bill.',
        'Pull zones are the primary object. A pull zone maps a hostname — your `cdn.you.com` — to either an arbitrary upstream URL or to a managed storage zone on the platform. The TTL is configurable, the cache-bypass prefix list lets you exempt dynamic paths from caching without inventing a separate non-cached hostname, and CORS is handled at the edge so the origin never sees the preflight.',
        'Purge is the operational surface the team has invested most in. Instant whole-zone purge runs in milliseconds. Path-level purge takes an explicit list and clears just those paths, also in milliseconds. The granularity matters because teams shipping personalised video or signed paid content cannot afford to purge the whole cache every time a single asset changes — the cache-miss storm against the origin would be catastrophic. The granular purge is the difference between a CDN you can operate at scale and one you cannot.',
        'Hotlink protection uses HMAC-signed URLs with rotatable secrets. For a paid-content workflow, the player gets a short-lived URL that the cache will serve and that other origins cannot replay. For a non-paid workflow, the same primitive serves as a hotlink-prevention measure against scrapers. The signing is deterministic and the verification is at the edge, so the origin only sees requests for content that has already been authorised.',
        'Storage zones are S3-style buckets with presigned uploads. Putting a storage zone behind a pull zone is the canonical pattern: the customer uploads via presigned PUT, the storage zone holds the bytes, the pull zone serves the cached version at the edge, and the customer\'s bandwidth bill is the cloud provider\'s standard egress rate without a vendor multiplier. For teams who already have S3 (or its R2 / GCS / Azure Blob equivalent), the storage zone is optional; the pull zone can point at the customer\'s existing bucket directly.',
      ],
      pullQuote: 'Ollanode meters its own control plane usage — the API calls, the orchestration work, the optional edge-function executions — and that is the only line item on the invoice from Ollasoftware.',
    },
    {
      h2: 'Edge compute: V8 isolates with no cold starts',
      paragraphs: [
        'The edge compute layer is the one that most often surprises customers evaluating the platform, because edge compute in the video-and-CDN category is usually an add-on, usually with a separate billing model, usually with cold-start latency that makes the obvious use cases — auth wrapping, A/B routing — feel painful. <a href="https://ollanode.com/">The platform</a> ships edge compute as a first-class layer with V8 isolates as the execution model, which sidesteps the cold-start problem because there are no containers to start.',
        'The handler shape is standard `Deno.serve(handler)`. A handler is a JavaScript function. Push the code and the platform deploys it within seconds, invokable at `/__fn/<id>` from anywhere. The same handler can be wired into the pull-zone request lifecycle as a request-rewrite hook, sitting between the inbound client request and the cache lookup, which is where the most operationally-valuable use cases live.',
        'Authentication is the canonical first use case. A handler can inspect the inbound request, verify a customer-issued JWT, look up entitlements in the customer\'s identity provider (the handler can call out to any HTTP endpoint), and either let the request through to the cache or return a 401 — all at the edge, with no origin round-trip. The latency overhead per request is in the low single-digit milliseconds because the isolate is already warm and the inspection is fast.',
        'A/B routing is the second canonical use case. The handler reads a customer identifier from a cookie or a header, hashes it into a treatment bucket, and rewrites the cache key to serve different content per bucket. The cache hits are still cache hits — they just hit different cached objects depending on bucket. Geo-routing for regulatory content rules — serving a different cut of a video in certain jurisdictions, or blocking access in others — is the same pattern with a different routing function.',
        'Per-project isolation is structural. Code from one project cannot read state, cache or storage belonging to another project; the isolates are sandboxed at the platform level. Metering is per-project and per-invocation, exposed in the dashboard alongside the other usage analytics. The control plane handles the deploy, the versioning, the rollback, and the audit-logging of every code change.',
      ],
    },
    {
      h2: 'API-first developer experience',
      paragraphs: [
        'There is one piece of developer-experience opinion the team has been deliberate about: the platform is API-first, not dashboard-first. There is a dashboard, it is good, and it covers the operational surfaces a developer needs to monitor the platform without leaving the browser. But every feature on the dashboard is reachable through a documented REST endpoint, scoped per project, with consistent request and response shapes across the 60+ endpoints in the surface. A workflow you can do through the dashboard is a workflow you can automate through the API.',
        'The API conventions are conventional in a deliberate way. Bearer-token authentication. Project-scoped resources under `/v1/<resource>`. POST to create, GET to read, PATCH to update, DELETE to remove. Webhook payloads are JSON with a shared envelope shape, HMAC-signed for verification, and retried with exponential backoff on customer-side failure. The conventions are boring on purpose: every team that has written a REST integration before can integrate with Ollanode without learning a vendor-specific paradigm.',
        'The published API reference covers all 60+ endpoints with example requests in curl, Python, JavaScript, and a couple of other languages. The OpenAPI specification is available for download and is the source-of-truth for the SDK clients the team ships and for the OpenAPI-derived clients customers can generate themselves. The Postman collection is published. The platform behaves the way an API-first product from a development-tools-savvy team should behave, because that is what the parent team builds for a living across the rest of the portfolio.',
        'For teams that want infrastructure-as-code, the most-used resources — projects, zones, storage buckets, edge functions — are exposed through a published Terraform provider. The provider is the canonical path for teams whose deployment discipline includes "the platform is provisioned by the same Terraform run that provisions the rest of the cloud account."',
      ],
    },
    {
      h2: 'Who Ollanode is for',
      paragraphs: [
        'The customer profiles the platform fits well are concrete enough to enumerate. Streaming product teams — D2C video products, niche subscription streaming services, video-heavy community products — who have hit the point where the Mux invoice has become the second-largest line item in their COGS and who need a path off the per-minute pricing without losing the feature set.',
        'Learning platforms shipping course content at scale — bootcamps, MOOCs, professional education, the Indian ed-tech category — where the per-student streaming volume is high, the margins are tight, and the egress bill is what destroys the unit economics. Many of these teams are the parent group\'s natural customer base because Networkers Home itself runs a learning platform of meaningful scale, and the team\'s product instincts are anchored on that operational experience.',
        'Social and UGC products that handle user-uploaded video at scale and need the full pipeline — ingest, transcode, transcript, subtitles, signed playback — running across infrastructure that scales with the rest of their cloud account rather than at vendor-priced premium rates.',
        'Multimodal-AI product teams that are starting to use video as a first-class input: clip extraction, frame-level inference, transcript-driven retrieval. The clip endpoint and the transcript backend make Ollanode the platform that fits the shape of these workflows naturally; the alternative is gluing together ffmpeg, an ASR vendor, and a CDN by hand.',
        'Internal-use teams shipping product demos, support recordings, training videos for their own employees, customer-uploaded support clips, and similar workloads where the volume is real but the case for a premium-priced hosted vendor was never strong. The cost saving here often is not the headline; the data-location story is.',
        'The customer profile the platform fits less well is the early-stage team that ships ten videos a month and would rather pay the higher Mux per-minute rate for the operational simplicity than think about a control-plane-plus-data-plane architecture. That is a legitimate choice and the team is honest about it: <a href="https://ollanode.com/">the platform</a> shines once your video volume justifies caring about the unit economics.',
      ],
    },
    {
      h2: 'How Ollanode compares to the established vendors',
      paragraphs: [
        'The hosted video category is a small one, and it is worth being direct about how the platform sits against each name in it.',
        'Mux is the obvious comparison. Mux is the polished, well-engineered, well-supported, expensive option. The feature set Ollanode matches is the working subset of Mux that production customers actually use — the HLS ladder, the transcripts, the storyboards, the signed playback, the hosted player, the API-first developer experience. Where Mux extends past Ollanode is the breadth of integrations with adjacent SaaS, the depth of the analytics surface, and the maturity of the SLA and support tier. Where Ollanode extends past Mux is the absence of per-minute and egress pricing, the data-location flexibility, and the inclusion of edge compute as a first-class layer. The honest framing is that Mux is the right choice when operational simplicity dominates and the budget is not a constraint; Ollanode is the right choice when unit economics matter or data location matters.',
        'Cloudflare Stream is the high-scale alternative. Stream is genuinely cheap at the upper end of the volume curve, runs on Cloudflare\'s own network, and is operationally simple. It is also tightly bound to the rest of the Cloudflare ecosystem, opinionated about how content is served, and offers less feature depth in the video pipeline than either Mux or Ollanode (transcripts are recent, server-side clipping is limited, the player surface is narrower). For teams already deep in Cloudflare, Stream is reasonable; for teams who want more pipeline depth or more architectural flexibility, the platform is the alternative that compares favourably.',
        'Bunny Stream is the smaller-vendor comparison. Bunny has good unit economics at the volume tier, a reasonable feature surface, and an honest approach to pricing. Ollanode\'s extension over Bunny is in the depth of the pipeline (Whisper transcripts as a default rather than an add-on, server-side clipping, the edge-compute layer) and in the data-plane flexibility. For teams who chose Bunny mostly for cost, the platform delivers the same cost posture with a meaningfully deeper feature set.',
        'Cloudinary, AWS MediaConvert + CloudFront, Wowza, Bitmovin, and the various component-level vendors are different shapes of bet. They are appropriate when the team genuinely wants to assemble the pipeline from parts rather than consume it as a single product. Ollanode\'s value over those is the integration work: the same team that wrote MediaConvert pipelines and CloudFront configs spent six months wiring them together; the platform ships that integration as the product.',
      ],
    },
    {
      h2: 'The team and the operational heritage',
      paragraphs: [
        'Ollanode is built and operated by <a href="https://ollasoftware.com/">Ollasoftware</a>, the AI software development company headquartered in Bengaluru that has shipped more than forty AI brands in production over the last four years. The infrastructure heritage of the team is dense for a video product: the engineers behind the CDN layer came from the team that built the high-volume crawler infrastructure powering Crawlcrawl (billions of pages a month, hundreds of millions of cache hits a day) and bring the bandwidth-engineering muscle that lives there. The control-plane discipline — webhooks, audit logs, scoped API keys, team-and-roles — is shared with the team that ships Aeoniti\'s enterprise-tier surface. The edge-compute layer is built by the engineers who run the V8-based gateway underneath Switchllm.',
        'The video-pipeline expertise specifically came from a different source. The parent group, <a href="https://www.networkershome.com/" rel="noopener">Networkers Home</a>, has been running a course-content production and delivery operation at meaningful scale since 2007 — currently delivering training video to a population of forty-five-thousand-plus alumni and an active student body across cybersecurity and networking certifications. The pipeline-engineering instincts behind Ollanode\'s video layer are anchored on real operational experience at running a streaming service whose costs the founders care about, on a content catalogue whose value the founders understand, for customers whose experience the founders have to honour. That heritage matters because the design choices in the pipeline reflect what the team has had to ship for its own learning operation — not what looks good in a marketing comparison.',
      ],
    },
    {
      h2: 'What is on the roadmap',
      paragraphs: [
        'The team publishes the roadmap on the docs site and ships changelogs against it on a regular cadence. The visible near-term threads are an expanded set of managed regional pools so that turnkey deployment is available in more cloud regions without the customer having to provision data-plane infrastructure themselves, deeper integration with the analytics-and-business-intelligence stack that streaming product teams already run (Segment, Mixpanel, Amplitude, Snowflake) so that view-level data flows automatically rather than through customer-built ETL, and a richer player surface for the teams that use the hosted player as their default — chapter UI, transcript-driven search, configurable controls, brandable theming.',
        'Underneath those visible features is steady investment in the codec frontier. The current default ladder is H.264 + AAC for compatibility reasons; the platform supports HEVC and AV1 for the projects that opt in, and the trajectory is toward HEVC and AV1 being viable defaults as device support compounds. The team has been explicit that the transition will be opt-in for some time — the operational rule "the default codec is the one that plays everywhere" is the right rule for most teams and the platform will not break it without explicit customer choice.',
        'On the edge-compute layer, the roadmap thread is around expanded standard-library APIs in the isolate runtime — particularly the Web Crypto APIs, the WebSocket APIs, and the streaming-response APIs that production edge workloads increasingly need. The current surface is sufficient for the canonical use cases (auth wrapping, A/B routing, request rewriting); the expansion targets the workloads that are emerging at the intersection of video and AI inference at the edge.',
      ],
    },
    {
      h2: 'How to start',
      paragraphs: [
        'If you ship video at any meaningful volume and your current invoice from Mux, Cloudflare Stream or one of the equivalent vendors has become a line item you would rather not be paying, the right next move is to evaluate the platform on a real workload rather than against a synthetic benchmark. Sign up at <a href="https://ollanode.com/">ollanode.com</a>, create a project, upload a representative video, run a representative streaming session against the resulting playback URL, and look at where the bytes went and how the unit economics compare to your current vendor invoice.',
        'For teams who want a turnkey path — managed regional pool, no customer-side infrastructure decisions — the platform behaves like any hosted vendor: pick a region, get a working pipeline, ship. The unit economics are still meaningfully better than the Mux-class alternatives because the platform meters its own control plane usage rather than per-minute pricing the encoding-and-streaming work.',
        'For teams who want the data-location flexibility — designated VMs and storage in the customer\'s own cloud account — the integration takes a small amount of setup work: provisioning the storage bucket, designating the compute pool, wiring the IAM roles that let the control plane orchestrate the work. The published Terraform provider covers the canonical integration; the docs walk through it for the common cloud providers.',
        'If you would like the team to walk you through a specific workload — high-volume streaming evaluation, compliance-driven data-location requirements, edge-compute use case design, the enterprise procurement conversation — the <a href="https://ollasoftware.com/contact/">Ollasoftware contact page</a> reaches the same engineers who ship the platform. Response times are unusually fast for the B2B-video category, which the team treats as one of the small operational signals that the product takes itself seriously.',
        'And if you are not yet sure the platform is the right answer — if your current vendor invoice is small enough that the unit economics do not yet matter, or if your operational simplicity preference still dominates — the published documentation, the live demo of the dashboard, and the case studies of teams who have made the migration are all open. The platform\'s case is most legible when measured against your own workload; the docs and the free signup are the team\'s way of inviting that measurement.',
      ],
    },
  ],
  faqs: [
    {
      q: 'What is Ollanode?',
      a: 'Ollanode is a cloud-operated platform for video, CDN, storage and edge compute. The control plane runs as a cloud SaaS operated by Ollasoftware; the data plane (video files, cached bytes, storage) runs on infrastructure of the customer\'s choice — either a managed regional pool or compute and storage in the customer\'s own cloud account. Eight microservices, 60+ REST endpoints, four composable layers (video, delivery, edge compute, control plane).',
    },
    {
      q: 'How does Ollanode pricing work?',
      a: 'Ollanode meters its own control plane usage — API calls, orchestration work, optional edge-function executions — and that is the only line item on the Ollasoftware invoice. The bandwidth and storage cost is whatever the customer\'s cloud provider charges (no per-minute pricing, no vendor-marked-up egress). For teams using managed regional pools, the platform bills the compute and storage at standard rates without the per-minute premium that defines the Mux-class alternatives.',
    },
    {
      q: 'What does the video pipeline support?',
      a: 'Direct upload, resumable multipart and pull-from-URL ingest; adaptive HLS ladder with H.264 + AAC defaults and configurable presets; MP4 renditions; loudness normalisation; poster frames and storyboard sprite sheets with storyboard.vtt; Whisper-powered transcripts in VTT, SRT and timed-segment JSON; multi-language WebVTT subtitles and chapter markers; server-side clipping that produces a new asset; signed or public playback with short-lived rotating tokens; a drop-in iframe hosted player.',
    },
    {
      q: 'What does the CDN support?',
      a: 'Pull zones mapping any hostname to an origin or storage zone; configurable per-zone TTL and cache-bypass prefixes; instant whole-zone and path-level purge in milliseconds; HMAC-signed URLs with rotatable secrets for hotlink protection; CORS handled at the edge; live edge analytics for requests, egress and cache-hit ratio per zone; S3-style storage zones with presigned uploads, CDN-fronted by default; ordered edge rules for header manipulation, redirect or block.',
    },
    {
      q: 'How does the edge compute layer work?',
      a: 'V8 isolates execute JavaScript handlers written as `Deno.serve(handler)`. No containers, no cold starts. Push code and invoke at `/__fn/<id>` within seconds. Handlers can also be wired into the pull-zone request lifecycle for auth wrapping, A/B routing, geo-routing, header rewriting. Per-project isolation, per-invocation metering, audit-logged code changes.',
    },
    {
      q: 'How does Ollanode compare to Mux and Cloudflare Stream?',
      a: 'Mux is the polished hosted alternative; Ollanode matches its working feature set and eliminates the per-minute and egress pricing. Cloudflare Stream is cheaper at the upper volume curve but operationally tied to the Cloudflare ecosystem and shallower on pipeline features. Ollanode is the right choice when unit economics matter, when data location matters, or when the team wants both a deep video pipeline and a first-class edge-compute layer in one platform.',
    },
    {
      q: 'Is Ollanode self-hosted?',
      a: 'The control plane is cloud-operated by Ollasoftware — there is nothing to install or run on the control-plane side. The data plane (video files, cached bytes, storage, transcoding compute) runs on infrastructure the customer designates: either a turnkey managed regional pool or compute and storage in the customer\'s own cloud account. This split is what allows the per-minute pricing and the vendor-metered egress to disappear without the customer giving up the operational simplicity of a managed platform.',
    },
    {
      q: 'Who is behind Ollanode?',
      a: 'Ollanode is built and operated by Ollasoftware, the Bengaluru-headquartered AI software development company. The CDN engineering inherits from the team that runs Crawlcrawl\'s high-volume crawler infrastructure; the control-plane discipline is shared with Aeoniti; the edge-compute layer comes from the Switchllm team. The video-pipeline instincts are anchored on the streaming operation Networkers Home — Ollasoftware\'s parent group — has run since 2007 across 45,000+ alumni and the active student body.',
    },
  ],
};
