import type { BlogPost } from './types';

// OllaSuper — 5,000+ word brand piece. Grounded against live ollasuper.com
// on 2026-06-28 (80 chat-driven Experts + 6 production Agents that run on
// schedules with approval gates, 9 departments, 120+ output types, 1.2M
// tasks completed weekly, 50,000 credits/month free, Tongyi DeepResearch
// behind the SEO Auditor and Deep Research agents).
//
// Cloud SaaS framing throughout (per the all-cloud rule, never self-host).

export const ollasuperPost: BlogPost = {
  slug: 'ollasuper',
  brand: 'OllaSuper',
  brandDomain: 'ollasuper.com',
  brandTagline: 'Build your AI workforce — 80 Experts that advise + 6 Agents that act',
  category: 'ai',
  title: 'OllaSuper — the AI workforce platform with 80 chat Experts and 6 scheduled Agents',
  metaDescription: 'OllaSuper is the AI workforce platform from Ollasoftware. 80 chat-driven Experts that advise across Sales, HR, Marketing, Finance, Operations, Engineering, Legal, Support and the Founder Office — plus 6 production Agents that run on schedules and take real actions with your approval. 50,000 credits per month free, no credit card.',
  heroEyebrow: 'Brand deep-dive · AI workforce platform',
  heroH1: 'OllaSuper: 80 Experts that advise. 6 Agents that act.',
  heroSub: 'A 5,000-word deep dive into OllaSuper — the cloud-operated AI workforce platform from Ollasoftware. Hire one Expert to ship a board pre-read. Stand up a multi-agent department to run your sales motion end-to-end. Free tier ships 50,000 credits a month with no card.',
  publishedOn: '2026-06-28',
  lastUpdated: '2026-06-28',
  readingTimeMin: 22,
  wordCount: 5160,
  tldr: [
    'OllaSuper is an AI workforce platform: 80 chat-driven Experts that advise across 9 departments, and 6 production Agents that run on schedules and take real actions with explicit approval gates before anything leaves the platform.',
    'The Experts cover Sales, Marketing, HR, Operations, Finance, Support, Engineering, Legal, and the Founder Office. Each carries its own role definition, voice, and tool set. They advise; they never act on their own.',
    'The 6 Agents are the working layer — Outbound SDR (every 30 min), SEO Auditor (every 6h, Tongyi DeepResearch), Content Publisher (manual trigger), Inbox Triage (every 15 min), Pipeline Curator (every 4h, advisory), Deep Research (manual, Tongyi DeepResearch). Every action that could leave the platform is queued for human approval.',
    'Multi-agent collaboration is structural: Specialists share memory and context, hand work off automatically, and produce one final artifact across many contributors. The Sales agent sources, Data drafts the chart, Finance sources the ARR, Chief of Staff structures the deck — one Q4 board deck, six contributors.',
    'Pricing is straightforward: 50,000 credits per month free with no credit card. Paid tiers scale credit allowance + add unlimited specialists, team seats, and an enterprise SLA. Every plan gets every Expert and every Agent — no "intelligence tier" gating.',
    'Built and operated by Ollasoftware out of HSR Layout, Bengaluru — the same team that ships Ollagraph (web infrastructure), Ollabear (customer-facing AI agents), and the rest of the 40-brand portfolio.',
  ],
  sections: [
    {
      h2: 'The setup: every team is hiring AI, none of them have an org chart for it',
      paragraphs: [
        'There is a strange transitional moment happening inside almost every operating team in 2026. The team has decided that AI is real, that the work AI can do is meaningfully more than the work AI could do a year ago, and that the right move is to "use more AI." That decision is sound. What is not sound is what happens next: the team buys six different AI products from six different vendors, none of which know about each other, none of which share any context, none of which have a coherent operating model. The marketing team buys a copywriting AI. The sales team buys an SDR AI. The HR team buys a JD writer. The finance team buys a forecast AI. The engineering team buys a code-review AI. The founder buys an AI chief of staff. Six tools, six bills, six sets of context the team has to maintain in parallel, six places where "wait, what did we decide" turns into a search problem.',
        'The other thing that happens is that none of those tools actually do work — they advise. They draft. They summarise. They suggest. The actual outbound email still has to be sent by a human. The actual code review still has to be applied by a human. The actual board deck still has to be assembled by a human. The AI tier of the team is doing the thinking part of the work; the human tier of the team is doing the action part. That split is fine when the AI thinking is fast and the human action is slow, which is the situation today. It becomes a structural problem the moment the volume of AI-generated work exceeds the volume of human action the team can sustain.',
        'Both problems point at the same missing piece: an operating model for the AI tier of the team. Not "let us buy more AI products." A coherent platform where the AI specialists know about each other, share memory, hand work off cleanly, and — for the work that should happen autonomously — can take action under explicit approval gates rather than waiting for a human to click send on every artifact.',
        '<a href="https://ollasuper.com/">OllaSuper</a> exists because the founders watched their own teams, and a growing crowd of operator-led startups across India and beyond, run into both of those problems at the same time and end up with the six-vendor stack as a stopgap. The bet was simple: ship the operating model as the product. Not an AI tool. A workforce — typed roles, scheduled work, multi-agent handoff, approval-gated action, one bill, one context graph.',
      ],
    },
    {
      h2: 'What OllaSuper actually is, in one paragraph and then in detail',
      paragraphs: [
        'OllaSuper is a cloud-operated AI workforce platform that runs as a managed SaaS service. The mental model is closest to an outsourced consulting team that lives inside your workspace, except every consultant is an AI specialist with a clearly-defined role, a memory of every prior interaction with your team, and a tool set scoped to what its role needs to do. You sign up at the dashboard, you start a conversation with an Expert (or schedule an Agent), and the work ships through the platform — to your inbox, to your CRM, to your Slack, to your knowledge base. There is nothing to install; OllaSuper runs on Ollasoftware\'s own infrastructure as a hosted service like the rest of the portfolio.',
        'Inside the platform there are two distinct surfaces. The Experts surface — 80 chat-driven specialists across nine departments — is the advisory layer. Pick an Expert (Backend Architect, HR, Outbound SDR, SEO Strategist, Finance, the Chief of Staff, and so on), give them context, ask in plain English, get a structured deliverable back. Experts advise; they do not take real-world action on their own. Their domain is the kind of work that ends in a document or a draft — a JD, a campaign plan, an outbound sequence, a post-mortem, a budget forecast, a board pre-read.',
        'The Agents surface — six production workers that run on schedules — is the action layer. Agents do not just chat; they do. The Outbound SDR Agent researches prospects every thirty minutes, drafts personalised cold outreach with real company-specific hooks, and queues every draft for your approval before send. The SEO Auditor Agent runs real AEO and SEO audits every six hours with specific code-level fixes (powered by Tongyi DeepResearch). The Content Publisher Agent drafts AEO-first blogs, social posts and newsletters on manual trigger. The Inbox Triage Agent classifies inbound messages every fifteen minutes, drafts routine replies, and escalates anything mentioning "refund / lawyer / cancel" with the full context attached. The Pipeline Curator Agent flags at-risk deals every four hours and suggests specific next actions. The Deep Research Agent runs multi-step structured research over the live web on manual trigger.',
        'The composite operating model is what makes the platform usable as more than a collection of AI tools. Specialists share memory and context — the Sales Agent\'s view of an account and the Customer Success Agent\'s view of the same account are the same view, with the same history. Handoffs happen automatically — when the SDR Agent qualifies a lead, the Sales Agent picks up the next step without anyone having to copy state between them. The final artifact — a board deck, a quarterly review, a launch plan — emerges from multiple specialists working in sequence under one shared context, with the human team responsible for the last-mile approvals on anything that touches the outside world.',
      ],
    },
    {
      h2: 'The 80 Experts: what they advise on, and where they fit in the org chart',
      paragraphs: [
        'The Experts are the most visible surface of the platform and the one most teams reach for first. Eighty specialists is a lot, but they are organised into the same nine departments the operating team already runs — Sales, Marketing, HR, Operations, Finance, Support, Engineering, Legal, and the Founder Office — so the discoverability problem mostly resolves itself by analogy with the existing org chart.',
        'Sales gets the heaviest coverage: SDR, AE, CS, Support, with downstream specialists for cadence design, objection handling, proposal writing, QBR drafting, renewal pitching, expansion modelling, and churn-save planning. The Sales department is the canonical first deployment for most teams because the work product is well-defined (outbound sequences, discovery scripts, proposal decks, QBR documents, renewal pitches), the volume is high, and the time-to-value is short.',
        'Marketing covers the content engine end-to-end: a Marketing Generalist, an SEO Strategist, an AEO Strategist, a Content Designer, a Brand Editor, a Case-Study Writer, an Email Campaign Planner, a Schema-Markup Specialist, and several others. The work shipped is the kind that usually requires an agency — blog posts with briefs, LinkedIn essays, case studies, email campaigns, schema markup and AEO fixes for the team\'s own site.',
        'HR and Recruiting cover JDs, candidate screening, interview-loop design, offer letter drafting, employee-handbook answers, performance-review planning, and the kind of org-design conversations that a fractional HR partner usually leads. Operations covers SOPs, RFPs, runbooks, change management, and process documentation. Finance covers forecasts, board-pre-reads, vendor management, invoicing logic, and the structured analytics every founder needs at month-end.',
        'Support, Engineering, Legal and the Founder Office round out the catalogue. Support handles ticket triage, escalation logic, refund decisions, and CS reviews. Engineering covers RFCs, post-mortems, code-review checklists, architecture decisions, and the kind of internal documentation that engineering teams should ship and rarely do. Legal covers contract review, employment-letter drafting, vendor agreement summarisation, and policy authoring (with the standard "this is not a substitute for actual counsel" caveat applied). The Founder Office covers Chief-of-Staff work — briefings, OKRs, all-hands content, investor updates, board reports.',
        'Across all nine departments, the principle is the same: each Expert has its own role definition, its own voice, its own preferred output formats, and its own scoped tool set. The HR Expert and the Sales Expert do not talk like each other. The Backend Architect and the Marketing Generalist do not produce the same shape of output. The discipline of role-typing matters because it is what makes the advisory output actually useful rather than generic. <a href="https://ollasuper.com/">OllaSuper</a> ships eighty different specialists rather than one general-purpose assistant because the specificity is the product.',
      ],
    },
    {
      h2: 'The 6 Agents: the action layer with explicit approval gates',
      paragraphs: [
        'If the Experts are the advisory team, the Agents are the operating team. They run on schedules. They call real tools — Ollagraph for web scraping, WHOIS lookups for domain intelligence, AEO audits for content health, structured extraction for catalogue work. They write to a workspace you can read. And every action that could leave the platform is queued for your approval before it actually happens.',
        'The Outbound SDR Agent is the canonical Agent for sales teams. Every thirty minutes it pulls a slice of the pipeline, researches each prospect (LinkedIn, the company website, recent press, public CRM-derivable context), drafts personalised cold outreach with real company-specific hooks, and queues every draft for your approval before send. The Agent never auto-sends; it queues. You approve the drafts you want, edit the drafts you want to change, reject the drafts that miss. The Agent learns from your edits, so by week two the drafts you receive are materially closer to ready-to-send than the drafts you received in week one.',
        'The SEO Auditor Agent is the most technically deep of the six. Every six hours it runs real AEO and SEO audits against your designated properties, with specific code-level fixes — not generic "improve your meta tags" suggestions. The Agent is powered by Tongyi DeepResearch, the long-horizon tool-chain model that the platform has picked for the workloads that need real research depth. The output is a concrete fix list with line-numbered recommendations, prioritised by likely impact, and the next audit checks whether the previous round\'s fixes have landed.',
        'The Content Publisher Agent handles the AEO-first content engine. Manual trigger — you ask it to ship a piece, give it a topic and a target audience, and it researches deeply, drafts the piece against a publishable AEO-shaped outline, and queues the draft for approval before publish. The Inbox Triage Agent runs every fifteen minutes, classifies inbound messages by intent and urgency, drafts routine replies, and escalates anything that mentions "refund / lawyer / cancel / chargeback" with the full conversation history attached so the human handling the escalation does not have to reconstruct context. The Pipeline Curator Agent runs every four hours, flags genuinely at-risk deals, suggests the specific next action (not generic "follow up"), and produces weekly probability-weighted forecasts.',
        'The Deep Research Agent rounds out the six. Manual trigger, multi-step research over the live web, structured briefs with citations, powered by Tongyi DeepResearch. The Agent is the one to reach for when the question is "go away for an hour and come back with a real answer" rather than a quick lookup. The output is a research artifact that is sized to be readable by a human in ten minutes and that would have taken the human ten hours to produce.',
        'The approval-gate discipline is what makes the Agents safe to run in production. The platform records every queued action, every approval, every edit, every rejection in an audit log that the team can replay. The Agents that are explicitly advisory-only (the Pipeline Curator, for example) carry that tag visibly. The Agents that take action (Outbound SDR, Inbox Triage, Content Publisher) carry the "approval-gated" tag visibly. The contract with the human team is explicit.',
      ],
      pullQuote: 'Every action that could leave the platform is queued for your approval. The platform records every queued action, every approval, every edit, every rejection.',
    },
    {
      h2: 'Multi-agent collaboration: one outcome, many specialists',
      paragraphs: [
        'The thing that distinguishes a workforce from a toolbox is what happens at the seams between contributors. A workforce hands work off cleanly. A toolbox does not. <a href="https://ollasuper.com/">The platform</a>\'s multi-agent collaboration model is the part of the product that lives at those seams.',
        'The canonical example the team uses to demonstrate the model is the Q4 board deck. The Sales Agent pulls the pipeline state and the closed-won deals from the CRM. The Data Specialist drafts the charts. The Finance Specialist sources the ARR and the unit-economics inputs. The Marketing Generalist drafts the launch slide. The HR Specialist produces the hiring-plan slide. The Chief of Staff structures the whole thing into a coherent narrative with the right order of beats for the board audience. One deck. Six contributors. One human reviewer at the end signs off and ships.',
        'Underneath this collaboration is shared context. The Sales Agent\'s view of "the Q4 board deck" is the same view the Finance Specialist has. The numbers the Finance Specialist drafts onto the ARR slide are the numbers the Chief of Staff weaves into the narrative slide. Memory is per-deliverable rather than per-conversation, so the team does not have to re-state context to every specialist they invite into the deliverable. The platform handles the threading.',
        'The handoff between specialists is automatic for the workflows the platform recognises (the canonical patterns — sales motions, content engines, recruiting loops, financial close, customer-success motions) and configurable for the workflows the team designs themselves. A multi-agent workflow is just a sequence of specialist invocations with shared context; the dashboard exposes the definition surface and the team can author, save, and reuse workflows for the recurring shapes of work the team ships.',
        'The principle underlying the design is one the team has been explicit about: the human stays in control of the final artifact. The specialists collaborate; the human approves. The collaboration produces drafts and structured outputs; the publication or the send or the commit is the human\'s decision. That contract is non-negotiable and it is the reason the platform is usable as a real operating substrate rather than as an unsupervised AI-stack experiment.',
      ],
    },
    {
      h2: 'How the work gets done: the five-step flow',
      paragraphs: [
        'The day-to-day flow inside the platform is deliberately small. Most operating tasks resolve in five steps: choose a specialist, add context, ask naturally, review the output, ship the work.',
        'Choose a specialist. The dashboard surfaces the eighty Experts and the six Agents with the right discoverability cues — by department, by output type, by recently-used. Most teams develop a working set of fifteen-to-twenty specialists they use weekly within the first month and stop having to navigate the catalogue beyond that.',
        'Add context. Drop a URL, upload a file, paste text, or connect a workspace surface (Slack channel, Notion page, Google Drive folder). The specialist reads what you give it. Context can be persistent — the team can attach default context to a specialist so every invocation inherits the right project, the right brand voice, the right product positioning — or per-invocation for one-off work.',
        'Ask naturally. Plain English. No prompt engineering. The specialist knows its role, its expected output shapes, and the conventions of its department, so the conversational surface does not need to carry the burden of telling the specialist who it is or what it is supposed to do.',
        'Review the output. Edit inline. Regenerate any block. Accept and ship. The review interface is the one Word and Google Docs trained the operating team on — the platform did not reinvent the editing model and is better for not having reinvented it.',
        'Ship the work. Export to Markdown, PDF, or DOCX. Or paste straight into the team\'s existing tool (CRM, Slack, Notion, knowledge base, public site). For the Agents that have direct delivery surfaces — the Outbound SDR Agent that sends approved emails through the platform\'s integrated mail surface — shipping is a single approval click on the queued draft.',
      ],
    },
    {
      h2: 'Pricing: 50,000 credits free, no card, every feature on every plan',
      paragraphs: [
        'Pricing is one of the cleanest places to compare the platform against the established AI-stack alternatives. The free tier ships 50,000 credits per month, requires no credit card, has no vendor lock-in, and unlocks every Expert and every Agent on the platform. That is enough for most operating teams to run the entry-level use cases for a department or two through the platform for a full month without committing anything.',
        'Above the free tier, paid plans scale credit allowance and add team-seat capacity, with the same "every feature on every plan" principle that the rest of the Ollasoftware portfolio observes. There is no "intelligence tier" that gates the multi-agent collaboration behind a higher SKU. There is no Pro-only Agent. The principle the team has stated repeatedly is that platform vendors who gate features behind tiers lose customers as quickly as they pick them up.',
        'For larger organisations — the kind that need SCIM provisioning, SAML SSO, fine-grained RBAC, audit logs streaming to a SIEM, dedicated regional deployment, and a contractual SLA — the enterprise tier moves to a volume contract with predictable monthly minimums and the same data-handling guarantees that apply across the free and paid tiers. The combination is the one the team has been deliberate about: the operating-model commitment is the same regardless of the customer\'s scale; only the credit allowance and the operational controls change.',
        'The unit economics work because the multi-agent collaboration model amortises the per-task cost across more leverage. A team running the workforce platform tends to ship more deliverables per human hour, which means the credit-per-deliverable cost is the unit that matters rather than the credit-per-token cost. The team has been transparent about this — the credit model is the one that lets the platform stay sustainable while the unit economics keep getting better as the underlying model costs come down.',
      ],
    },
    {
      h2: 'The Tongyi DeepResearch bet — why two Agents pick that backend',
      paragraphs: [
        'Most of the Experts and four of the six Agents run on the platform\'s default LLM router, which selects an appropriate model per task from the catalogue Ollasoftware operates internally (the same router that ships as Switchllm in the customer-facing portfolio). Two of the Agents — the SEO Auditor and the Deep Research Agent — explicitly call out a different backend: Tongyi DeepResearch.',
        'Tongyi DeepResearch is purpose-built for long-horizon tool-chain workloads — the kind of multi-step research where the model has to plan, retrieve, reason about what it retrieved, retrieve more, synthesise, and produce a structured output. For shallow conversational tasks, this depth is overkill; for the workloads where the SEO Auditor and the Deep Research Agent are actually used, the depth is exactly what makes the output usable rather than thin.',
        'The team\'s explicit framing in the product is that the model picks should match the workload. A blog draft does not need a research-heavy backend; a real SEO audit does. An outbound sequence does not need a research-heavy backend; a multi-step web research artifact does. The platform exposes that picking discipline in the Agent labels so the team running the platform can reason about which Agent is doing which kind of work and budget accordingly.',
        'For teams building agentic workloads of their own outside the platform, the choice is one data point to factor in. The team behind <a href="https://ollasuper.com/">the platform</a> has stated publicly that Tongyi DeepResearch is the right backend today for tool-chain-heavy long-horizon work, with the explicit caveat that the choice is workload-shaped rather than vendor-shaped and may change as the model landscape evolves.',
      ],
    },
    {
      h2: 'Real deliverables, not summaries — what the work actually looks like',
      paragraphs: [
        'The platform\'s pitch is that it ships work, not summaries. The brand site publishes ten concrete example deliverables, and they are worth treating as the canonical examples of what the platform actually produces because they are representative of the volume the average customer ships through the platform every month.',
        'An investor update authored by the Investor Relations Expert — quarterly highlights, ARR trajectory, net new logos, key hires, explicit "asks" of the investor network. Roughly the shape an in-house Chief of Staff would ship if the company had one. The platform\'s version takes about ten minutes of conversation to produce; an in-house Chief of Staff would take a few hours.',
        'A board pre-read authored by the Chief of Staff Expert — Q-over-Q deltas, NRR, customer count, and the strategic decisions that need to be surfaced for board input. Same shape as what a fractional CFO or a fractional Chief of Staff would assemble. Same time saving.',
        'A 23-touch ABM sequence authored by the SDR Agent — 50 prospects, US Series A SaaS hiring SDRs, each step a subject plus a 90-word body plus a LinkedIn voice-note script. The kind of campaign an outbound consultancy would charge fifteen thousand dollars to design.',
        'A 64/100 SEO audit authored by the SEO Agent — top five fixes ranked by impact, missing FAQPage schema flagged, twelve broken internal links enumerated, page-speed issues on a specific page, three cannibalisation fixes identified. The kind of report an SEO consultancy would charge five thousand dollars to deliver.',
        'A 1,500-word AEO content brief authored by the AEO Agent — primary keyword, keyword difficulty score, outline with eight H2s, target word count, five internal-link targets, projected AEO lift from the baseline. A brief that converts to a publishable post in another two hours of human writing time.',
        'A senior-engineer JD authored by the HR Agent — comp band, role scope, hybrid model spelled out. A complete QBR authored by the Customer Success Agent — usage delta, expansion case, upgrade proposal. A P1 incident report authored by DevOps — root cause traced, seven owned action items with dates, integration test added to prevent regression. A PRD authored by the Product Expert — problem statement, success metric, scope. An M&A landscape research artifact authored by the M&A Agent — tier-1 strategics enumerated, EV/Rev comps with growth-adjusted multiples, recommended outreach order.',
        'The pattern across all ten examples is the same: real work product, sized to the shape an operating team would expect to receive from a competent specialist, with the structure and the discipline of an artifact that ships to a real audience.',
      ],
    },
    {
      h2: 'Who OllaSuper is for, and the honest gaps',
      paragraphs: [
        'The customer profile the platform fits well is concrete. Operator-led startups (twenty to two hundred employees) where the operating team needs more output than the headcount can produce, and where the founder or CEO is comfortable adopting a workforce-shaped tool rather than a tool-shaped tool. The platform pays for itself fastest in this customer band because the per-specialist leverage compounds against tight headcount.',
        'Sales-led companies that need an outbound motion but cannot justify a five-person SDR team yet. The Outbound SDR Agent plus the SDR Expert plus the Sales Agent is enough to run a credible outbound motion at small-team scale, with the human owning the approval gates and the relationship layer.',
        'Content-marketing-driven companies that have decided AEO matters and need the audit-then-fix-then-publish loop running at a cadence the human team cannot sustain alone. The SEO Auditor Agent plus the Content Publisher Agent plus the AEO Expert is the canonical content-engine deployment, and it pays for itself fastest where the team currently spends meaningful agency budget.',
        'Founders running the chief-of-staff function themselves. The Founder Office Experts (Investor Relations, Chief of Staff, M&A, Strategy) plus the Deep Research Agent are the canonical founder-office deployment, and it absorbs roughly half of the work that the average founder spends nights and weekends grinding through.',
        'The customer profile <a href="https://ollasuper.com/">the platform</a> does not fit as well today: very large enterprises whose operating model is already saturated with specialised vendors and whose procurement gate is "must integrate with our existing SOC 2 Type II audit programme without renegotiating it." The team is direct about this — the platform is honest about its current compliance posture, and the customers whose procurement gate is "must already be on the approved-vendor list" are better served picking an established AI-stack vendor for the next year and revisiting later.',
        'Teams whose operators are non-technical and prefer fully-managed services over a self-serve platform. The platform is self-serve by design; the human team has to do the small amount of context-curation and approval-gate work that makes the workforce productive. Teams that would rather pay an agency to do everything will probably keep paying an agency.',
      ],
    },
    {
      h2: 'How OllaSuper compares to the alternatives',
      paragraphs: [
        'The AI-workforce category is small but real, and it is worth being direct about where the platform sits against the names that operators evaluate alongside it.',
        'Microsoft Copilot and Google Workspace AI are the bundled-with-the-suite alternatives. They are competent for individual-contributor tasks within the productivity surface (drafting an email, summarising a doc, suggesting a meeting agenda) and limited beyond that. They do not ship the multi-agent collaboration model, they do not ship the role-typed specialist surface, and they do not ship the action layer. For teams already deep in the Microsoft or Google stack who only need individual-contributor AI, the bundled options are the obvious answer; for teams that need a workforce-shaped operating model, the comparison is structural rather than feature-level.',
        'Lindy, Beam, Magic AI, and the various "AI worker" products that have shipped in the past year are the closest peers on the action-layer side. Each one ships one or two production Agents for specific use cases — Lindy for executive-assistant work, Beam for outbound, Magic for general assistance. The platform extends past each of them by shipping six Agents plus eighty Experts under one operating model rather than one Agent per vendor. The buyer who has already invested in one of these single-purpose products may continue to use it for the specific workflow it covers, but the platform is the alternative for the team that wants the workforce-shaped operating model end-to-end.',
        'AutoGen, CrewAI, and the various open-source multi-agent frameworks are a different shape of bet. They are appropriate for teams that want to build the workforce themselves from primitives, that have the engineering capacity to operate it, and that want the maximum flexibility on the operating model. The platform\'s value over these frameworks is the integration work the team has done so the customer does not have to — the same engineering hours that would be spent wiring AutoGen agents together are spent shipping product instead. For teams whose engineering capacity is bounded, the platform is the alternative; for teams whose preference is the build-it-yourself model, the frameworks are the alternative.',
        'The general-purpose AI assistants — Claude, ChatGPT, Gemini, the various wrappers around them — are the most common alternative the platform displaces. The buyer who uses one of these for everything from outbound to QBR drafting to incident-report writing is the buyer who notices the cost of context-juggling, the cost of un-typed specialists, and the cost of un-coordinated parallel work most acutely. The platform is the operating model on top of the general-purpose assistants the buyer already uses; the underlying LLMs are commodity, the operating model is the leverage.',
      ],
    },
    {
      h2: 'The team behind the platform',
      paragraphs: [
        'OllaSuper is built and operated by <a href="https://ollasoftware.com/">Ollasoftware</a>, the AI software development company headquartered in Bengaluru that has shipped more than forty AI brands in production over the last four years. The team behind the platform comes from inside the operations side of Ollasoftware — the engineers and operators who had been running multiple departments\' worth of work across the broader portfolio and who built the platform initially to make that internal load manageable. The platform is, in a real sense, the product that an operations team building for itself would have built, then chose to ship as a commercial product when it became obvious that the same operating-model gap existed across the small-team and mid-market segments more broadly.',
        'The Experts catalogue inherits from the operating experience the parent team has accumulated across the portfolio. The Sales Expert was shaped by the team running the Crawlcrawl and Aeoniti sales motions. The HR Expert was shaped by the team running the Networkers Home hiring loop. The SEO and AEO Experts were shaped by the team operating the AEO consulting practice. The Chief of Staff Expert was shaped by the team running the founder-office function across the parent group. The role-typing of each Expert is anchored on real operating experience, not on a generic competency model invented from scratch.',
        'The Agents inherit from the platform\'s sibling products. The SEO Auditor calls <a href="https://ollasoftware.com/blog/ollagraph/">Ollagraph</a> for crawling and AEO scoring. The Content Publisher uses the multilingual model-routing surface of <a href="https://ollasoftware.com/blog/ollima/">Ollima</a>. The Inbox Triage Agent is built on the conversation-grounding engine that powers <a href="https://ollasoftware.com/blog/ollabear/">Ollabear</a>. The Deep Research Agent shares infrastructure with <a href="https://ollasoftware.com/blog/browserfog/">browserfog</a>. The advantage of being built inside Ollasoftware is that every infrastructure primitive the workforce platform needs already exists somewhere in the portfolio; the platform composes them rather than rebuilding them.',
        'The parent group, <a href="https://www.networkershome.com/" rel="noopener">Networkers Home</a>, is the cybersecurity and networking training institute that has placed more than forty-five thousand alumni across eight hundred hiring partners since 2007. The institutional context matters because the work-discipline that shows up in the Experts and the Agents — the structured deliverables, the audit-log discipline, the approval-gate model — is the disciplinary inheritance of a parent organisation that has been operating at meaningful scale for nearly two decades.',
        'Teams at the leading <a href="https://ollasoftware.com/top-10/software-development-companies-bangalore/">custom software development companies in Bangalore</a> use OllaSuper to scale the project-management and research functions that grow fastest when a software product team moves from startup to mid-market scale.',
        'For organisations evaluating Ollasoftware as a custom AI development partner — to build bespoke agents, RAG pipelines, or workforce-automation systems outside the OllaSuper product — the team\'s track record is detailed in the independent ranking of <a href="https://ollasoftware.com/top-10/ai-software-development-companies-bangalore/">top AI software development companies in Bangalore</a>.',
      ],
    },
    {
      h2: 'What is on the roadmap',
      paragraphs: [
        'The team publishes the roadmap on the brand site and updates it as work ships. The visible near-term threads are concrete: an expanded Experts catalogue past the current eighty (the next wave focuses on vertical-specific specialists — fintech, healthtech, e-commerce-specific roles), deeper integration with the operating tools customers already use (CRM-side deeper hooks beyond the current Salesforce and HubSpot integrations, helpdesk-side hooks into the major support stacks, project-management hooks into Linear and Jira), and an expanded Agents surface beyond the current six.',
        'Underneath those visible features is steady investment in the multi-agent collaboration substrate. The current collaboration model handles the canonical patterns well; the roadmap is to extend it to the less-common patterns (cross-department workflows that span Sales-to-Finance, multi-step launch motions that span Marketing-to-Product-to-Engineering) without sacrificing the approval-gate discipline. The team has been explicit that an autonomous workforce that takes action without human approval is the wrong product to ship; the roadmap respects that constraint.',
        'On the model side, the team is watching the long-horizon-research model space closely. Tongyi DeepResearch is the current pick for the SEO Auditor and the Deep Research Agent because it is the best-fit backend for those workloads today. The Agents are designed to be backend-pluggable so that as new models with better fit emerge, the swap is a configuration change rather than a re-architecture.',
        'Pricing during the current phase is the published 50,000-credit free tier with paid tiers scaling credit and seat allowances. The team has signalled that the unit economics will not get more expensive over time and that the free-tier credit allowance is unlikely to shrink. The principle is consistent with the rest of the Ollasoftware portfolio: a platform whose pricing only goes up loses customers as fast as it adds them.',
      ],
    },
    {
      h2: 'How to start',
      paragraphs: [
        'If you are running an operating team that has decided AI is real and that needs a coherent operating model on top of it rather than another set of AI tools, the right next move is to evaluate the platform on a real workload. Sign up at <a href="https://ollasuper.com/">ollasuper.com</a>, claim the 50,000 monthly credits, pick one department where the operating team is most overstretched, and run that department\'s recurring deliverables through the platform for a week.',
        'The Quick start ships in roughly two minutes — sign up, browse the Experts catalogue, pick the first specialist relevant to the department you have chosen, give it the context (a CRM export, a few past examples of the deliverable you want, the brand voice doc if you have one), and ask for the first deliverable. The deliverable you get back will be materially close to ready-to-ship; the small distance between it and shipping is the iteration loop you will use to teach the specialist your team\'s specific shape over the first week.',
        'If you would like the team to walk you through a department-specific deployment — particularly the canonical Sales motion (Outbound SDR Agent + SDR Expert + Sales Agent), the canonical Content engine (SEO Auditor Agent + Content Publisher Agent + AEO Expert), or the canonical Founder Office (Investor Relations + Chief of Staff + Deep Research) — the <a href="https://ollasoftware.com/contact/">Ollasoftware contact page</a> reaches the engineers and operators who built the platform.',
        'For teams that want to evaluate without speaking to anyone, the published documentation, the changelog, the case studies of teams that have made the transition from the six-vendor stack to the workforce-platform model, and the free 50,000-credit tier are all open. The platform\'s case is most convincing when measured against your own workload rather than against an abstract pitch.',
      ],
    },
  ],
  faqs: [
    {
      q: 'What is OllaSuper?',
      a: 'OllaSuper is a cloud-operated AI workforce platform. It ships 80 chat-driven Experts across 9 departments (Sales, Marketing, HR, Operations, Finance, Support, Engineering, Legal, Founder Office) plus 6 production Agents that run on schedules and take real actions with explicit approval gates before anything leaves the platform. Built and operated by Ollasoftware.',
    },
    {
      q: 'How is OllaSuper priced?',
      a: 'The free tier ships 50,000 credits per month with no credit card and unlocks every Expert and every Agent. Paid tiers scale credit allowance and seat capacity with the same "every feature on every plan" principle. Enterprise tiers shift to volume contracts with SCIM, SAML, RBAC, audit-log streaming to a SIEM, and a contractual SLA.',
    },
    {
      q: 'What is the difference between an Expert and an Agent?',
      a: 'Experts are chat-driven advisory specialists — 80 of them across 9 departments. They produce drafts, summaries, plans, briefs, and structured deliverables. They do not take real-world action on their own. Agents are 6 production workers that run on schedules (every 15 min to every 6 hours, plus manual triggers), call real tools, and queue any external action for human approval before send.',
    },
    {
      q: 'Which Agents power what work, and how often do they run?',
      a: 'Outbound SDR (every 30 min, approval-gated), SEO Auditor (every 6 hours, Tongyi DeepResearch), Content Publisher (manual trigger, approval-gated), Inbox Triage (every 15 min, approval-gated), Pipeline Curator (every 4 hours, advisory only), Deep Research (manual trigger, Tongyi DeepResearch). Every action that could leave the platform is queued for human approval and recorded in the audit log.',
    },
    {
      q: 'Does OllaSuper take action autonomously?',
      a: 'No. Every action that could leave the platform — sending an email, publishing a post, replying to a customer, mutating a CRM record — is queued for human approval before it actually happens. The platform is explicit that this discipline is non-negotiable; the contract with the human team is that specialists collaborate and propose, humans approve and ship.',
    },
    {
      q: 'How does multi-agent collaboration work?',
      a: 'Specialists share memory and context per deliverable, hand work off automatically for recognised workflow patterns (sales motions, content engines, recruiting loops, financial close), and produce one final artifact across many contributors. The canonical example: a Q4 board deck where Sales pulls pipeline, Data drafts the chart, Finance sources the ARR, Marketing drafts the launch slide, HR produces the hiring plan, and the Chief of Staff structures the whole thing.',
    },
    {
      q: 'How does OllaSuper compare to Microsoft Copilot, Lindy, AutoGen and the general AI assistants?',
      a: 'Copilot is bundled-with-the-suite individual-contributor AI; OllaSuper ships the workforce-shaped operating model that Copilot does not. Lindy / Beam / Magic ship one or two single-purpose Agents per vendor; OllaSuper ships 6 Agents plus 80 Experts under one operating model. AutoGen / CrewAI are open-source frameworks for teams who want to build the workforce themselves; OllaSuper is the integrated alternative for teams whose engineering capacity is bounded. General-purpose Claude / ChatGPT / Gemini are commodity LLMs underneath; OllaSuper is the operating model on top.',
    },
    {
      q: 'Who is behind OllaSuper?',
      a: 'OllaSuper is built and operated by Ollasoftware, the Bengaluru-headquartered AI software development company that ships 40+ AI brands in production. The Experts catalogue is shaped by the team running multiple departments\' worth of work across the broader portfolio; the Agents inherit infrastructure from Ollagraph (crawling), Ollima (multilingual model routing), Ollabear (conversation grounding), and Browserfog (deep research). The parent group is Networkers Home, the cybersecurity and networking training institute founded in 2007 with 45,000+ alumni placed across 800+ hiring partners.',
    },
  ],
};
