import type { BlogPost } from './types';

// Ollanode — fully cloud SaaS piece. Rewritten 2026-06-24 after founder
// correction: "no its cloud saas model like nextdns". The brand site's
// "self-hosted / BYO infra" framing is a marketing bug; Ollanode actually
// runs as a turnkey hosted platform — sign up, get a cloud account, use
// the APIs, the platform handles compute, storage, transcoding, CDN, edge
// compute, billing. Customer brings nothing.
//
// NextDNS analogy is the founder's framing: a polished hosted platform
// that competes on UX, depth and price against the incumbents in the
// category — for Ollanode, that's Mux and Cloudflare Stream.
//
// Anchor distribution: 6-8 to ollanode.com, 2-3 to ollasoftware.com,
// 1-2 to networkershome.com.

export const ollanodePost: BlogPost = {
  slug: 'ollanode',
  brand: 'Ollanode',
  brandDomain: 'ollanode.com',
  brandTagline: 'The hosted video, CDN and edge platform — Mux-class features at a fraction of the price',
  category: 'ai',
  title: 'Ollanode — the hosted video, CDN and edge-compute platform with Mux-class features',
  metaDescription: 'Ollanode is a fully hosted, cloud-operated platform for video, CDN, storage and edge compute. Mux-class video pipeline, Cloudflare-Stream-class CDN, V8-isolate edge compute, 60+ REST endpoints — all behind one API and one predictable monthly bill. Built for product teams who want depth without per-minute pricing.',
  heroEyebrow: 'Brand deep-dive · hosted video & CDN',
  heroH1: 'Ollanode: hosted video and CDN with the depth of Mux at a fraction of the price.',
  heroSub: 'A 5,000-word deep-dive into Ollanode — the fully hosted video, CDN and edge-compute platform from Ollasoftware. Sign up, get an account, ship video to your customers — the same product surface as Mux and Cloudflare Stream, integrated with first-class edge compute, on a predictable cloud-SaaS bill.',
  publishedOn: '2026-06-24',
  lastUpdated: '2026-06-24',
  readingTimeMin: 22,
  wordCount: 5180,
  tldr: [
    'Ollanode is a fully hosted, cloud-operated platform for video, CDN, storage and edge compute. There is nothing to install, no infrastructure to provision, no cloud account to wire up — sign up, get an API key, ship.',
    'Four composable primitives behind one control plane: a Mux-class video pipeline (ingest, transcode, transcripts, subtitles, clipping, hosted player); a Cloudflare-Stream-class CDN (pull zones, storage zones, instant purge, signed URLs); V8-isolate edge compute (Deno.serve handlers, no cold starts); a developer-grade control plane (API keys, webhooks, RBAC, audit log).',
    'The closest mental model is NextDNS for the video-and-CDN category — a polished hosted platform that competes on depth, UX, and price against larger incumbents. Mux is the obvious feature comparison; Cloudflare Stream is the obvious price comparison; Ollanode sits at the intersection.',
    'Edge compute is included as a first-class layer, not an upsell. Auth wrapping, A/B routing, geo-routing, header rewriting — all run at the edge, next to the cache, in V8 isolates with no cold-start penalty.',
    'Pricing is predictable, published, and structured around sensible bands rather than per-minute and per-gigabyte multipliers that surprise teams at scale. The free tier is generous enough to evaluate the platform on real workloads without a credit card.',
    'Built and operated by Ollasoftware out of HSR Layout, Bengaluru — the same team that runs Crawlcrawl\'s high-volume crawler infrastructure, Aeoniti\'s enterprise control plane, and the V8 gateway underneath Switchllm. Video-pipeline instincts anchored on the streaming operation Networkers Home has run since 2007.',
  ],
  sections: [
    {
      h2: 'The setup: video is too complicated, too fragmented, and too expensive',
      paragraphs: [
        'Every product team that ships video runs into the same three problems within the first month of trying to do it well. Video is too complicated — the pipeline from raw upload to playback touches at least seven distinct concerns (ingest, transcoding, storage, delivery, transcripts, subtitles, the player itself) and there is no single open-source toolchain that handles them coherently. Video is too fragmented — the established hosted vendors each own a slice of the surface, none of them own all of it, and the team ends up running three vendors in parallel with three integrations and three monthly bills. Video is too expensive — at scale, the per-minute encoding fees and per-gigabyte egress fees that define the category make the line item one of the largest in the COGS, often second only to the cloud compute itself.',
        'The conventional answers solve one problem at a time. Mux solves "video is too complicated" by shipping a polished, deep, well-engineered pipeline behind a clean API — and charges premium per-minute rates for the privilege. Cloudflare Stream solves "video is too expensive" by riding Cloudflare\'s own bandwidth pricing — and ships a feature surface that is meaningfully shallower than Mux on the dimensions teams care about most (transcripts, server-side clipping, player flexibility). Component-level vendors — AWS MediaConvert, CloudFront, Bunny Stream, Cloudinary — solve narrow slices and force the team to handle integration as their own problem.',
        'The third problem — fragmentation — is the one nobody in the category solves, because solving it requires shipping a single product across the entire video-and-CDN surface. Mux owns the video pipeline but not the CDN at any depth. Cloudflare Stream owns the CDN at depth but ships the pipeline as a thinner add-on. Bunny ships both but at the price tier that fits its volume-economics position. Cloudinary ships images first and video second. None of them include edge compute as a first-class layer, which is the thing the modern web player increasingly needs sitting between itself and the cache.',
        'Ollanode exists because the founders watched their own portfolio companies — and a growing crowd of streaming-heavy product teams across India and beyond — run into all three problems at once and end up assembling the same uncomfortable three-vendor stack to solve them. The bet was simple: ship a single hosted platform that does the entire video, CDN, storage and edge-compute surface at depth, with the polish and developer-grade UX of a top-tier product, at a price structure that does not punish success.',
      ],
    },
    {
      h2: 'What Ollanode actually is, in one paragraph and then in detail',
      paragraphs: [
        '<a href="https://ollanode.com/">Ollanode</a> is a fully hosted, cloud-operated platform for video, CDN, storage and edge compute. The mental model is closest to NextDNS for this category: a polished hosted product that you sign up for, configure, point your application at, and use. There is nothing to install. There is no cloud account of yours that the platform requires access to. There is no infrastructure decision to make. You sign up at the dashboard, you create a project, you get an API key, you start uploading video and serving it through the CDN. The platform handles the rest.',
        'Inside the platform there are eight microservices behind sixty-plus REST endpoints, organised into four composable layers: video, delivery, edge compute, and control plane. The layers compose so that a typical workload — an uploaded video, transcoded, transcribed, streamed through a CDN, with an edge function handling auth — touches all four layers through one API key and one set of webhook subscriptions. The pipeline is async by default, fast in the common case, and observable end-to-end in the dashboard.',
        'The hosting model is the same hosting model the rest of the Ollasoftware portfolio uses: cloud-operated by the team, running on Ollasoftware\'s own infrastructure at the regional pools that serve global traffic, with a transparent pricing surface, a self-serve free tier, and the operational maturity that comes from a team that has been running production AI infrastructure at billion-page-a-month scale for several years. The customer\'s job is to ship product; the platform\'s job is to be invisibly reliable underneath it.',
        'Competitively, the platform sits in a specific place. It is not trying to undercut Bunny on the rock-bottom-cost tier (Bunny serves that market well and is the right answer for teams whose only requirement is the lowest bandwidth bill). It is not trying to win the largest enterprise contracts away from Mux (Mux owns that market through depth of relationships and SLAs the team has spent years cultivating). It is trying to be the right answer for the very large middle — series-A to mid-market product teams who want depth, UX and operational maturity comparable to Mux at a price comparable to Stream, with edge compute included rather than bolted on.',
      ],
    },
    {
      h2: 'The four primitives, and what each one does',
      paragraphs: [
        'The platform exposes four composable layers: video, delivery, edge compute, and control plane. Each is a family of capabilities behind a coherent API; the layers were designed together rather than acquired or assembled, which is what makes the composition clean.',
        'The video layer is the full pipeline from raw upload to playback. Ingest accepts direct uploads for small files, resumable multipart uploads for large files, and pull-from-URL when the source is hosted elsewhere. Transcoding produces an adaptive HLS ladder with configurable quality presets, H.264 + AAC defaults, loudness normalisation, and MP4 renditions for the use cases that need them. Thumbnails and storyboards generate poster frames and scrubbing sprite sheets with a `storyboard.vtt` modern players consume directly. Transcripts run on a Whisper-powered backend and produce VTT, SRT, and timed-segment outputs. Subtitles and chapters handle the metadata surface with multi-language WebVTT tracks. Server-side clipping cuts sub-clips into brand-new assets in one API call. Playback is signed or public, with short-lived rotating tokens. A drop-in iframe hosted player handles the player surface for teams that do not want to wire their own.',
        'The delivery layer is a multi-tenant CDN with pull zones and storage zones as the two primary objects. Pull zones map any hostname to either an arbitrary upstream or a managed storage zone, with configurable TTLs and cache-bypass prefixes for dynamic paths. Purge is instant and granular — whole-zone in milliseconds, path-level in the same time. Hotlink protection uses HMAC-signed URLs with rotatable secrets. CORS is handled at the edge so the origin never sees the preflight. Storage zones are S3-style buckets with presigned uploads, CDN-fronted by default. Edge rules let you set headers, redirect or block based on ordered conditions.',
        'The edge compute layer runs JavaScript in V8 isolates next to the cache. The handler shape is standard `Deno.serve(handler)`. There are no containers, no cold starts, no build step beyond the JavaScript itself. Push code, invoke at `/__fn/<id>` within seconds, or wire the handler into the pull-zone request lifecycle for auth, A/B and geo-routing. Per-project isolation is structural; metering is per-invocation.',
        'The control plane layer is the operational substrate that the rest inherits. API keys at read, write, admin tiers; rotatable, scoped per project. Webhooks HMAC-signed and retried, with structured events. Analytics for storage, views, status breakdowns, per-day rollups, top videos. Team and roles for scoped multi-user access. Audit log for every mutation. Self-serve auth covering signup, email verification, password reset.',
      ],
    },
    {
      h2: 'The video pipeline in depth',
      paragraphs: [
        'The video pipeline is the layer where the platform gets compared most directly to Mux, and it is the layer the team has invested the most engineering in over the last two years. The capability surface matches Mux closely on the features production customers actually use, and diverges where the team has had a deliberate reason to choose differently.',
        '<a href="https://datatracker.ietf.org/doc/html/rfc8216" rel="noopener noreferrer">Adaptive HLS</a> is the default output. The ladder is configurable per project — by default the platform produces a sensible four-rung ladder for the median customer (240p, 480p, 720p, 1080p, H.264 video, AAC audio), and individual projects can extend it upward (4K, HEVC for the projects that opt in) or downward (180p for the low-bandwidth markets). Loudness normalisation runs by default so that audio levels across the catalogue stay within a couple of LUFS of each other — a small but operationally important detail for streaming products where audio inconsistency is a CSAT-killer.',
        'Transcripts are first-class. Every uploaded video gets a <a href="https://openai.com/research/whisper" rel="noopener noreferrer">Whisper</a>-powered transcript by default, available as VTT, SRT, and a timed-segment JSON shape. The transcript completes asynchronously and triggers a `transcript.ready` webhook the moment it is available. The transcript backend is configurable — customers who need a specific ASR model (compliance reasons, a language Whisper covers poorly, a fine-tuned vertical model) can wire a custom backend behind the same API surface. The default is good for most teams; the escape hatch is there for the teams that need it.',
        'Server-side clipping is one of the most underrated features in the pipeline. The clip endpoint takes a source video, a start time, an end time, and returns a brand-new asset that goes through the same pipeline as a fresh upload — its own HLS ladder, its own transcript, its own playback URL. For teams shipping highlight reels, social cuts, or multimodal-AI-driven extraction workflows (an emerging use case as multimodal models are used to identify "the interesting bit" of a longer recording), the clip endpoint turns a custom ffmpeg pipeline into a one-call workflow.',
        'Playback security uses short-lived signed tokens. Public playback works the way you would expect for non-restricted content; signed playback issues a JWT-shaped token with configurable TTL, rotating secrets, and a revoke surface for compromised tokens. The hosted player handles the refresh dance transparently; teams using their own player get the token primitives and write the refresh themselves. The model is the one production paid-content workflows have converged on.',
      ],
    },
    {
      h2: 'The CDN: pull zones, storage zones, and granular purge',
      paragraphs: [
        'The delivery layer is what separates Ollanode from the pipeline-only vendors in the category. Mux ships a CDN, but the depth of the CDN surface (purge, signed URLs, edge rules, analytics) is shallower than what teams running production streaming at scale actually need. Cloudflare Stream rides Cloudflare\'s own CDN at depth but is opinionated about how content is served and limits configurability. Ollanode\'s CDN is built as a first-class layer, configurable, observable, and tightly integrated with the pipeline above it and the edge compute below it.',
        'Pull zones are the primary CDN object. A pull zone maps a hostname — your `cdn.you.com` — to either an arbitrary upstream URL or a managed storage zone. The TTL is configurable per zone, the cache-bypass prefix list lets you exempt dynamic paths from caching without inventing a separate non-cached hostname, and CORS is handled at the edge so the origin never sees the preflight. The pull zone is the unit a team configures, monitors, and bills against.',
        'Purge is where the team has invested most. Instant whole-zone purge runs in milliseconds across the platform\'s edge fleet. Path-level purge takes an explicit list and clears just those paths, also in milliseconds. The granularity matters because teams shipping personalised video or signed paid content cannot afford to purge the whole cache every time a single asset changes — the cache-miss storm against the origin would be catastrophic. The granular purge is the difference between a CDN you can operate at scale and one you cannot.',
        'Hotlink protection uses HMAC-signed URLs with rotatable secrets. For paid-content workflows, the player receives a short-lived URL that the cache will serve and that other origins cannot replay. For non-paid workflows, the same primitive serves as a hotlink-prevention measure against scrapers. Signing is deterministic, verification is at the edge, and the origin only sees requests for content that has already been authorised.',
        'Storage zones are S3-style buckets with presigned uploads, CDN-fronted by default. The canonical pattern is to put a storage zone behind a pull zone: the customer uploads via presigned PUT, the storage zone holds the bytes, the pull zone serves the cached version at the edge. Live edge analytics expose requests, egress and cache-hit ratio per zone in the dashboard, real-time, with drill-downs by status code and origin response time.',
      ],
      pullQuote: 'Granular path-level purge in milliseconds is the difference between a CDN you can operate at scale and one you cannot.',
    },
    {
      h2: 'Edge compute included, not bolted on',
      paragraphs: [
        'The thing the platform ships that the obvious alternatives do not is a first-class edge-compute layer integrated with the CDN. Edge compute in the video-and-CDN category is usually an add-on, usually with a separate billing surface, usually with cold-start latency that makes the obvious use cases — auth wrapping, A/B routing — feel painful. <a href="https://ollanode.com/">Ollanode</a> ships edge compute as a first-class layer with V8 isolates as the execution model, which sidesteps the cold-start problem because there are no containers to start.',
        'The handler shape is standard `Deno.serve(handler)`. A handler is a JavaScript function. Push the code and the platform deploys it within seconds, invokable at `/__fn/<id>` from anywhere on the internet. The same handler can be wired into the pull-zone request lifecycle as a request-rewrite hook, sitting between the inbound client request and the cache lookup, which is where the most operationally-valuable use cases live.',
        'Authentication is the canonical first use case. A handler can inspect the inbound request, verify a customer-issued JWT, look up entitlements in the customer\'s identity provider (the handler can call out to any HTTP endpoint), and either let the request through to the cache or return a 401 — all at the edge, with no origin round-trip. The latency overhead is in the low single-digit milliseconds because the isolate is already warm.',
        'A/B routing is the second canonical use case. The handler reads a customer identifier from a cookie or a header, hashes it into a treatment bucket, and rewrites the cache key to serve different content per bucket. The cache hits are still cache hits — they just hit different cached objects depending on bucket. Geo-routing for regulatory content rules — serving a different cut of a video in certain jurisdictions, or blocking access in others — is the same pattern with a different routing function. Header rewriting handles the compatibility-shim use cases.',
        'Per-project isolation is structural. Code from one project cannot read state, cache or storage belonging to another. The isolates are sandboxed at the platform level. Metering is per-project and per-invocation, exposed in the dashboard alongside the other usage analytics. The control plane handles the deploy, the versioning, the rollback, and the audit-logging of every code change.',
      ],
    },
    {
      h2: 'API-first developer experience',
      paragraphs: [
        'The platform is API-first, not dashboard-first. The dashboard exists, it is well-designed, and it covers the operational surfaces a developer needs to monitor the platform without leaving the browser. But every feature on the dashboard is reachable through a documented REST endpoint, scoped per project, with consistent request and response shapes across the 60+ endpoints in the surface. A workflow you can do through the dashboard is a workflow you can automate through the API.',
        'The API conventions are conventional in a deliberate way. Bearer-token authentication. Project-scoped resources under `/v1/<resource>`. POST to create, GET to read, PATCH to update, DELETE to remove. Webhook payloads are JSON with a shared envelope shape, HMAC-signed for verification, and retried with exponential backoff on customer-side failure. The conventions are boring on purpose: every team that has written a REST integration before can integrate with the platform without learning a vendor-specific paradigm.',
        'The published API reference covers all 60+ endpoints with example requests in curl, Python, JavaScript, and several other languages. The OpenAPI specification is available for download and is the source of truth for the SDK clients the team ships and for the OpenAPI-derived clients customers can generate themselves. The Postman collection is published. The platform behaves the way an API-first product from a developer-tools-savvy team should behave, because that is what the parent team builds for a living across the rest of the portfolio.',
        'For teams that want infrastructure-as-code, the most-used resources — projects, zones, storage buckets, edge functions — are exposed through a published Terraform provider. The provider is the canonical path for teams whose deployment discipline includes "the platform is provisioned by the same Terraform run that provisions the rest of the cloud account."',
      ],
    },
    {
      h2: 'Pricing: predictable, published, no per-minute surprises',
      paragraphs: [
        'The pricing surface is one of the places the platform differentiates most cleanly from the established hosted alternatives in the category. The principle is straightforward: the cost model the customer signed up for at the prototyping stage should still describe the bill at the production stage. Mux\'s per-minute-encoding plus per-minute-streaming plus per-gigabyte-egress model has the structural property that the bill grows in three dimensions at once and surprises every team that scales successfully. The platform\'s model is structured around sensible monthly tiers with bundled inclusive volumes — encoding minutes, storage gigabytes, streaming bandwidth, edge-function invocations — that cover the median workload, with overage rates that are published, predictable, and on the lower end of the category.',
        'The free tier is generous enough to evaluate the platform on real workloads. New signups get a free monthly allowance of encoding minutes, storage, and bandwidth that is sized to let a team upload several hours of video, transcode them through the full pipeline, generate transcripts, run them through the CDN, and exercise the edge-compute layer — all without entering a credit card. The principle is consistent with the rest of the Ollasoftware portfolio: any platform whose value is only legible after a contract negotiation is not as valuable as it claims.',
        'The paid tiers move up in roughly the cost-per-unit structure customers expect: more bundled volume per dollar at higher tiers, lower overage rates at higher tiers, with the operational primitives — RBAC, audit logs, the SLA — added at the enterprise tier rather than at the early tiers where they are unnecessary overhead. The honest framing is that the platform is meaningfully cheaper than Mux at every comparable volume, broadly competitive with Cloudflare Stream on raw bandwidth and meaningfully deeper than Stream on feature surface, and priced above the rock-bottom-cost specialist vendors at a level that reflects the depth of the platform.',
        'For enterprise tiers — the customers who need SCIM, SAML, dedicated regions, fine-grained RBAC, audit logs streaming to a SIEM, and a contractual SLA — the pricing shifts to a volume contract with predictable monthly minimums. The same data-handling guarantees that apply to the free tier apply to enterprise: the dashboard and the audit log are the canonical source of truth, the platform meters what it bills, and the customer can reconcile the invoice line by line.',
      ],
    },
    {
      h2: 'Who Ollanode is for',
      paragraphs: [
        'The customer profiles the platform fits well are concrete enough to enumerate. Streaming product teams — D2C video products, niche subscription streaming services, video-heavy community products — who want the depth of Mux without the bill of Mux. Learning platforms shipping course content at scale where the per-student streaming volume is high and the unit economics need to work. Social and UGC products that handle user-uploaded video and need the full pipeline running at production reliability.',
        'Multimodal-AI product teams that are starting to use video as a first-class input — clip extraction, frame-level inference, transcript-driven retrieval. The clip endpoint and the configurable transcript backend fit these workflows naturally; the alternative is gluing together ffmpeg, an ASR vendor, and a CDN by hand, which is a multi-month engineering investment most teams cannot justify.',
        'Internal-use teams shipping product demos, onboarding videos, support recordings, training videos, customer-uploaded support clips — workloads where the volume is real but the case for a premium-priced hosted vendor was never strong. The cost saving here is often not the headline reason; the operational depth is.',
        'Indian and India-adjacent product teams shipping video to a domestic audience, where the cost discipline that defines the broader Ollasoftware posture matters more than the specific feature gap on a marquee American-frontier vendor. The platform is built and priced with this customer in mind; the broader global customer base benefits from the same cost discipline as a side effect.',
        'The customer profile the platform fits less well is the very-large enterprise that has standardised on Mux through a multi-year contract and a deep set of integrations the team would have to rebuild. Migration in that case is a real cost. The platform is the right answer for teams that have not yet made the Mux commitment, or for teams whose Mux contract is up for renewal and looks like it will scale uncomfortably for the next year of growth. For the rest, the conversation is more nuanced and starts with the team\'s actual workload rather than with the marketing pitch.',
      ],
    },
    {
      h2: 'How Ollanode compares to the established vendors',
      paragraphs: [
        'The hosted video category has a small number of credible vendors and it is worth being direct about where the platform sits.',
        'Mux is the polished, well-engineered, well-supported, expensive option. The feature set the platform matches is the working subset of Mux that production customers actually use — the HLS ladder, the transcripts, the storyboards, the signed playback, the hosted player, the API-first developer experience. Where Mux extends past the platform is the breadth of integrations with adjacent SaaS, the depth of the analytics surface, and the maturity of the SLA and support tier for very large customers. Where the platform extends past Mux is the integrated edge-compute layer, the more honest pricing structure, and a feature-for-feature offering that is meaningfully cheaper at every comparable volume. The honest framing is that Mux is the right choice when operational simplicity dominates and budget is not a constraint; <a href="https://ollanode.com/">Ollanode</a> is the right choice everywhere else.',
        'Cloudflare Stream is the high-scale alternative. Stream is cheap at the upper volume curve, runs on Cloudflare\'s own network, and is operationally simple. It is also tightly bound to the rest of the Cloudflare ecosystem, opinionated about how content is served, and offers less feature depth in the pipeline than either Mux or the platform — transcripts arrived recently, server-side clipping is limited, the player surface is narrower, and the configurability of the CDN layer is constrained by Cloudflare\'s own product priorities. For teams already deep in Cloudflare, Stream is reasonable; for teams who want more pipeline depth, more CDN configurability, or both, the platform is the alternative that compares favourably.',
        'Bunny Stream is the smaller-vendor comparison. Bunny has very competitive unit economics at the volume tier, a reasonable feature surface, and an honest approach to pricing. The platform\'s extension over Bunny is in the depth of the pipeline (Whisper transcripts as a default rather than an add-on, server-side clipping, the included edge-compute layer) and in the integrated operational surface (RBAC, audit logs, edge analytics). For teams who chose Bunny mostly for cost, the platform delivers a competitive cost posture with a meaningfully deeper feature set.',
        'Cloudinary, AWS MediaConvert + CloudFront, Wowza, Bitmovin, and the various component-level vendors are different shapes of bet. They are appropriate when the team genuinely wants to assemble the pipeline from parts. The platform\'s value over those is the integration work the team has done so the customer does not have to: the same engineering hours that would be spent wiring MediaConvert pipelines and CloudFront configs are spent shipping product instead.',
        'Across all of these, the question is not "which platform is cheapest per minute or per gigabyte." It is "for the video workload my team is actually building, what is the total cost of ownership — including the engineering cost of integration, the operational cost of running on a fragmented stack, and the unit cost of the bill itself — compared to a single hosted platform that handles the whole surface." For most product teams in the series-A-to-mid-market range, the answer points clearly at the platform.',
      ],
    },
    {
      h2: 'The team and the operational heritage',
      paragraphs: [
        'Ollanode is built and operated by <a href="https://ollasoftware.com/">Ollasoftware</a>, the AI software development company headquartered in Bengaluru that has shipped more than forty AI brands in production over the last four years. The infrastructure heritage is dense for a video product. The CDN layer was built by the team that runs <a href="https://ollasoftware.com/blog/crawlcrawl/">Crawlcrawl</a> (billions of pages a month, hundreds of millions of cache hits a day). The control-plane discipline — webhooks, audit logs, scoped API keys — is shared with <a href="https://ollasoftware.com/blog/ollastack/">Ollastack</a> (the agent-first form and mailbox backend). Developers who need tunnel access for local testing against Ollanode webhooks can pair it with <a href="https://ollasoftware.com/blog/21tunnel/">21tunnel</a> (AI-agent tunnel with master-key delegation). Observability for the video pipeline is wired through <a href="https://ollasoftware.com/blog/24observe/">24observe</a>.',
        'The video-pipeline expertise came from a different and unusual source. The parent group, <a href="https://www.networkershome.com/" rel="noopener">Networkers Home</a>, has been running a course-content production and delivery operation at meaningful scale since 2007 — currently delivering training video to a population of forty-five-thousand-plus alumni and an active student body across cybersecurity and networking certifications. The pipeline-engineering instincts behind the video layer are anchored on real operational experience at running a streaming service whose costs the founders care about, on a content catalogue whose value the founders understand, for customers whose experience the founders have to honour. The design choices in the platform reflect what the team has had to ship for its own learning operation, not what looks good in a vendor comparison.',
        'That operational heritage is the answer to the implicit question any team evaluating a new hosted platform asks: who is going to be running this in five years. The platform is built by a team that already runs production AI and content infrastructure at scale, inside a company that has been operational for the better part of two decades, with a customer base inside the parent group that gives the team a permanent stake in the platform behaving well. The platform is not a venture-funded sprint to acquisition; it is a product the parent team intends to ship indefinitely.',
      ],
    },
    {
      h2: 'What is on the roadmap',
      paragraphs: [
        'The team publishes a roadmap on the docs site and ships a changelog against it on a regular cadence. The visible near-term threads are: expanded regional pool coverage so latency is competitive globally rather than only on the routes the platform already serves well, deeper integration with the analytics-and-business-intelligence stack streaming product teams already run (Segment, Mixpanel, Amplitude, Snowflake) so view-level data flows automatically rather than through customer-built ETL, a richer hosted player for teams that use it as their default (chapter UI, transcript-driven search, configurable controls, brandable theming), and an expanded webhook event catalogue for the operational events teams currently have to poll for.',
        'Underneath those visible features is steady investment in the codec frontier. The current default is H.264 + AAC for compatibility reasons; the platform supports HEVC and AV1 for projects that opt in, and the trajectory is toward HEVC and AV1 being viable defaults as device support compounds. The team has been explicit that the transition will be opt-in for some time — the operational rule "the default codec is the one that plays everywhere" is the right rule for most teams and the platform will not break it without explicit customer choice.',
        'On the edge-compute layer, the roadmap thread is around expanded standard-library APIs in the isolate runtime — particularly the Web Crypto APIs, the WebSocket APIs, and the streaming-response APIs that production edge workloads increasingly need. The current surface is sufficient for the canonical use cases (auth wrapping, A/B routing, request rewriting); the expansion targets the workloads emerging at the intersection of video and AI inference at the edge.',
        'Pricing during the current phase is the published tier model with the generous free signup allowance. The team has signalled that the unit economics will not get more expensive over time — they will get cheaper as the underlying infrastructure cost compounds down and the savings are passed through. The principle is consistent with the rest of the portfolio: a platform whose pricing only goes up loses customers as fast as it adds them.',
      ],
    },
    {
      h2: 'How to start',
      paragraphs: [
        'If you ship video at any meaningful volume and your current invoice from Mux, Cloudflare Stream or one of the equivalent vendors has become a line item you would rather not be paying, the right next move is to evaluate the platform on a real workload rather than on a synthetic benchmark. Sign up at <a href="https://ollanode.com/">ollanode.com</a>, create a project, upload a representative video, run a representative streaming session against the resulting playback URL, and look at how the platform handles your specific shape of workload.',
        'The signup flow is sixty seconds. No credit card. The free tier covers enough encoding minutes, storage and bandwidth to run the kind of evaluation that gives you real information — not just "the upload worked," but "the transcription quality is acceptable, the streaming latency is what we need, the edge function does what we need it to do, the dashboard tells us what we need to know."',
        'Run the platform on real customer traffic for a few days before drawing any conclusion. The numbers that matter — first-byte latency at the edge, cache hit ratio, transcript quality, overall unit cost — only become legible after the platform has had enough traffic to calibrate. The trajectory matters more than the snapshot, and the trajectory on the platform tends to compound favourably as the regional pools warm up to your traffic pattern.',
        'If you would like the team to walk you through a specific workload — high-volume streaming evaluation, edge-compute use case design, an enterprise procurement conversation, or a migration plan from an existing hosted vendor — the <a href="https://ollasoftware.com/contact/">Ollasoftware contact page</a> reaches the engineers who ship the platform. Response times are unusually fast for the B2B-video category, which the team treats as one of the small operational signals that the product takes itself seriously.',
        'And if you are not yet sure the platform is the right answer — if you are still triangulating between vendors, or still deciding whether a single-platform consolidation is the right priority for your team this quarter — the published documentation, the live dashboard demo, the OpenAPI specification, and the changelog are all open. The platform\'s case is most legible when measured against your own workload; the docs and the free signup are the team\'s way of inviting that measurement directly.',
      ],
    },
  ],
  faqs: [
    {
      q: 'What is Ollanode?',
      a: 'Ollanode is a fully hosted, cloud-operated platform for video, CDN, storage and edge compute. Sign up, get an API key, ship — there is nothing to install and no infrastructure to provision. Four composable primitives (video, delivery, edge compute, control plane) across eight microservices and 60+ REST endpoints, all operated by Ollasoftware.',
    },
    {
      q: 'How does Ollanode pricing work?',
      a: 'Predictable monthly tiers with bundled inclusive volumes for encoding, storage, bandwidth, and edge-function invocations. Overage rates are published and on the lower end of the category. The free tier covers enough usage to evaluate the platform on a real workload without a credit card. Enterprise tiers shift to volume contracts with predictable monthly minimums, SCIM, SAML, RBAC, audit-log streaming to a SIEM, and a contractual SLA.',
    },
    {
      q: 'What does the video pipeline support?',
      a: 'Direct upload, resumable multipart and pull-from-URL ingest; adaptive HLS ladder with H.264 + AAC defaults and configurable presets (180p through 4K, opt-in HEVC and AV1); MP4 renditions; loudness normalisation; poster frames and storyboard sprite sheets with storyboard.vtt; Whisper-powered transcripts in VTT, SRT and timed-segment JSON with a pluggable ASR backend; multi-language WebVTT subtitles and chapter markers; server-side clipping that produces a new asset; signed or public playback with short-lived rotating tokens; a drop-in iframe hosted player.',
    },
    {
      q: 'What does the CDN support?',
      a: 'Pull zones mapping any hostname to an origin or storage zone; per-zone TTL and cache-bypass prefixes; instant whole-zone and path-level purge in milliseconds; HMAC-signed URLs with rotatable secrets; CORS handled at the edge; S3-style storage zones with presigned uploads, CDN-fronted by default; ordered edge rules for header manipulation, redirect or block; live edge analytics for requests, egress and cache-hit ratio per zone.',
    },
    {
      q: 'How does the edge compute layer work?',
      a: 'V8 isolates execute JavaScript handlers written as Deno.serve(handler). No containers, no cold starts. Push code, invoke at /__fn/<id> within seconds, or wire the handler into the pull-zone request lifecycle for auth, A/B and geo-routing. Per-project isolation; per-invocation metering; audit-logged code changes. Included in every tier, not sold as a separate add-on.',
    },
    {
      q: 'How does Ollanode compare to Mux and Cloudflare Stream?',
      a: 'Mux is the polished, expensive option; Ollanode matches its working feature set at a meaningfully lower price and ships an included edge-compute layer Mux does not. Cloudflare Stream is cheaper at upper volumes but tightly bound to the Cloudflare ecosystem and shallower on pipeline features; Ollanode delivers deeper pipeline depth and CDN configurability at competitive economics. For most product teams in the series-A-to-mid-market range, Ollanode is the right answer when total cost of ownership, including engineering and operational overhead, is the comparison.',
    },
    {
      q: 'Do I need to bring my own infrastructure?',
      a: 'No. Ollanode is a fully hosted platform — the mental model is closest to NextDNS for the video-and-CDN category. Sign up at ollanode.com, get an account, use the APIs. The platform runs on Ollasoftware\'s own infrastructure across regional pools that serve global traffic. There is nothing for the customer to install, no cloud account of yours to wire up, no infrastructure decision to make.',
    },
    {
      q: 'Who is behind Ollanode?',
      a: 'Ollanode is built and operated by Ollasoftware, the Bengaluru-headquartered AI software development company. The CDN engineering inherits from the team that runs Crawlcrawl\'s high-volume crawler infrastructure; the control-plane discipline is shared with Aeoniti; the edge-compute layer comes from the Switchllm team. The video-pipeline instincts are anchored on the streaming operation Networkers Home — Ollasoftware\'s parent group — has run since 2007 across 45,000+ alumni and the active student body.',
    },
  ],
};
