import type { BlogPost } from './types';

// 24observe — 5,000+ word brand piece. Grounded against live 24observe.com
// on 2026-06-26 (uptime + logs + SIEM + agent API on a knowledge graph,
// AI NOC + SOC analyst that walks the graph and returns evidence-cited
// verdicts, 16 entity types / 16 relationship types, 50 detections across
// 10 packs, 7 check types, AI-agent observability + security as a new
// pitch, OpenTelemetry-native, pre-built MCP server and OpenAI/Anthropic/
// LangChain tool definitions, 24 narrow PAT scopes, Free 1GB/Startup 10GB/
// Pro 100GB plans).
//
// FRAMING: brand site says "self-hostable" / "Self-host / air-gapped" —
// per founder rule (feedback_ollasoftware_all_cloud_never_self_hosted)
// the blog describes 24observe as cloud SaaS only and never mentions
// self-host. The cloud product is real and complete; the blog focuses on
// it.
//
// Anchor distribution target: 6-8 to 24observe.com, 2-3 to ollasoftware.com
// (parent), 1-2 to networkershome.com (group).

export const twentyfourobservePost: BlogPost = {
  slug: '24observe',
  brand: '24observe',
  brandDomain: '24observe.com',
  brandTagline: 'Uptime, logs, and security on an API your AI agent can drive',
  category: 'ai',
  title: '24observe — the AI NOC + SOC analyst that replaces four observability vendors',
  metaDescription: '24observe is a cloud observability and security platform that collapses uptime monitoring, log management, SIEM detections and an agent-driveable API into one product. An AI analyst walks the knowledge graph of your services, hosts, identities and agents to deliver evidence-cited verdicts in seconds. 50 detections, 7 check types, OpenTelemetry-native, MCP built in.',
  heroEyebrow: 'Brand deep-dive · observability + security',
  heroH1: '24observe: uptime, logs, SIEM and an agent API — on one knowledge graph.',
  heroSub: 'A 5,000-word deep dive into 24observe, the AI NOC and SOC analyst from Ollasoftware that reasons over your operational knowledge graph instead of your alert queue. Four observability vendors collapsed into one product, on an API your AI agent can drive end to end.',
  publishedOn: '2026-06-26',
  lastUpdated: '2026-06-26',
  readingTimeMin: 22,
  wordCount: 5210,
  tldr: [
    '24observe is a cloud observability and security platform that collapses what most teams currently buy from four separate vendors — uptime monitoring, log management, SIEM, and an agent-callable API — into one product with one bill, one API, and one incident pipeline.',
    'The differentiator is the operational knowledge graph: 16 entity types (services, hosts, devices, identities, agents) and 16 relationship types (owns, runs_on, impacts, matched, raised) that an AI analyst walks during an incident to produce evidence-cited verdicts — root cause and the fix — in seconds rather than minutes.',
    'Uptime depth covers seven check types (HTTP/HTTPS, TCP, SSL/TLS cert, ICMP, port, keyword, heartbeat/cron) with multi-region probes, SLO targets, and status pages with custom domains. The Pingdom / UptimeRobot / BetterStack surface, full-fat.',
    'SIEM ships 50 detections across 10 packs (most MITRE ATT&CK-tagged), multi-event correlation, inline threat-intel matching on every source IP, and detection rules that open incidents in the same pipeline as a failed health check — no parallel "security console."',
    'AI-agent observability + security is the newest layer: OpenTelemetry GenAI spans show cost, latency and error rate per agent and per model, while detection rules flag prompt injection, runaway tool loops and sensitive tool calls into the same incident pipeline.',
    'The API surface is built for agents from the start — pre-converted tool definitions for OpenAI, Anthropic and LangChain, a native MCP server, signed event webhooks instead of polling, rate-limit headers your agent reads to back off, Idempotency-Key on every mutation, and 24 narrow PAT scopes with per-key daily caps.',
  ],
  sections: [
    {
      h2: 'The setup: every team has the same four-vendor observability stack',
      paragraphs: [
        'There is a piece of operational infrastructure that almost every serious software team has built — usually accidentally, over the course of two or three years — and that almost every team would rebuild differently if they could start over. The shape of it is universal. There is an uptime monitor, usually Pingdom or UptimeRobot at the small-team tier and Datadog Synthetics or BetterStack at the medium tier, watching the public surfaces of the product. There is a log platform, usually Datadog Logs or Splunk or one of the cheaper alternatives, ingesting and searching the structured output of every running service. There is a SIEM, sometimes the same vendor with a "security tier" upsell, sometimes a separate product entirely, watching for the threats and the suspicious patterns that the engineering team would not catch on their own. And there is some kind of SDK or integration layer that the engineering team has wired up, on top of all three of those, to make the observability state queryable from a single place.',
        'The four-vendor stack is what teams arrive at because no single vendor offered all of it well at the time the team first needed each piece. The uptime monitor was bought first because the product was down and the team needed something cheap and fast. The log platform was bought next because someone discovered a production bug at 3am and there was no way to investigate it. The SIEM was bought third because compliance or a security incident forced the question. The SDK layer was added fourth because the engineering team realised that none of the previous three vendors were composable with each other.',
        'The cost of that stack at maturity is meaningful. Four billing relationships, four sets of keys to rotate, four dashboards to learn, four sets of alert configurations to keep in sync, four definitions of "what counts as an incident" that never quite agree. The operational team learns to operate the stack rather than learn to operate the product the stack is supposed to support. The MTTR for a production incident is dominated by the time the team spends correlating data across the four vendors. The MTTR for a security incident is dominated by the same problem with a slightly different cast.',
        'The AI-agent era has added a fifth dimension that none of the four existing vendors handle well today. Production AI agents — the ones that have crossed over from internal experiments into customer-facing workloads — are real production traffic now. They spend tokens. They call tools. They touch real customer data. They generate the same operational and security signal that a microservice generates, and they generate a few new categories of signal that no microservice has ever generated. The existing four-vendor stack mostly does not see them at all.',
        '<a href="https://24observe.com/">24observe</a> exists because the founders watched their own engineering and security teams — and a growing crowd of small-to-mid-market product teams across India and beyond — build the same four-vendor stack out of necessity, suffer the same operational drag from running it, and then have to bolt a fifth vendor on top to handle AI agents. The bet was simple: ship the four collapsed into one product, on a knowledge graph an AI analyst can walk, with the agent observability and security layer present from day one rather than added as a fifth.',
      ],
    },
    {
      h2: 'What 24observe actually is, in one paragraph and then in detail',
      paragraphs: [
        '24observe is a cloud-operated observability and security platform that runs as a managed SaaS service. The mental model is closest to "Datadog plus Splunk plus PagerDuty plus a SIEM, on one bill, behind one API." You sign up at the dashboard, you point your telemetry pipelines at the platform, and the system handles ingestion, correlation, detection, alerting, incident management, status-page surfacing, and the AI-analyst layer that walks the knowledge graph on top of it all. There is nothing to install on the platform side; the product runs on Ollasoftware\'s own infrastructure as a hosted service like the rest of the portfolio.',
        'Inside the product there are five composable surfaces. The uptime layer covers seven check types — HTTP/HTTPS, TCP, SSL/TLS certificates, ICMP ping, port probe, keyword match, and inverted heartbeat-or-cron checks — across multi-region probes, with SLO targets and status pages that can ride custom domains. The log management layer ingests structured logs from twelve common sources, indexes them for fast search by typing the words you remember rather than by learning a proprietary query language, auto-extracts facets for filtering, supports live-tail of new events, and collapses recurring stack traces into single rows with first-seen and last-seen counts. The SIEM layer ships 50 detection rules across 10 packs — access, exfiltration, secrets, web attacks, reliability, threat intelligence, AI-agent security, MCP traffic, and AWS control-plane — with multi-event correlation, inline threat-intel matching on every source IP at ingest, and detection rules that open incidents in the same pipeline as a failed health check rather than in a parallel security console. The AI-agent observability and security layer reads <a href="https://opentelemetry.io/" rel="noopener noreferrer">OpenTelemetry</a> GenAI spans and surfaces cost, latency and error rate per agent and per model, plus detection rules for prompt injection, runaway tool loops and sensitive tool calls. The agent-API layer wraps all of it with pre-converted tool definitions for OpenAI, Anthropic and LangChain, a native MCP server, signed event webhooks, rate-limit headers, idempotency keys, and twenty-four narrow personal-access-token scopes with per-key daily caps.',
        'Operationally, the platform is built on the operational knowledge graph that ties all five surfaces together. Every entity in the customer\'s environment — services, hosts, devices, identities, AI agents, monitors, cases, incidents — is a node in the graph; every relationship — owns, runs_on, impacts, matched, raised — is an edge. When an incident fires, the AI analyst walks the graph from the symptom backward, blames the change, confirms with the metrics, and returns an evidence-cited verdict — root cause and the fix — in seconds rather than the minutes or hours an on-call engineer would spend doing the same walk by hand.',
        'Competitively, the platform sits in a specific place that the established vendors do not occupy. It is not trying to displace Datadog at the Fortune-500 SRE tier (Datadog has spent more than a decade building the depth and the ecosystem that customer base requires). It is not trying to displace Splunk in the very-large-enterprise SIEM market (Splunk\'s install base and procurement gravity are real). It is trying to be the right answer for the engineering and security teams below the Fortune-500 tier — series-A to mid-market — who currently run the four-vendor stack because no single vendor offered all of it well, and who would prefer one product, one API, one incident pipeline, and one bill if it were available at acceptable depth.',
      ],
    },
    {
      h2: 'The four-into-one collapse, and what each layer actually ships',
      paragraphs: [
        'The collapse is the most important architectural property of the platform. It is the thing that makes the AI-analyst layer possible, the thing that makes the API surface coherent, and the thing that makes the unit economics work in favour of the buyer rather than the vendor.',
        'The uptime layer is the gateway product for most teams. Pingdom, UptimeRobot, BetterStack and the equivalent vendors all do the basic surface well — HTTP probes, TCP probes, SSL certificate expiry alerts, ICMP ping reachability. <a href="https://24observe.com/">24observe</a> matches that surface and extends it with the two check types most uptime vendors charge separately for: keyword match (does the page still say "Order placed" or is the 200 just a generic landing page), and inverted heartbeat or cron checks (the customer\'s job pings the platform on its expected interval, and if the silence exceeds the configured window the platform opens an incident automatically). Multi-region probes are standard. SLO targets convert raw uptime into business-grade availability metrics. Status pages with custom domains let the customer surface incidents to their own customers without buying a separate status-page vendor.',
        'The logs layer is the workhorse product for most teams once they get past the prototyping stage. Ingest is deliberately permissive — twelve common sources covering AWS Lambda (through CloudWatch), Heroku (through log drains), Vercel (through the dashboard integration), Docker (through the syslog driver), systemd (through journald), any OpenTelemetry SDK, Vector and Fluent Bit pipelines, or just a raw `curl` of structured JSON straight to a URL. Search is the un-feature: there is no SPL, no proprietary DSL, no query language to learn. Type the words you remember. Filters compose with the obvious `service:checkout AND level:error` syntax. Auto-extracted facets appear on the side; click a value, drill in. Live-tail watches new events as they land. Pattern grouping collapses ten thousand similar log lines into one row showing the shape that matters. Recurring stack traces collapse into a single error-tracking row with first-seen, last-seen, sample, and a count — the thing Sentry charges separately for, here on the same bill.',
        'The SIEM layer is the security half of the platform. Fifty detection rules across ten packs cover the common ground that almost every security team eventually configures by hand: access (failed logins, privilege escalations, credential stuffing patterns), exfiltration (unusual outbound volume, suspicious destinations), secrets (token leaks in logs, environment variable exposure), web attacks (SQL injection patterns, XSS attempts, path traversal), reliability (sudden error-rate spikes, dependency failures), threat intelligence (known-bad IPs, Tor exits, datacenter ranges), AI-agent security (prompt injection, runaway tool loops), MCP traffic (anomalous tool calls), AWS control plane (suspicious IAM activity), and a tenth pack for the less-common but still important patterns. Most rules carry their MITRE ATT&CK technique tag. Multi-event correlation handles the patterns a single log line cannot express — failed-login-then-success sequences, single-IP-touching-many-accounts cardinality patterns — and runs every minute against the event stream. Threat-intel matching runs inline at ingest, so the bad-IP context is already on the event by the time a detection rule looks at it.',
        'The agent-API layer is the thing that ties the other three together and makes the platform usable as the substrate an AI agent operates against. It is the topic of its own section below; the short version is that every endpoint on the platform is also available as a pre-converted tool definition for OpenAI, Anthropic and LangChain, plus a native MCP server, with the scoping and rate-limiting discipline an autonomous agent workload requires.',
      ],
    },
    {
      h2: 'The operational knowledge graph and the AI analyst that walks it',
      paragraphs: [
        'The knowledge graph is the architectural decision that distinguishes the platform most clearly from the established alert-queue vendors. Every incident on the platform — whether it is a security alert or an availability outage — lands in a live graph of sixteen entity types and sixteen relationship types. Services own each other. Hosts run instances of services. Devices live on networks. Identities authenticate against services. AI agents call tools. Monitors raise cases. Incidents impact services. The graph is dense, typed, and queryable in both directions.',
        'When an incident fires, the AI analyst walks the graph from the symptom outward. It starts at the impacted entity — the service that returned a 500, the agent that exceeded a token budget, the identity that triggered the suspicious-login detection — and traces the relationships in both directions: what does this entity depend on, what depends on this entity, what changed recently in either direction, what is the blast radius of the symptom. The walk is fast because the graph is in memory and the entity count is bounded by the customer\'s actual environment rather than by an abstract universe of possibilities.',
        'The output of the walk is an evidence-cited verdict. The analyst produces a one-paragraph root-cause hypothesis, identifies the most likely change (a deploy, a configuration update, an identity-grant change, an upstream dependency outage) that triggered the symptom, confirms the hypothesis against the metrics and the logs from the relevant entities, and recommends a fix. Every claim in the verdict cites the evidence — the specific log line, the specific metric reading, the specific recent change — that supports it. The on-call engineer reading the verdict can verify the analyst\'s reasoning rather than trust the verdict as a black-box assertion.',
        'For incidents the analyst cannot resolve confidently — the verdict carries a confidence score, and below a customer-configurable threshold the analyst escalates rather than concludes — the human engineer inheriting the case gets the analyst\'s partial walk, the entities the analyst considered, the relationships the analyst followed, and the specific points at which the analyst lost confidence. The handoff is the same shape as a strong junior engineer briefing a senior engineer mid-investigation: here is what I have looked at, here is where I am stuck, here is what I think is most likely. The handoff quality is the thing that makes the analyst usable in production rather than a research demo.',
      ],
      pullQuote: 'Every claim in the verdict cites the evidence — the specific log line, the specific metric reading, the specific recent change — that supports it.',
    },
    {
      h2: 'Uptime monitoring depth: seven check types covering the things stacks actually break on',
      paragraphs: [
        'The uptime layer is where most teams meet the platform first, and it is the layer where the team has invested the most engineering against a published roadmap of "every real thing your stack breaks at." Seven check types cover the common cases comprehensively.',
        'HTTP and HTTPS checks verify status codes, measure response time, and flag degradation before a full outage by tracking the response-time distribution against a configurable baseline. The check supports configurable headers, request bodies, expected response patterns, and follow-redirect behaviour for the cases where a 200 from a redirect is not the same as a 200 from the real surface.',
        'TCP and port checks handle the reachable-or-not question for databases, message queues, internal APIs, and anything else that speaks TCP but does not have an HTTP surface. The port-probe variant handles the specific case where the URL format does not include the port and the customer wants the check to specify it explicitly.',
        'SSL and TLS certificate checks are the under-rated category. The check warns the operator seven days before certificate expiry — early enough that the renewal can happen in business hours, late enough that the warning is actionable. The check validates the full certificate chain, not just the leaf, and surfaces the case where a 200 OK on HTTPS is hiding a broken intermediate. For teams whose biggest production incidents have come from expired certificates that nobody was watching, this primitive alone is worth the subscription.',
        'ICMP ping checks handle the classic reachability question — is the network path to this host alive — from inside the customer\'s network or from the platform\'s own probes. The check is the right primitive for monitoring infrastructure inside a private network when paired with the platform\'s collector agent.',
        'Keyword match checks answer the second-order availability question. The page returns 200, but does the page still say "Order placed" or has it silently degraded to a generic landing page because of a deployment that broke the checkout flow without breaking the HTTP surface. Most teams have at least one production incident in their history where the answer was the wrong one and the uptime monitor said everything was fine. The keyword check is the primitive that catches it.',
        'Heartbeat and cron checks are the inverted shape — instead of the platform polling the customer, the customer\'s job pings the platform on its expected interval. If the platform sees silence past the configured window, an incident opens automatically; the next ping closes it. The primitive is what catches the production cron job that has been broken for three weeks without anyone noticing because the cron was supposed to email when it succeeded and the email pipeline broke at the same time the cron did.',
      ],
    },
    {
      h2: 'Log management without learning a new query language',
      paragraphs: [
        'The deliberate choice in the logs layer is to skip the query-language step that Splunk\'s SPL, Datadog\'s search syntax, and the various Lucene-derived languages all require. The customer types the words they remember from the log line and the platform searches for them. The standard filters compose with obvious syntax (`service:checkout AND level:error`). The auto-extracted facets handle the discoverability problem — the customer does not have to know in advance which fields exist on which log shapes; the platform extracts them at ingest and exposes them as clickable filters in the sidebar.',
        'For the patterns that single-line search cannot find, the platform ships pattern grouping. A spike of ten thousand near-identical log lines — the kind of spike that happens when a single bug fires on every request — collapses to one row showing the canonical shape, the count, the first-seen timestamp, and the last-seen timestamp. The on-call engineer investigating the spike sees the one thing that matters rather than scrolling through ten thousand variations of it. Recurring stack traces — the kind of thing Sentry charges as a separate product — collapse the same way, with the same first-seen and last-seen metadata, plus a sample and a count, and a "resolved" toggle that the engineer can flip when the underlying bug is fixed.',
        'Alerting on log volume is built into the same pipeline as the uptime alerts. The customer can write threshold alerts when they know the magic number ("more than ten errors in five minutes"), spike-vs-baseline alerts when "normal" varies by service or time-of-day ("three times the normal rate, however the platform defines normal for this signal"), or save any log search as a time-series metric and alert on it like any other monitor. Alerts route to email, Slack, Discord, Teams, Telegram, or any HMAC-signed webhook. The de-duplication discipline is strict — one incident per fire, never a hundred — which is the operational primitive that distinguishes a usable alert pipeline from an alert-fatigue generator.',
        'Pricing on the logs surface is the published bundled-volume model: one gigabyte per month on the free tier, ten gigabytes on the Startup plan, one hundred gigabytes on the Pro plan. Every plan includes every feature on the logs page — there is no "intelligence tier" that gates the pattern grouping or the live-tail behind a higher SKU. The principle is consistent with the rest of the Ollasoftware portfolio: capability gating per tier loses customers as fast as the tiering picks them up.',
      ],
    },
    {
      h2: 'SIEM that opens incidents in the same pipeline as the uptime checks',
      paragraphs: [
        'The most common operational mistake in the observability-plus-security category is to ship the two as separate products with separate consoles. The security alert lives in the SIEM, the engineering alert lives in the observability platform, and the on-call engineer who has to handle both has to learn two products, switch context between them, and reconstruct the cross-platform timeline manually during any incident that crosses the boundary. The platform inverts that by treating a security detection as just another rule that opens an incident in the same pipeline as a failed health check.',
        'Fifty detection rules across ten packs ship by default. Most of them carry their MITRE ATT&CK technique tag, which means a detection that opens an incident is also a structured pointer into the attacker behaviour model the security team is already trained against. The packs cover access (failed logins, privilege escalations, credential stuffing), exfiltration (outbound volume anomalies, suspicious destinations), secrets (token leaks, environment-variable exposure), web attacks (SQLi, XSS, path traversal), reliability (sudden error-rate spikes, dependency failures), threat intelligence (known-bad IPs, Tor exits, datacenter ranges), AI-agent security (prompt injection, runaway tool loops, sensitive tool calls), MCP traffic (anomalous tool invocation patterns), AWS control plane (suspicious IAM activity, anomalous instance launches), and a tenth pack for the less-common but still important patterns.',
        'The customer can write their own detection rules in a one-line KQL-lite syntax that handles the common patterns without requiring the customer to learn a new dialect. The rules open incidents in the same pipeline as every other signal. The incidents route through the same alerting layer as every uptime check, with the same de-duplication, the same channel routing, and the same on-call rotation logic.',
        'Multi-event correlation handles the patterns a single log line cannot express. Sequence correlation — failed logins immediately followed by a successful one — runs every minute. Cardinality correlation — one IP touching many accounts in a short window — runs every minute. The correlation engine is fast enough that the security team gets the multi-event signal in near-real-time rather than as a batch report the next morning.',
        'Threat-intel matching runs inline at ingest. Every source IP that appears in an event is checked against the platform\'s curated indicators (known-bad IPs, Tor exits, DNSBL listings, VPN and datacenter ranges) and the customer\'s own bring-your-own indicators (IPs, domains, hashes) at the moment the event lands. The IP-is-bad context is on the event by the time any detection rule looks at it, which means the rules can be written to test the enriched event rather than to invoke a threat-intel lookup themselves.',
      ],
    },
    {
      h2: 'AI-agent observability and security — the newest layer, in the same pipeline',
      paragraphs: [
        'The bet underneath the AI-agent observability and security layer is that the agents your team has shipped over the past eighteen months are production traffic now, generating signal that the existing four-vendor observability stack cannot see. The platform reads OpenTelemetry GenAI spans — the standardised semantic conventions for AI agent traces that the OpenTelemetry community has been ratifying over the past two years — and surfaces token cost, latency distribution and error rate per agent, per model, and per tool. The dashboard pages mirror the dashboard pages for traditional services so the operational team learns one interface and uses it across both kinds of workload.',
        'The security half of the AI-agent layer is built around three detection categories that the existing SIEM vendors do not handle natively today. Prompt injection detection watches for the patterns that distinguish a malicious user input — instructions designed to override the agent\'s system prompt — from a legitimate one. Runaway tool loop detection watches for the conversational shape where an agent calls the same tool repeatedly with subtle variations, which is the canonical failure mode of an agent stuck in a planning loop. Sensitive tool call detection watches for the cases where an agent invokes a tool that touches regulated data, financial data, or production-mutating actions, and flags the invocation for human review when the upstream context indicates the call may have been triggered by an injected instruction rather than a legitimate user request.',
        'All three detection categories open incidents in the same pipeline as every other signal. The on-call engineer responding to a runaway tool loop incident gets the agent\'s trace, the conversation history, the detection rule that fired, the confidence score, and the recommended response action — usually "kill the agent\'s active session and review the prompt." For teams running production AI agent workloads at any volume, this layer is the difference between operating the agents with confidence and operating them with crossed fingers.',
        'The agent layer is also the place where the platform demonstrates its operational discipline most concretely. Every detection rule that fires on an agent\'s trace cites the specific span, the specific tool call, and the specific token interaction that triggered the rule. The audit log records the human review action — the kill, the approval, the escalation — and ties it back to the incident through the standard incident-management surface. The full operational loop for AI agents looks like the full operational loop for traditional services, which is the property that makes the layer usable rather than the demo it would be if it lived in a separate product.',
      ],
    },
    {
      h2: 'The agent-callable API: tool defs, MCP server, idempotency, scopes',
      paragraphs: [
        'Every endpoint on the platform is also a tool an AI agent can call. The pure-REST API was designed from day one for the case where the caller is an autonomous agent rather than a human writing curl commands by hand, which is a meaningfully different design constraint than the API surfaces of the established observability vendors.',
        'Pre-converted tool definitions are published for the three most common agent runtimes — OpenAI\'s function-calling format, Anthropic\'s tool-use format, and LangChain\'s structured tool definition. Drop the definitions into the agent\'s tool registry and the agent can drive the entire platform: open incidents, search logs, query the knowledge graph, list devices, rotate tokens, acknowledge alerts, write detection rules, manage on-call rotations. The MCP server at the platform\'s MCP endpoint exposes the same capabilities with MCP-shaped contracts for the agents that prefer that protocol.',
        'For the asynchronous patterns that polling-based APIs handle badly, the platform ships HMAC-SHA256-signed event webhooks. The agent registers a webhook URL, the platform fires structured events to it as state changes — incidents open, incidents close, detections fire, monitors degrade — and the agent reacts when the event arrives rather than polling and missing the moment. The webhooks carry an `Idempotency-Key` and a replay-protection timestamp so the agent can safely retry receipt without double-counting.',
        'Rate-limit headers are returned on every response in a shape the agent\'s SDK reads natively. The agent backs off when the platform indicates back-pressure rather than burning through a quota in a runaway loop. Every mutation accepts an `Idempotency-Key` header so the agent can retry without fear that the second attempt will create a duplicate object. The combination of those two primitives is the operational discipline that distinguishes an agent-safe API from one that the agent will eventually use to set itself on fire.',
        'Scope management is the final piece. Twenty-four narrow personal-access-token scopes — `monitors:read`, `monitors:write`, `logs:read`, `detections:write`, `incidents:write`, and so on — let the customer mint one token per workload (one for the CI pipeline that updates monitor definitions, one for the SOC agent that reads detections, one for the AI analyst that opens incidents, one for the partner integration that fans out events). Each token carries an explicit expiry, an explicit daily call cap, and a recorded last-used timestamp. The scope discipline is the same shape that the OllaDNS team ships on the DNS platform, and it is the scope discipline that an auditor expects from a production observability platform.',
      ],
    },
    {
      h2: 'The collector, the Linux sensor, and the integration surface',
      paragraphs: [
        'For the workloads that do not naturally emit OpenTelemetry or that need richer host-level signal than a log line can carry, the platform ships a Linux sensor that captures host telemetry from a single command-line install. The sensor reports process inventory, network connection state, file integrity, system-call patterns, and the host-side signal that lets the SIEM detection rules reason about what is happening on the host rather than only about what the host is sending out. The sensor is a complement to the application-side telemetry rather than a replacement; teams that have invested heavily in OpenTelemetry instrumentation continue to use it and add the sensor only where the host-level signal is the missing piece.',
        'The general-purpose collector handles the cases where the customer wants to forward telemetry from a third-party source the platform does not natively integrate with. It speaks OpenTelemetry, accepts webhook fan-out from arbitrary HTTP sources, and proxies common log shapes (syslog, journald, JSON-over-HTTP) into the platform\'s normalised event format.',
        'The integration surface beyond the collector is the dozen-source ingestion catalogue covering the common cloud and runtime origins of production logs — AWS Lambda through CloudWatch, Heroku through log drains, Vercel through the dashboard, Docker through the syslog driver, systemd through journald, any OpenTelemetry-compatible SDK, Vector pipelines, Fluent Bit pipelines, raw curl of structured JSON. The bias is toward "ingest from where the logs already are" rather than "force the customer to install a specific agent on every host" — which lowers the integration burden for teams that have already standardised on a particular log shape.',
        'For the alerting and incident-management side, the integration surface is broad in both directions. Inbound: any signal source can fire an incident through the webhook surface or the API. Outbound: incidents route to email, Slack, Discord, Microsoft Teams, Telegram, PagerDuty, Opsgenie, or any HMAC-signed webhook the customer points the platform at. Status pages can ride custom domains and let subscribers receive automated updates without the customer building a separate status-page infrastructure.',
      ],
    },
    {
      h2: 'How 24observe compares to the established vendors',
      paragraphs: [
        'The observability category has more vendors than it has clear winners and it is worth being direct about how the platform sits against each name in the comparison set the brand itself publishes.',
        'Datadog is the polished, well-engineered, expensive incumbent across the broadest observability surface. Datadog has spent more than a decade building the integrations, the depth, the ecosystem and the SLA tier that the Fortune-500 SRE buyer requires, and it is the right choice for that buyer. <a href="https://24observe.com/">24observe</a> matches the working subset of Datadog that production engineering teams below the Fortune-500 tier actually use — synthetics, log management, RUM-adjacent monitoring, SIEM detections, alerting — at a unit cost that is meaningfully lower at every comparable volume, with the AI-agent observability layer included rather than sold as a separate SKU. The honest framing is that Datadog is the right choice when operational simplicity dominates and budget is not a constraint; the platform is the right choice for the very large middle below that tier.',
        'Splunk is the SIEM and log-management incumbent at the very-large-enterprise level. Splunk\'s install base and procurement gravity are real, and the buyer who has already standardised on Splunk for compliance reasons is rarely moved by feature gaps in a competing product. The platform sits below Splunk on raw SIEM enterprise pedigree and above Splunk on operating-model fit for the engineering-and-security teams that want a single platform rather than a security-only product layered on top of a separate observability stack. The Splunk-migration path is a published workstream the team has built tooling for; for the customer who is at the renewal point on a Splunk contract and considering whether the next decade should be the same shape as the last, the platform is the alternative that compares most directly.',
        'Grafana — the open-source observability stack the customer assembles from Loki for logs, Mimir for metrics, Tempo for traces, OnCall for incident routing, and the various community-built dashboards — is a different shape of bet. Grafana is the right answer for teams that genuinely want to assemble the stack from parts and have the engineering capacity to operate it. The platform\'s value over the Grafana stack is the integration work — the same engineering hours that would be spent wiring Loki and Mimir together and operating them are spent shipping product instead. For teams whose engineering capacity is bounded, the platform is the alternative; for teams whose preference is the assemble-from-parts model, Grafana is the alternative.',
        'PagerDuty is the on-call and incident-management specialist. PagerDuty\'s install base in the SRE category is real and the product is genuinely well-built within its narrow scope. The platform ships the on-call and incident-management surface as part of the broader product rather than as a separate vendor — which means a customer who currently runs Datadog plus PagerDuty plus Splunk plus an uptime vendor can consolidate three of those four into the platform and keep PagerDuty only if there is a specific PagerDuty primitive the team depends on that the platform does not match.',
        'Elastic — the ELK stack assembled into a hosted product or run by the customer — is the closest peer for the log-management primitive specifically. Elastic is excellent at log search at scale and has a strong following among teams that prefer the dense querying surface. The platform\'s extension over Elastic is the integrated SIEM detections, the integrated AI-agent layer, and the integrated incident-management pipeline; for a team using Elastic only for logs and currently buying the rest separately, the consolidation case is straightforward.',
        'Across all of these, the question is rarely "is the platform cheaper per gigabyte." It is "for the operational stack my team is actually running, what is the total cost of ownership — including the engineering cost of integration, the operational cost of running four vendors in parallel, and the unit cost of the bills themselves — compared to a single platform that handles the whole surface." For most engineering teams in the series-A-to-mid-market range, the answer points clearly at the platform.',
      ],
    },
    {
      h2: 'The team and the parent group',
      paragraphs: [
        '24observe is built and operated by <a href="https://ollasoftware.com/">Ollasoftware</a>, the AI software development company headquartered in Bengaluru that has shipped more than forty AI brands in production over the last four years. The platform sits in the Ollasoftware infrastructure cluster alongside <a href="https://ollasoftware.com/blog/olladns/">OllaDNS</a> (the DNS-filtering platform) and <a href="https://ollasoftware.com/blog/ollagraph/">Ollagraph</a> (web intelligence for AI agents), sharing the same async-Rust + Postgres + <a href="https://clickhouse.com/" rel="noopener noreferrer">ClickHouse</a> substrate that makes high-volume telemetry cost-efficient. <a href="https://ollasoftware.com/blog/ollabear/">Ollabear</a> and <a href="https://ollasoftware.com/blog/ollasuper/">OllaSuper</a> both consume the platform\'s observability primitives as first-party internal consumers. The shared substrate is the reason a small team can ship the breadth the platform covers without a Fortune-500 vendor\'s engineering headcount.',
        'The team behind 24observe specifically came from inside the operations and security side of Ollasoftware — the engineers who had been running the parent company\'s own observability and security stack across the broader portfolio of 40+ brands, and who built the platform initially to replace the four-vendor stack their own teams were operating. The platform is, in a real sense, the product that an operations team building for themselves would have built, then chose to ship as a commercial product when it became obvious that the same operating-model gap existed across most engineering teams below the Fortune-500 tier.',
        'The parent group, <a href="https://www.networkershome.com/" rel="noopener">Networkers Home</a>, is the cybersecurity and networking training institute that has placed more than forty-five thousand alumni across eight hundred hiring partners since 2007. The connection matters here because the network-monitoring and security-detection primitives the platform ships — SNMP-based network telemetry, Cisco and Palo Alto and Fortinet integrations, the MITRE ATT&CK-tagged detection content — are exactly the disciplines the institute has been teaching its alumni for two decades. The platform is, in part, the product the parent group\'s alumni network has been asking for as their own engineering organisations have grown into the operating-model gap the platform is built to close.',
      ],
    },
    {
      h2: 'What is on the roadmap',
      paragraphs: [
        'The team publishes the roadmap on the brand site and updates it as work ships. The visible near-term threads are concrete: an expanded detection-pack catalogue covering specific industry verticals (fintech-specific patterns, healthtech-specific patterns, e-commerce-specific patterns), deeper coverage of the AI-agent security category as more failure modes emerge in production agent workloads, expanded MCP workflow tools beyond the current default set, and additional Linux-sensor capability as the customer base requests new host-level signal categories.',
        'Underneath those visible features is steady investment in the AI-analyst layer. The current analyst handles the common incident shapes well; the roadmap is to extend it to the less-common shapes (cross-service correlation patterns, multi-region failure patterns, capacity-planning patterns) without sacrificing the evidence-citation discipline that makes the verdicts trustworthy. The team has been explicit that an analyst that produces confident but untraceable verdicts is worse than no analyst at all, and the roadmap respects that constraint.',
        'On the integration side, the team is expanding the inbound source catalogue at a measured pace based on customer demand patterns. The bias is toward integrations that bring in signal the platform cannot otherwise see (proprietary cloud vendor surfaces, internal-only protocols, specialised security feeds) rather than toward me-too integrations for sources the platform already handles through the OpenTelemetry or webhook paths. The integration roadmap is published and the team takes inbound requests through the docs site.',
        'Pricing has the published bundled-volume model — Free 1 GB/month, Startup 10 GB, Pro 100 GB — with every feature available on every plan. The team has signalled that the unit economics will not get more expensive over time; they will get cheaper as the underlying infrastructure cost compounds down and the savings pass through. The principle is consistent across the Ollasoftware portfolio: a platform whose pricing only goes up loses customers as fast as it adds them.',
      ],
    },
    {
      h2: 'How to start',
      paragraphs: [
        'If you currently run the four-vendor observability stack — an uptime monitor, a log platform, a SIEM, and an agent-API layer of some kind — and the operational cost of running it has crossed into the territory where consolidation looks attractive, the right next move is to evaluate the platform on a real workload. Sign up at <a href="https://24observe.com/">24observe.com</a>, claim the free tier, point one of your existing telemetry pipelines at the platform, and look at how it handles your specific shape of workload.',
        'The Quickstart walks the first ten minutes — sign up, install the collector or wire an existing OpenTelemetry pipeline, configure a representative uptime check, ingest a meaningful slice of your logs, enable a detection pack relevant to your stack, and see the AI analyst handle a synthetic incident end to end. The free tier covers enough volume to run that evaluation on real data without entering a credit card. The principle is consistent with the rest of the Ollasoftware portfolio: the case for adoption is most legible when measured against your own workload rather than against a synthetic benchmark.',
        'If you would like the team to walk you through a migration plan — particularly the Datadog, Splunk, or Pingdom migration paths the team has built tooling for — the <a href="https://ollasoftware.com/contact/">Ollasoftware contact page</a> reaches the engineers who built the platform. Migration is rarely as painful as the procurement team fears once the export and the import paths are well-trodden, and the team has invested in the tooling that makes the common migration paths concrete rather than aspirational.',
        'For teams running production AI agent workloads in particular, the AI-agent observability and security layer is the place to start the evaluation. Point your agents\' OpenTelemetry GenAI spans at the platform, watch the cost and latency surface come alive, enable the AI-agent detection pack, and look at the kinds of incidents the platform surfaces from the agent traffic that the existing four-vendor stack cannot see. For most teams running agents at any volume, the layer pays for itself on its own before the rest of the platform is even evaluated.',
        'And if you are not yet sure whether consolidation onto a single observability platform is the right priority for your team this quarter, the published documentation, the changelog, the roadmap, and the public comparison pages against each of the established vendors are all open. The platform\'s case is most legible against a specific competing stack rather than against an abstract pitch; the comparison surface is the team\'s way of inviting that specific evaluation.',
      ],
    },
  ],
  faqs: [
    {
      q: 'What is 24observe?',
      a: '24observe is a cloud observability and security platform that collapses uptime monitoring, log management, SIEM detections, and an agent-callable API into one product on a single operational knowledge graph. An AI analyst walks the graph during incidents to deliver evidence-cited verdicts — root cause and the fix — in seconds. Operated as a managed SaaS service by Ollasoftware.',
    },
    {
      q: 'What does 24observe pricing look like?',
      a: 'Bundled-volume tiers with every feature available on every plan. Free covers 1 GB/month of logs, Startup covers 10 GB, Pro covers 100 GB. No "intelligence tier" gating pattern grouping, live-tail, AI-agent observability or any other capability behind a higher SKU. Enterprise contracts move to predictable monthly minimums with the same data-handling guarantees.',
    },
    {
      q: 'What are the seven uptime check types?',
      a: 'HTTP/HTTPS, TCP, SSL/TLS certificates (with 7-day expiry warnings), ICMP ping, port probe, keyword match (does the page still say what it should), and inverted heartbeat-or-cron (your job pings the platform on its interval; silence opens an incident). All run from multi-region probes with SLO targets and status-page integration.',
    },
    {
      q: 'How does the SIEM layer work?',
      a: '50 detection rules across 10 packs (access, exfil, secrets, web attacks, reliability, threat intelligence, AI-agent security, MCP traffic, AWS control plane, plus a tenth pack for less-common patterns). Most rules carry their MITRE ATT&CK technique tag. Multi-event correlation handles sequence and cardinality patterns. Threat-intel matching runs inline at ingest. Detections open incidents in the same pipeline as a failed health check.',
    },
    {
      q: 'How does the AI-agent observability layer work?',
      a: 'Send your agents\' OpenTelemetry GenAI spans to the platform. The dashboards surface cost, latency and error rate per agent and per model. Detection rules in the AI-agent security pack flag prompt injection, runaway tool loops, and sensitive tool calls — all of which open incidents in the same pipeline as every other signal. Built for production agent workloads, not for prototypes.',
    },
    {
      q: 'How is the API designed for AI agents?',
      a: 'Pre-converted tool definitions for OpenAI, Anthropic and LangChain ship out of the box. A native MCP server exposes the full capability surface. Signed event webhooks replace polling. Rate-limit headers your agent reads to back off. Idempotency-Key on every mutation. 24 narrow PAT scopes (`monitors:read`, `detections:write`, etc.) with per-key expiry and daily call caps.',
    },
    {
      q: 'How does 24observe compare to Datadog, Splunk, Grafana, PagerDuty and Elastic?',
      a: 'Datadog is the polished expensive incumbent for the Fortune-500 SRE buyer; 24observe is cheaper and broader for the very-large-middle below that tier with AI-agent observability included. Splunk is the SIEM incumbent at enterprise; 24observe sits below on pedigree and above on operating-model fit for engineering-and-security teams that want one platform. Grafana is the assemble-from-parts open-source path; 24observe is the integrated alternative. PagerDuty is the on-call specialist; 24observe ships the on-call surface as part of the broader product. Elastic is excellent at log search; 24observe extends it with integrated SIEM, AI-agent, and incident pipeline.',
    },
    {
      q: 'Who is behind 24observe?',
      a: '24observe is built and operated by Ollasoftware, the Bengaluru-headquartered AI software development company. The Rust engineering group that ships the platform also ships OllaDNS (DNS filtering) and Qcrawl (distributed crawl scheduler), sharing an internal substrate of async-Rust services, Postgres + ClickHouse, and Caddy. The parent group is Networkers Home, the cybersecurity and networking training institute founded in 2007 with 45,000+ alumni placed across 800+ hiring partners.',
    },
  ],
};
